window.CASE_SESSION={
  id:'03',storage:'titanic-voyage-03:state:v1',lab:'Bridge Watch 03',hero:'iceberg-hero',
  start:{eyebrow:'JELLY SEA DETECTIVES · TITANIC CASE 03',title:'The Mystery of<br><em>the Silent Warnings</em>',lead:'얼음 경고가 왜 함교에 닿지 않았는지 읽고, 망루·무선실·조타 세 자리를 계획한 순서대로 하나씩 점검하세요.'},
  caseLines:[
    ['WATCH REPORT · SUNDAY, APRIL 14','Other ships sent ice warnings all day. By two o’clock, Captain Smith had received several of them.'],
    ['NIGHT LOG','The night was clear and the sea was very calm. The ship kept running at nearly top speed, about 26 miles per hour.'],
    ['UNRESOLVED QUESTION','Why did the warnings stay silent? Plan a short sequence, then check each station until every warning reaches the bridge.']
  ],
  goal:{question:['What is the best watch goal?','가장 알맞은 점검 목표는 무엇일까요?'],correct:'deliver',choices:[
    ['fast','Press every control as fast as possible.','모든 조작 버튼을 최대한 빨리 누른다.'],
    ['deliver','Plan, check, and fix the three stations so every warning reaches the bridge.','세 자리를 계획하고 점검해 모든 경고가 함교에 닿게 한다.'],
    ['photo','Take a picture of the iceberg.','빙산 사진을 찍는다.']
  ]},
  words:[["receive", "to get something that is sent · 받다 : 보내온 것을 손에 넣다", "The wireless room received another ice warning.", ["receive", "received"], "re·ceive"], ["several", "more than two, but not many · 여럿 : 두셋보다 많은", "Several ships reported ice that day.", ["several"], "sev·er·al"], ["calm", "still and quiet · 잔잔한 : 움직임이 없이 고요한", "The sea was very calm that night.", ["calm"], "calm"], ["station", "a place where one job is done · 자리 : 한 가지 일을 맡아 하는 곳", "Check one station at a time.", ["station", "stations"], "sta·tion"], ["bridge", "the room from which the captain steers the ship · 함교 : 선장과 항해사가 배를 조종하는 방", "The lookout phoned the bridge.", ["bridge"], "bridge"], ["lookout", "a person who watches for danger · 망보는 사람 : 위험이 없는지 살피는 사람", "The lookouts watched for ice from the crow’s nest.", ["lookout", "lookouts"], "look·out"], ["binoculars", "a tool with two tubes that makes far things look close · 쌍안경", "The lookouts had no binoculars.", ["binoculars"], "bin·oc·u·lars"], ["wireless", "a radio machine that sent messages without wires · 무선 전신 : 전선 없이 소식을 보내는 기계", "The wireless room received the warning.", ["wireless"], "wire·less"], ["operator", "a person who runs a machine · 기사 : 기계를 다루는 사람", "The wireless operator was very busy.", ["operator", "operators"], "op·er·a·tor"], ["telegram", "a message sent by wireless or wire · 전보 : 전신으로 보내는 짧은 소식", "He had a big stack of passenger telegrams.", ["telegram", "telegrams"], "tel·e·gram"], ["deliver", "to carry something to the right place · 전달하다 : 가야 할 곳까지 가져다주다", "Two warnings were never delivered to the bridge.", ["deliver", "delivered"], "de·liv·er"], ["steer", "to turn a ship in a direction · 조종하다 : 배의 방향을 잡다", "Steer farther south, away from the ice.", ["steer", "steering"], "steer"], ["course", "the way a ship travels · 항로 : 배가 가는 길", "The captain changed the ship’s course.", ["course"], "course"], ["farther", "a longer way · 더 멀리", "The Titanic would travel farther south.", ["farther"], "far·ther"], ["reduce", "to make less · 줄이다", "He did not reduce the ship’s speed.", ["reduce"], "re·duce"], ["officer", "a crew leader who helps the captain · 항해사 : 선장을 돕는 배의 간부", "The officer turned the wheel as far as it would go.", ["officer", "officers"], "of·fi·cer"], ["iceberg", "a huge piece of ice floating in the sea · 빙산 : 바다에 떠다니는 큰 얼음 덩어리", "The iceberg struck the ship.", ["iceberg", "icebergs"], "ice·berg"], ["struck", "hit hard · 부딪쳤다 : 세게 부딪혔다", "The Titanic struck the iceberg.", ["struck"], "struck"], ["sequence", "an order of steps · 순서 : 일이 이루어지는 앞뒤의 차례", "Turn the night into a clear sequence.", ["sequence"], "se·quence"], ["assistant", "a helper · 조수 : 곁에서 돕는 사람", "The assistant operator carried a warning to the bridge.", ["assistant"], "as·sis·tant"]],
  strategy:{labels:['짧게 계획','하나씩 실행','결과 확인'],game:'먼저 순서를 정하고 한 자리씩 점검해요',check:'세 자리의 결과가 모두 바뀌었는지 확인해요'},
  guide:{game:[
    {en:'Make a short three-step watch plan.',ko:'세 단계의 짧은 점검 계획을 세워요.'},
    {en:'Check only the station marked CHECK NOW.',ko:'CHECK NOW로 표시된 자리 하나만 점검해요.'},
    {en:'See the result before the next station.',ko:'다음 자리로 가기 전에 결과를 확인해요.'}
  ]},
  game:{type:'systems',title:'Keep every warning moving to the bridge.',eyebrow:'BRIDGE WATCH',intro:'Choose a watch order. Then test one control in each station.',items:[
    {id:'lookout',name:'LOOKOUT · CROW’S NEST',problem:'A dark, clear night and a very calm sea. The lookouts have no binoculars and must spot ice early.',correct:'Keep a careful watch and phone the bridge the moment a shape appears.',options:['Keep a careful watch and phone the bridge the moment a shape appears.','Wait until the shape is very close, then ring the bell.','Watch the passengers on the deck instead of the sea.']},
    {id:'wireless',name:'WIRELESS ROOM',problem:'Ice warnings arrive between a big stack of passenger telegrams. One warning is written down and set aside.',correct:'Carry every ice warning to the bridge before sending more passenger telegrams.',options:['Answer “I am busy” and keep sending passenger telegrams.','Carry every ice warning to the bridge before sending more passenger telegrams.','Send the ice warning back to the ship that sent it.']},
    {id:'bridge',name:'BRIDGE · STEERING',problem:'The ship runs at nearly top speed, about 26 miles per hour. Its course leads straight into the ice.',correct:'Reduce speed and steer farther south, away from the reported ice.',options:['Keep top speed so the ship reaches New York early.','Turn off the engines and stop in the dark.','Reduce speed and steer farther south, away from the reported ice.']}
  ]},
  check:{title:'Which watch report matches the night?',lead:'Look at the three safe stations and choose the complete report.',correct:'complete',choices:[
    ['lookout','Only the lookouts needed a change.'],['complete','The lookout, the wireless room, and the bridge each needed a matching action.'],['random','Pressing controls in any order made the warnings arrive.']
  ],success:'Watch complete. A short plan kept one warning from being forgotten.'},
  reading:{title:'Warnings That Never Reached the Bridge',easy:[
    'On Sunday, April 14, the Titanic sailed into waters where other ships had reported ice.','Captain Smith moved the ship farther south and told the lookouts to watch carefully.','More ice warnings reached the wireless room, but two were never delivered to the bridge.','One operator was busy with passenger telegrams and set an important warning aside.','A lookout saw the iceberg just before 11:40 P.M., too late to steer the ship away.'
  ],challenge:[
    'By two o’clock on Sunday afternoon, Captain Smith had received several ice warnings from other ships.','He steered farther south but did not reduce the ship’s speed, about 26 miles per hour.','The assistant operator carried a 7:30 warning to the bridge, but the captain was at dinner.','Another warning was set aside because the busy wireless operator was sending passenger telegrams.','The officer slowed the engines and turned the wheel, but the ship still struck the iceberg.'
  ]},
  organize:{type:'repair-order',title:'Turn the night into a clear sequence.',lead:'Place the three event cards in the order they happened. Then type the final checking word.',bank:'EVENT CARDS',cards:[
    ['warn','Ice warnings arrive in the wireless room.'],['spot','The lookout sees a dark shape and phones the bridge.'],['turn','The officer slows the engines and turns the wheel.']
  ],blank:['After every warning,','that the bridge received it.'],answer:'check'},
  retell:{title:'Why did the warnings stay silent?',prompt:'Write a short watch report in English. Use order words and name at least two stations.',placeholder:'First, the wireless room... Next... Finally...',frame:'First, the ____ received ____. Next, the ____ did not ____. Finally, the bridge ____.'},
  solved:{eyebrow:'CASE 03 · WARNINGS DELIVERED',title:'계획하고 하나씩 확인해<br>조용한 경고를 함교까지 전했어요!',text:'해야 할 일이 여러 개일 때는 짧은 순서를 만들고, 한 단계가 끝날 때마다 결과를 확인하면 빠뜨리는 경고가 줄어듭니다.'},
  coach:{watch:'정답 버튼을 찾는 속도보다, 시작 전에 세 자리(망루·무선실·함교)의 순서를 스스로 정하고 완료 표시를 따라가는지 관찰합니다.',answer:'LOOKOUT: careful watch + phone the bridge at once. WIRELESS: carry every ice warning to the bridge first. BRIDGE: reduce speed + steer farther south. 순서 카드 3장(경고 도착→발견·전화→감속·조타)을 모두 놓으면 통과. 빈칸: check.'}
};
