(()=>{"use strict";
const data=window.LESSON_DATA,level=window.LESSON_LEVEL,pages=[...document.querySelectorAll(".page")];let page=0,predictIndex=0,questionIndex=0,questionAttempts=0,spyIndex=0,classifyIndex=0,verifyIndex=0,verifyCoachStep=0,transferIndex=0,toastTimer;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={classification:shuffle(data.classification.slice()),counts:{solar:0,wind:0,tidal:0,biomass:0},reflection:"",reflectionStrategy:""};
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function log(action,itemId,extra={}){const detail={lessonId:"l14-renewable-energy-careful-reading",lessonVersion:"1.0.57",level,action,itemId,timestamp:new Date().toISOString(),...extra};document.dispatchEvent(new CustomEvent("oncuvate:log",{detail}));window.parent?.postMessage({type:"ONCUVATE_LESSON_EVENT",...detail},"*")}
function showToast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2200)}
function feedback(el,message,type){el.textContent=message;el.classList.remove("ok","bad");if(type)el.classList.add(type)}
function normalize(v){return String(v||"").replace(/[\s.,!?·'\"“”‘’]/g,"")}
function normalizeShortAnswer(v){return normalize(v).replace(/(입니다|이에요|예요|이다)$/,"")}
function showPage(next){page=Math.max(0,Math.min(pages.length-1,next));pages.forEach((p,i)=>p.classList.toggle("active",i===page));$$('.step-link').forEach((b,i)=>{b.classList.toggle("active",i===page);b.toggleAttribute("aria-current",i===page)});$$('.step-dots button').forEach((b,i)=>b.classList.toggle("active",i===page));$("#progressBar").style.width=((page+1)/pages.length*100)+"%";$("#backButton").disabled=page===0;$("#nextButton").textContent="다음";$("#nextButton").classList.toggle("hidden",page===pages.length-1);$("#stage").scrollTop=0;const dock=$("#annotationDock"),toolbar=$("#annotationToolbar"),dockToggle=$("#annotationDockToggle");if(dock){dock.classList.toggle("hidden",page!==1);if(page!==1){toolbar.classList.add("hidden");dockToggle.setAttribute("aria-expanded","false")}}log("page_view","page-"+(page+1));spyOnPage(page);window.dispatchEvent(new Event("resize"))}
function setupAnnotationDock(){const toggle=$("#annotationDockToggle"),toolbar=$("#annotationToolbar");toggle.onclick=()=>{const open=toolbar.classList.toggle("hidden")===false;toggle.setAttribute("aria-expanded",String(open));log("annotation_panel",open?"open":"close")}}
function setupNavigation(){const dots=$("#stepDots");pages.forEach((_,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",(i+1)+"단계로 이동");b.onclick=()=>showPage(i);dots.append(b)});$$('[data-go]').forEach(b=>b.onclick=()=>showPage(Number(b.dataset.go)));$("#backButton").onclick=()=>showPage(page-1);$("#nextButton").onclick=()=>{if(page===pages.length-1){finish()}else showPage(page+1)};$("#menuButton").onclick=()=>{const s=$("#sidebar"),open=!s.classList.contains("open");s.classList.toggle("open",open);$("#menuButton").textContent=open?"◀":"▶";$("#menuButton").setAttribute("aria-expanded",String(open))};$("#helpButton").onclick=()=>showToast(["제목과 그림을 보고 낱말을 예상해요.","본문을 가린 뒤 단어나 짧은 구로 기억을 확인해요.","숫자 타일을 골라 문장이 본문과 같은지 O·X로 판정하고, 다르면 틀린 낱말을 눌러요.","카드의 핵심 낱말을 발전 방식과 연결해요.","대상과 개수를 먼저 확인한 뒤 답을 골라요.","새 글에서도 같은 확인 방법을 사용해요.","오늘 실수한 것을 고르고, 다음에 사용할 방법을 확인해요."][page])}
function setupIntro(){const gate=$("#introGate"),start=$("#introStart"),params=new URLSearchParams(location.search),force=params.get("intro")==="1",seen=sessionStorage.getItem("oncuvate-energy-intro-seen")==="1";gate.classList.toggle("hidden",seen&&!force);start.onclick=()=>{sessionStorage.setItem("oncuvate-energy-intro-seen","1");gate.classList.add("hidden");const requested=params.get("level");if(requested!=="steady"&&requested!=="deep")$("#levelGate").classList.remove("hidden");log("intro_start","intro",{level:requested||"not-selected"})}}
function setupLevel(){const requested=new URLSearchParams(location.search).get("level");$("#levelGate").classList.toggle("hidden",requested==="steady"||requested==="deep");$$('[data-level-choice]').forEach(b=>b.onclick=()=>location.href="session01.html?level="+b.dataset.levelChoice);$("#changeLevel").onclick=()=>$("#levelGate").classList.remove("hidden");$("#levelPill").textContent=data.level+" · "+data.label;$("#readingLevel").textContent=data.label;$("#topTitle").textContent=data.title;$("#articleTitle").textContent=data.title}
function escapeHTML(v){const e=document.createElement("div");e.textContent=v;return e.innerHTML}
function renderPassage(){let html=data.paragraphs.map((p,i)=>'<p data-paragraph="'+i+'">'+escapeHTML(p)+'</p>').join("");data.vocab.forEach((v,i)=>{const word=escapeHTML(v[0]),button='<button class="vocab-word" type="button" data-vocab="'+i+'">'+word+'</button>';html=html.replace(word,button)});$("#passage").innerHTML=html;$$('[data-vocab]').forEach(b=>b.onclick=()=>openVocab(Number(b.dataset.vocab)));}
function openVocab(i){const v=data.vocab[i],saved=JSON.parse(localStorage.getItem("oncuvate-energy-vocab-"+level)||"[]");$("#vocabTitle").textContent=v[0];$("#vocabHanja").textContent=v[1];$("#vocabMeaning").textContent=v[2];$("#vocabExample").textContent=v[3];$("#vocabSave").dataset.index=i;$("#vocabSave").textContent=saved.includes(i)?"단어장에 담았어요":"단어장에 담기";$("#vocabDialog").classList.remove("hidden");log("vocab_open","vocab-"+i,{word:v[0]})}
function setupVocab(){$("#vocabClose").onclick=()=>$("#vocabDialog").classList.add("hidden");$("#vocabDialog").onclick=e=>{if(e.target===$("#vocabDialog"))$("#vocabDialog").classList.add("hidden")};$("#vocabSave").onclick=()=>{const i=Number($("#vocabSave").dataset.index),key="oncuvate-energy-vocab-"+level,saved=JSON.parse(localStorage.getItem(key)||"[]");if(!saved.includes(i))saved.push(i);localStorage.setItem(key,JSON.stringify(saved));$("#vocabSave").textContent="단어장에 담았어요";log("vocab_save","vocab-"+i,{word:data.vocab[i][0]})}}
function renderPrediction(){const item=data.prediction[predictIndex];$("#predictCounter").textContent=(predictIndex+1)+" / "+data.prediction.length;$("#predictProgress").style.width=((predictIndex+1)/data.prediction.length*100)+"%";$("#predictWord").textContent=item[0];feedback($("#predictFeedback"),"낱말을 살펴보고 판단해 보세요.");$("#predictNext").classList.add("hidden");$$('[data-predict-answer]').forEach(b=>{b.disabled=false;b.classList.remove("correct","wrong")})}
function setupPrediction(){$$('[data-predict-answer]').forEach(b=>b.onclick=()=>{const chosen=b.dataset.predictAnswer==="yes",correct=data.prediction[predictIndex][1];$$('[data-predict-answer]').forEach(x=>x.disabled=true);feedback($("#predictFeedback"),chosen===correct?(correct?"맞아요. 본문에서 이 낱말을 확인해 봐요.":"맞아요. 이 낱말은 주제와 관련이 없어요."):"그림과 제목의 주제를 다시 살펴보세요.",chosen===correct?"ok":"bad");log("answer","predict-"+predictIndex,{response:chosen,correct:chosen===correct});$("#predictNext").classList.remove("hidden")});$("#predictNext").onclick=()=>{if(predictIndex<data.prediction.length-1){predictIndex++;renderPrediction()}else{feedback($("#predictFeedback"),"예측을 마쳤어요. 이제 본문에서 확인해 봐요!","ok");$("#predictNext").classList.add("hidden")}}}
function addMemoryMessage(role,text,response=false){const row=document.createElement("div");row.className="memory-message "+role+(response?" memory-response":"");const label=document.createElement("span"),bubble=document.createElement("p");label.textContent=role==="coach"?"젤리코치":"나";bubble.textContent=text;row.append(label,bubble);$("#questionChat").append(row);$("#questionChat").scrollTop=$("#questionChat").scrollHeight}
function clearMemoryResponses(){$$(".memory-response",$("#questionChat")).forEach(x=>x.remove())}
function renderQuestion(){const q=data.questions[questionIndex],choices=$("#questionChoices"),next=$("#questionNext");questionAttempts=0;$("#questionCounter").textContent=(questionIndex+1)+" / "+data.questions.length;$("#questionChat").innerHTML="";addMemoryMessage("coach",q[0]);choices.innerHTML="";choices.classList.remove("hidden");choices.dataset.itemId="reading-q"+questionIndex;q[1].forEach((text,i)=>{const b=document.createElement("button");b.type="button";b.dataset.track="answer";b.dataset.response=text;b.dataset.correct=String(i===q[2]);b.innerHTML='<b>'+String.fromCharCode(65+i)+'</b><span>'+escapeHTML(text)+'</span>';b.onclick=()=>chooseMemoryAnswer(i,b);choices.append(b)});next.classList.add("hidden");next.textContent=questionIndex===data.questions.length-1?"확인 마치기":"다음 질문"}
function chooseMemoryAnswer(choice,button){const q=data.questions[questionIndex],correct=choice===q[2];questionAttempts++;log("answer","reading-q"+questionIndex,{response:q[1][choice],correct,attempt:questionAttempts});clearMemoryResponses();$$("button",$("#questionChoices")).forEach(b=>b.classList.remove("wrong"));if(!correct){button.classList.add("wrong");addMemoryMessage("coach","본문의 내용을 다시 떠올리고 다른 답을 골라 봐.",true);return}$$("button",$("#questionChoices")).forEach(b=>{b.disabled=true;b.classList.toggle("correct",b===button)});addMemoryMessage("coach",q[3],true);$("#questionNext").classList.remove("hidden")}
function setupReadingFlow(){const paper=$("#readingPaper"),cover=$("#passageCover"),panel=$("#questionPanel"),coach=$("#readingCoachPanel"),done=$("#readingDone"),toggle=$("#passageToggle");done.onclick=()=>{done.classList.add("hidden");paper.classList.add("covered");cover.classList.remove("hidden");coach.classList.add("hidden");panel.classList.remove("hidden");renderQuestion();log("reading_complete","reading-done",{level});window.dispatchEvent(new Event("resize"))};toggle.onclick=()=>{const peek=paper.classList.toggle("peek");toggle.textContent=peek?"본문 다시 가리기":"본문 다시 보기"}}function setupQuestions(){$("#questionNext").onclick=()=>{if(questionIndex<data.questions.length-1){questionIndex++;renderQuestion()}else{$("#questionChoices").classList.add("hidden");$("#questionNext").classList.add("hidden");clearMemoryResponses();addMemoryMessage("coach","여섯 문제를 모두 확인했어!",true)}}}
const SPY_LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const spy={status:[],attempts:[],lines:[],current:-1,phase:"",judgeMiss:0,locateMiss:0,audio:null,sound:true,particles:[],raf:0};
function spyIsFalse(item){return item.length>=3}
function spyTarget(tokens,item){return tokens.findIndex(t=>t.includes(item[1]))}
function spySound(kind){if(!spy.sound)return;try{spy.audio=spy.audio||new (window.AudioContext||window.webkitAudioContext)();const ctx=spy.audio,now=ctx.currentTime,notes={open:[[520,0,.09],[780,.06,.12]],ok:[[660,0,.1],[880,.08,.1],[1320,.16,.18]],bad:[[220,0,.16],[180,.1,.18]],fix:[[520,0,.08],[700,.07,.08],[940,.14,.08],[1250,.21,.2]],bingo:[[523,0,.12],[659,.1,.12],[784,.2,.12],[1047,.3,.3]],pick:[[420,0,.05]]}[kind]||[];notes.forEach(([f,t,d])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=kind==="bad"?"triangle":"sine";o.frequency.setValueAtTime(f,now+t);g.gain.setValueAtTime(.0001,now+t);g.gain.exponentialRampToValueAtTime(.16,now+t+.015);g.gain.exponentialRampToValueAtTime(.0001,now+t+d);o.connect(g).connect(ctx.destination);o.start(now+t);o.stop(now+t+d+.05)})}catch(e){}}
function spyFxSize(){const c=$("#spyFx"),r=window.devicePixelRatio||1;c.width=innerWidth*r;c.height=innerHeight*r;c.getContext("2d").setTransform(r,0,0,r,0,0)}
function spyBurst(x,y,count,colors,power=1,confetti=false){if(reduceMotion)return;for(let i=0;i<count;i++){const a=confetti?Math.PI/2+(Math.random()-.5)*1.2:Math.random()*Math.PI*2,v=(confetti?3+Math.random()*5:2+Math.random()*5)*power;spy.particles.push({x:confetti?Math.random()*innerWidth:x,y:confetti?-20-Math.random()*120:y,vx:Math.cos(a)*v*(confetti?.5:1),vy:confetti?Math.random()*2:Math.sin(a)*v-2,life:confetti?160+Math.random()*80:50+Math.random()*30,age:0,size:confetti?6+Math.random()*6:3+Math.random()*4,color:colors[i%colors.length],rot:Math.random()*6,spin:(Math.random()-.5)*.3,shape:confetti||Math.random()<.4?"rect":"star"})}if(!spy.raf)spy.raf=requestAnimationFrame(spyTick)}
function spyTick(){const c=$("#spyFx"),ctx=c.getContext("2d");ctx.clearRect(0,0,innerWidth,innerHeight);spy.particles=spy.particles.filter(p=>p.age<p.life);spy.particles.forEach(p=>{p.age++;p.vy+=.12;p.vx*=.985;p.x+=p.vx;p.y+=p.vy;p.rot+=p.spin;ctx.save();ctx.globalAlpha=Math.max(0,1-p.age/p.life);ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.fillStyle=p.color;if(p.shape==="rect")ctx.fillRect(-p.size/2,-p.size/4,p.size,p.size/2);else{ctx.beginPath();for(let k=0;k<10;k++){const r=k%2?p.size*.45:p.size;ctx.lineTo(Math.cos(k*Math.PI/5)*r,Math.sin(k*Math.PI/5)*r)}ctx.closePath();ctx.fill()}ctx.restore()});spy.raf=spy.particles.length?requestAnimationFrame(spyTick):0}
function spyCenter(el){const r=el.getBoundingClientRect();return[r.left+r.width/2,r.top+r.height/2]}
function spyMsg(text,type){const el=$("#spyCaseMsg");el.textContent=text;el.classList.remove("ok","bad");if(type){void el.offsetWidth;el.classList.add(type)}}
function spyStamp(text,type){const s=$("#spyStamp");s.textContent=text;s.className="spy-stamp "+type;void s.offsetWidth;s.classList.add("show")}
function spyShake(el){el.classList.remove("shake");void el.offsetWidth;el.classList.add("shake")}
function renderSpyBoard(){const board=$("#spyBoard");board.innerHTML="";data.spy.forEach((item,i)=>{const b=document.createElement("button"),st=spy.status[i];b.type="button";b.className="spy-tile"+(st?" solved "+st:"");b.dataset.index=i;b.style.setProperty("--i",i);b.setAttribute("aria-label",(i+1)+"번 문장"+(st?" · 해결함":""));const back=spyIsFalse(item)?'<em class="fix">✎</em><small>'+escapeHTML(item[2])+'</small>':'<em class="ok">O</em><small>일치</small>';b.innerHTML='<span class="spy-tile-inner"><span class="spy-face front"><i>'+(i+1)+'</i><span class="spy-shine"></span></span><span class="spy-face back">'+back+(st==="perfect"?'<b class="spy-star" aria-hidden="true">★</b>':'')+'</span></span>';b.onclick=()=>openSpyCase(i);board.append(b)});renderSpyLines(false);updateSpyHud()}
function renderSpyLines(animateIndex){const svg=$("#spyLines"),pos=[50,150,250];svg.classList.toggle("all-done",spy.status.every(Boolean)&&!animateIndex&&animateIndex!==0);svg.innerHTML=spy.lines.map((li,k)=>{const l=SPY_LINES[li],a=l[0],z=l[2],x1=pos[a%3],y1=pos[Math.floor(a/3)],x2=pos[z%3],y2=pos[Math.floor(z/3)],ex=(x2-x1)*.14,ey=(y2-y1)*.14;return'<line class="'+(k===animateIndex?"draw":"")+'" x1="'+(x1-ex)+'" y1="'+(y1-ey)+'" x2="'+(x2+ex)+'" y2="'+(y2+ey)+'" pathLength="1" vector-effect="non-scaling-stroke"/>'}).join("")}
function updateSpyHud(){const solved=spy.status.filter(Boolean).length;$("#spySolved").textContent=solved;$("#spyBingo").textContent=spy.lines.length;$("#spyMeter").style.width=(solved/data.spy.length*100)+"%"}
function bump(el){el.classList.remove("bump");void el.offsetWidth;el.classList.add("bump")}
function renderSpySentence(done){const item=data.spy[spy.current],tokens=item[0].split(/\s+/),target=spyIsFalse(item)?spyTarget(tokens,item):-1,box=$("#spySentence");box.innerHTML="";box.className="spy-sentence";tokens.forEach((t,k)=>{const w=document.createElement("button");w.type="button";w.className="spy-word";w.style.setProperty("--k",k);w.disabled=true;w.textContent=done&&k===target?t.replace(item[1],item[2]):t;if(done&&k===target)w.classList.add("fixed-static");w.onclick=()=>pickSpyWord(k,target,w);box.append(w);if(k<tokens.length-1)box.append(document.createTextNode(" "))})}
function openSpyCase(i){const tile=$('.spy-tile[data-index="'+i+'"]'),item=data.spy[i],done=Boolean(spy.status[i]);spy.current=i;spy.judgeMiss=0;spy.locateMiss=0;spy.phase=done?"review":"judge";$("#spyCaseNo").textContent=i+1;$("#spyCaseKicker").textContent=done?"해결한 문장":"수사 문장 "+(i+1);$("#spyCaseTitle").textContent=done?(spyIsFalse(item)?"바르게 고친 문장이에요":"본문과 같은 문장이에요"):"본문과 같은 문장일까요?";renderSpySentence(done);$("#spyStamp").className="spy-stamp";$("#spyJudge").classList.toggle("hidden",done);$$("#spyJudge button").forEach(b=>{b.disabled=false;b.classList.remove("wrong","right")});$("#spyNext").classList.toggle("hidden",!done);$("#spyNext").textContent="보드로 돌아가기";$("#spyPeekPanel").classList.add("hidden");$("#spyPeek").textContent="본문 살짝 보기";spyMsg(done?(spyIsFalse(item)?"‘"+item[1]+"’을(를) ‘"+item[2]+"’(으)로 바로잡았어요.":"O로 정확하게 판정했어요."):"문장을 끝까지 읽고 판정해요.",done?"ok":"");const modal=$("#spyModal"),card=$("#spyCase");modal.classList.remove("hidden","closing");modal.setAttribute("aria-hidden","false");tile.classList.add("opening");spySound("open");if(!reduceMotion&&card.animate){const t=tile.getBoundingClientRect(),c=card.getBoundingClientRect();card.animate([{transform:"translate("+(t.left+t.width/2-c.left-c.width/2)+"px,"+(t.top+t.height/2-c.top-c.height/2)+"px) scale("+(t.width/c.width)+","+(t.height/c.height)+") rotateY(90deg)",opacity:.3,borderRadius:"30px"},{transform:"none",opacity:1,borderRadius:"26px"}],{duration:520,easing:"cubic-bezier(.2,.9,.25,1.12)"});$$(".spy-word",card).forEach(w=>w.classList.add("enter"))}setTimeout(()=>tile.classList.remove("opening"),520);if(!done)$("#spyJudge [data-spy-judge]").focus({preventScroll:true});log("spy_open","spy-"+i,{review:done})}
function closeSpyCase(instant){const modal=$("#spyModal");if(modal.classList.contains("hidden"))return;const i=spy.current,tile=$('.spy-tile[data-index="'+i+'"]'),card=$("#spyCase"),finish=()=>{if(modal.classList.contains("hidden"))return;modal.classList.add("hidden");modal.classList.remove("closing");modal.setAttribute("aria-hidden","true");if(spy.phase==="solved"){spy.phase="";celebrateSpyTile(i)}};if(instant||reduceMotion||!card.animate||!tile){finish();return}const t=tile.getBoundingClientRect(),c=card.getBoundingClientRect();modal.classList.add("closing");setTimeout(finish,480);card.animate([{transform:"none",opacity:1},{transform:"translate("+(t.left+t.width/2-c.left-c.width/2)+"px,"+(t.top+t.height/2-c.top-c.height/2)+"px) scale("+(t.width/c.width)+","+(t.height/c.height)+")",opacity:0}],{duration:380,easing:"cubic-bezier(.5,0,.75,0)"}).onfinish=finish}
function judgeSpy(choice,button){if(spy.phase!=="judge")return;const item=data.spy[spy.current],isFalse=spyIsFalse(item),correct=(choice==="x")===isFalse;spy.attempts[spy.current]=(spy.attempts[spy.current]||0)+(correct?0:1);log("answer","spy-"+spy.current,{step:"judge",response:choice,correct,attempt:spy.judgeMiss+1});if(!correct){spy.judgeMiss++;button.classList.remove("wrong");void button.offsetWidth;button.classList.add("wrong");spyShake($("#spyCase"));spySound("bad");spyMsg(choice==="o"?"본문과 다른 낱말이 숨어 있어요. 낱말을 하나씩 본문과 비교해 봐요.":"잘 살펴봤나요? 이 문장의 낱말이 본문과 모두 같은지 다시 비교해 봐요.","bad");if(spy.judgeMiss>=2)openSpyPeek(true);return}button.classList.add("right");$$("#spyJudge button").forEach(b=>b.disabled=true);spySound("ok");const [x,y]=spyCenter(button);spyBurst(x,y,22,["#16a37f","#42c5d8","#ffd45c","#ffffff"]);if(!isFalse){spyStamp("O 일치","ok");spyMsg("정확해요! 본문과 같은 문장이에요.","ok");spyResolve();return}spyStamp("X 발견","bad");spy.phase="locate";setTimeout(()=>{if(spy.phase!=="locate")return;$("#spyJudge").classList.add("hidden");$("#spyCaseKicker").textContent="틀린 곳 찾기";$("#spyCaseTitle").textContent="본문과 다른 낱말을 눌러요";const box=$("#spySentence");box.classList.add("scan");$$(".spy-word",box).forEach(w=>w.disabled=false);spyMsg("스파이가 바꿔 놓은 낱말은 어디일까요?","")},650)}
function pickSpyWord(k,target,w){if(spy.phase!=="locate")return;const item=data.spy[spy.current],correct=k===target;log("answer","spy-"+spy.current,{step:"locate",response:w.textContent,correct,attempt:spy.locateMiss+1});if(!correct){spy.locateMiss++;spy.attempts[spy.current]=(spy.attempts[spy.current]||0)+1;w.classList.remove("miss");void w.offsetWidth;w.classList.add("miss");setTimeout(()=>w.classList.remove("miss"),600);spySound("bad");spyMsg(spy.locateMiss>=2?"반짝이는 낱말을 본문과 비교해 봐요.":"그 낱말은 본문과 같아요. 다른 낱말을 살펴봐요.","bad");if(spy.locateMiss>=2)$$(".spy-word",$("#spySentence"))[target].classList.add("hint");return}spy.phase="fixing";spySound("pick");const box=$("#spySentence");box.classList.remove("scan");$$(".spy-word",box).forEach(x=>{x.disabled=true;if(x!==w)x.classList.add("dim")});w.classList.remove("hint");w.classList.add("caught");const before=w.textContent,after=before.replace(item[1],item[2]);setTimeout(()=>{w.innerHTML='<span class="spy-old">'+escapeHTML(before)+'</span><span class="spy-new">'+escapeHTML(after)+'</span>';w.classList.add("fixing");spySound("fix");setTimeout(()=>{const [x,y]=spyCenter(w);spyBurst(x,y,34,["#16a37f","#ffd45c","#7a4fe0","#42c5d8"],1.1)},260);$$(".spy-word.dim",box).forEach(x=>x.classList.remove("dim"));spyStamp("수정 완료","fix");spyMsg("‘"+item[1]+"’ → ‘"+item[2]+"’ 바로잡았어요!","ok");$("#spyCaseTitle").textContent="본문에 맞게 고쳤어요";spyResolve()},700)}
function spyResolve(){const i=spy.current;spy.status[i]=(spy.attempts[i]||0)===0?"perfect":"solved";spy.phase="solved";$("#spyPeekPanel").classList.add("hidden");const last=spy.status.filter(Boolean).length===data.spy.length;$("#spyNext").textContent=last?"임무 결과 보기":"보드로 돌아가기";$("#spyNext").classList.remove("hidden");$("#spyNext").focus({preventScroll:true})}
function celebrateSpyTile(i){const tile=$('.spy-tile[data-index="'+i+'"]'),st=spy.status[i];renderSpyBoard();const fresh=$('.spy-tile[data-index="'+i+'"]');fresh.classList.add("just-solved");const [x,y]=spyCenter(fresh);spyBurst(x,y,st==="perfect"?40:26,st==="perfect"?["#ffd45c","#ffb020","#fff4c2","#7a4fe0"]:["#42c5d8","#16a37f","#ffffff"]);bump($("#spySolved"));const newLines=SPY_LINES.map((l,k)=>k).filter(k=>!spy.lines.includes(k)&&SPY_LINES[k].every(n=>spy.status[n]));let delay=450;newLines.forEach(k=>{setTimeout(()=>{spy.lines.push(k);renderSpyLines(spy.lines.length-1);updateSpyHud();bump($("#spyBingo"));spySound("bingo");SPY_LINES[k].forEach((n,j)=>{setTimeout(()=>{const t=$('.spy-tile[data-index="'+n+'"]');if(!t)return;t.classList.remove("line-glow");void t.offsetWidth;t.classList.add("line-glow");const [bx,by]=spyCenter(t);spyBurst(bx,by,14,["#ffd45c","#7a4fe0","#42c5d8"],.8)},j*110)});showSpyBanner("빙고!")},delay);delay+=700});const solved=spy.status.filter(Boolean).length;feedback($("#spyFeedback"),solved===data.spy.length?"모든 문장을 수사했어요!":st==="perfect"?"한 번에 해결! 다음 숫자를 골라요.":"해결했어요. 다음 숫자를 골라요.","ok");if(solved===data.spy.length)setTimeout(spyFinale,delay+300)}
function showSpyBanner(text){const b=document.createElement("div");b.className="spy-banner";b.textContent=text;$("#spyGame .spy-board-wrap").append(b);setTimeout(()=>b.remove(),1300)}
function spyFinale(){$("#spyLines").classList.add("all-done");const perfect=spy.status.filter(s=>s==="perfect").length;$("#spyFinaleText").textContent="9문장 중 "+perfect+"문장을 한 번에 해결하고, 빙고 "+spy.lines.length+"줄을 완성했어요.";$("#spyFinale").classList.remove("hidden");spySound("bingo");spyBurst(0,0,160,["#7a4fe0","#42c5d8","#ffd45c","#16a37f","#ff7a8a"],1,true);log("spy_complete","word-spy",{perfect,lines:spy.lines.length})}
function openSpyPeek(auto){const panel=$("#spyPeekPanel");if(!auto&&!panel.classList.contains("hidden")){panel.classList.add("hidden");$("#spyPeek").textContent="본문 살짝 보기";return}panel.innerHTML=data.paragraphs.map(p=>"<p>"+escapeHTML(p)+"</p>").join("");panel.classList.remove("hidden");$("#spyPeek").textContent="본문 닫기";log("spy_peek","spy-"+spy.current,{auto:Boolean(auto)})}
function spyEnter(){const board=$("#spyBoard");board.classList.remove("intro");void board.offsetWidth;board.classList.add("intro")}
function setupSpy(){["#spyModal","#spyFinale","#spyFx"].forEach(s=>document.body.append($(s)));spy.status=data.spy.map(()=>null);spy.attempts=data.spy.map(()=>0);try{spy.sound=localStorage.getItem("oncuvate-energy-spy-sound")!=="off"}catch(e){}const snd=$("#spySound"),syncSound=()=>{snd.textContent=spy.sound?"🔊":"🔇";snd.setAttribute("aria-pressed",String(spy.sound));snd.setAttribute("aria-label",spy.sound?"효과음 끄기":"효과음 켜기")};syncSound();snd.onclick=()=>{spy.sound=!spy.sound;try{localStorage.setItem("oncuvate-energy-spy-sound",spy.sound?"on":"off")}catch(e){}syncSound()};$$("[data-spy-judge]").forEach(b=>b.onclick=()=>judgeSpy(b.dataset.spyJudge,b));$("#spyNext").onclick=()=>closeSpyCase();$("#spyClose").onclick=()=>{if(spy.phase==="fixing")return;closeSpyCase()};$("#spyModal").onclick=e=>{if(e.target===$("#spyModal")&&spy.phase!=="fixing")closeSpyCase()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("#spyModal").classList.contains("hidden")&&spy.phase!=="fixing")closeSpyCase()});$("#spyPeek").onclick=()=>openSpyPeek(false);$("#spyFinale").onclick=()=>$("#spyFinale").classList.add("hidden");spyFxSize();window.addEventListener("resize",spyFxSize)}
function renderSpy(){renderSpyBoard()}
function spyOnPage(p){if(p===2)spyEnter();else{closeSpyCase(true);$("#spyFinale").classList.add("hidden")}}
function clearDropTargets(){$('.energy-bin').forEach(bin=>bin.classList.remove("drop-target"))}
function setupBinDrop(bin,type){bin.ondragover=e=>{e.preventDefault();clearDropTargets();bin.classList.add("drop-target")};bin.ondragleave=e=>{if(!bin.contains(e.relatedTarget))bin.classList.remove("drop-target")};bin.ondrop=e=>{e.preventDefault();clearDropTargets();classify(type)};bin.onclick=e=>{if(e.detail===0)classify(type)}}
function renderBins(){const box=$("#energyBins");box.innerHTML="";Object.entries(data.stages).forEach(([type,stage])=>{const b=document.createElement("button");b.type="button";b.className="energy-bin";b.dataset.type=type;b.setAttribute("aria-label",stage[0]+"에 현재 카드 놓기");b.innerHTML='<span class="sprite"></span><b>'+escapeHTML(stage[0])+'</b><small>'+state.counts[type]+' / '+stage[1]+'</small>';setupBinDrop(b,type);box.append(b)});renderClassifyCard()}
function enableClassifyDrag(){const card=$("#classifyCard"),item=state.classification[classifyIndex];card.draggable=Boolean(item);card.style.pointerEvents=item?"":"none";card.setAttribute("aria-grabbed","false");card.ondragstart=e=>{if(!item){e.preventDefault();return}e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",item.id);card.classList.add("dragging");card.setAttribute("aria-grabbed","true")};card.ondragend=()=>{card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets()};let touchDragging=false;card.onpointerdown=e=>{if(!item||e.pointerType==="mouse")return;touchDragging=true;card.setPointerCapture(e.pointerId);card.classList.add("dragging");card.setAttribute("aria-grabbed","true");e.preventDefault()};card.onpointermove=e=>{if(!touchDragging)return;e.preventDefault();clearDropTargets();const bin=document.elementFromPoint(e.clientX,e.clientY)?.closest(".energy-bin");if(bin)bin.classList.add("drop-target")};const endTouch=e=>{if(!touchDragging)return;touchDragging=false;const bin=document.elementFromPoint(e.clientX,e.clientY)?.closest(".energy-bin");card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets();if(bin)classify(bin.dataset.type)};card.onpointerup=endTouch;card.onpointercancel=()=>{touchDragging=false;card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets()}}
function renderClassifyCard(){const item=state.classification[classifyIndex];$("#classifyCounter").textContent=Math.min(classifyIndex+1,state.classification.length)+" / "+state.classification.length;const card=$("#classifyCard");if(!item){card.textContent="모든 특징 카드를 알맞게 분류했어요!";card.classList.add("complete-card");feedback($("#classifyFeedback"),"네 가지 발전 방식의 차이를 확인했습니다.","ok");enableClassifyDrag();return}card.classList.remove("complete-card");card.innerHTML=(item.cue?'<small>'+escapeHTML(item.cue)+'</small>':"")+escapeHTML(item.text);enableClassifyDrag()}
function classify(type){const item=state.classification[classifyIndex];if(!item)return false;const correct=type===item.type;log("answer","classify-"+item.id,{response:type,correct});if(!correct){feedback($("#classifyFeedback"),"카드의 핵심 낱말을 다시 보고 다른 칸으로 옮겨 보세요.","bad");return false}const card=$("#classifyCard");card.draggable=false;card.style.pointerEvents="none";state.counts[type]++;const bin=$('.energy-bin[data-type="'+type+'"]');$('small',bin).textContent=state.counts[type]+" / "+data.stages[type][1];if(state.counts[type]===data.stages[type][1])bin.classList.add("complete");feedback($("#classifyFeedback"),"맞아요. "+data.stages[type][0]+"의 특징입니다.","ok");classifyIndex++;setTimeout(renderClassifyCard,450);return true}function getVerifyCoachPrompts(){if(verifyIndex===0){const target="재생 에너지의 특징과 사용 방법",otherTarget="화석 연료가 만들어지는 과정",weatherOption=level==="deep"?"햇빛과 바람에 따라 발전량이 달라질 수 있습니다.":"날씨에 따라 발전량이 달라질 수 있습니다.";return[{tag:"본문 확인",q:"본문의 내용은 어떤 것이었나요?",options:[target,otherTarget],correct:0},{tag:"묻는 내용",q:"어떤 설명을 고르라고 했나요?",options:["본문의 내용과 맞는 설명","본문에 없는 낱말"],correct:0},{tag:"답의 범위",q:"답은 몇 개 골라야 하나요?",options:["해당하는 것을 모두","가장 알맞은 것 하나"],correct:0},{tag:"본문과 비교",q:"본문의 내용과 다른 설명은 무엇인가요?",options:[weatherOption,"날씨와 상관없이 언제나 같은 양의 전기를 만듭니다."],correct:1}]}if(verifyIndex===1)return[{tag:"대상",q:"어떤 발전 방법에 관한 문제인가요?",options:["풍력 발전","태양광 발전"],correct:1},{tag:"묻는 내용",q:"어떤 설명을 고르라고 했나요?",options:["맞는 설명","맞지 않는 설명"],correct:0},{tag:"답의 범위",q:"답은 몇 개 골라야 하나요?",options:["해당하는 것을 모두","가장 알맞은 것 하나"],correct:0},{tag:"주의 낱말",q:"태양광 발전과 관계없는 낱말은 무엇인가요?",options:["햇빛","바람"],correct:1}];return[{tag:"대상",q:"무엇에 관한 문제인가요?",options:["에너지를 만드는 시설","에너지를 아껴 쓰는 행동"],correct:1},{tag:"묻는 내용",q:"어떤 행동을 고르라고 했나요?",options:["실천할 행동","피해야 할 행동"],correct:0},{tag:"답의 범위",q:"답은 몇 개 골라야 하나요?",options:["가장 알맞은 것 하나","해당하는 것을 모두"],correct:1},{tag:"주의 낱말",q:"본문에 나온 표현은 무엇인가요?",options:["필요한 물건만 사고 오래 쓴다","갖고 싶은 물건을 모두 산다"],correct:0}]}
function renderVerifyCoach(){const prompts=getVerifyCoachPrompts();if(verifyCoachStep>=prompts.length){$("#verifyStep").textContent="준비";$("#verifyPrompt").textContent="확인했어요. 왼쪽에서 답을 모두 고른 뒤 확인해요.";$("#verifyCoachChoices").innerHTML="";$$('#verifyOptions input').forEach(x=>x.disabled=false);$("#verifyCheck").disabled=false;feedback($("#verifyFeedback"),"문제에서 묻는 내용과 답의 범위를 확인하고, 보기를 본문과 비교했어요. 답을 골라 보세요.","ok");return}const p=prompts[verifyCoachStep];$("#verifyStep").textContent=(verifyCoachStep+1)+" / "+prompts.length;$("#verifyPrompt").innerHTML="<small>"+p.tag+"</small><strong>"+p.q+"</strong>";$("#verifyCoachChoices").innerHTML="";p.options.forEach((o,i)=>{const b=document.createElement("button");b.type="button";b.textContent=o;b.onclick=()=>{const correct=i===p.correct;log("answer","verify-"+verifyIndex+"-precheck-"+verifyCoachStep,{response:i,correct});if(!correct){showToast("문제와 보기를 다시 꼼꼼하게 읽어 보세요.");return}verifyCoachStep++;renderVerifyCoach()};$("#verifyCoachChoices").append(b)})}
function renderVerifyQuestion(){const v=data.verify[verifyIndex];verifyCoachStep=0;$("#verifyQuestionCount").textContent="문제 "+(verifyIndex+1)+" / "+data.verify.length;$("#verifyQuestion").textContent=v[0];$("#verifyOptions").innerHTML="";v[1].forEach((o,i)=>{const label=document.createElement("label");label.innerHTML='<input type="checkbox" value="'+i+'" disabled><span>'+escapeHTML(o)+'</span>';$("#verifyOptions").append(label)});$("#verifyCheck").classList.remove("hidden");$("#verifyCheck").disabled=true;$("#verifyNext").classList.add("hidden");feedback($("#verifyFeedback"),"먼저 오른쪽에서 질문을 확인해요.");renderVerifyCoach()}
function checkVerify(){const v=data.verify[verifyIndex],picked=$$('#verifyOptions input:checked').map(x=>Number(x.value)).sort(),answer=v[2].slice().sort(),correct=JSON.stringify(picked)===JSON.stringify(answer);log("answer","verify-main-"+verifyIndex,{response:picked,correct});if(!correct){feedback($("#verifyFeedback"),"아직 정답이 아니에요. 고른 보기와 빠뜨린 보기를 다시 살펴보세요.","bad");return}$$('#verifyOptions input').forEach(x=>x.disabled=true);$("#verifyCheck").classList.add("hidden");const done=(verifyIndex+1)+" / "+data.verify.length+" 완료";feedback($("#verifyFeedback"),"정답이에요! "+done+". "+v[3],"ok");if(verifyIndex<data.verify.length-1){$("#verifyNext").textContent="다음 문제";$("#verifyNext").classList.remove("hidden");$("#verifyStep").textContent="정답";$("#verifyPrompt").textContent="맞혔어요. 다음 문제에서도 묻는 말과 보기의 표현을 확인해요.";$("#verifyCoachChoices").innerHTML=""}else{$("#verifyStep").textContent="완료";$("#verifyPrompt").textContent="정답이에요. 세 문제를 모두 정확하게 풀었어요!";$("#verifyCoachChoices").innerHTML="";showToast("3문제를 모두 마쳤어요!")}}
function setupVerify(){$("#verifyCheck").onclick=checkVerify;$("#verifyNext").onclick=()=>{verifyIndex++;renderVerifyQuestion()};renderVerifyQuestion()}function renderTransfer(){const t=data.transfer[transferIndex];$("#transferLabel").textContent=t[0];$("#transferCounter").textContent=(transferIndex+1)+" / "+data.transfer.length;$("#transferPassage").textContent=t[1];$("#transferQuestion").textContent=t[2];$("#transferOptions").innerHTML="";t[3].forEach((o,i)=>{const b=document.createElement("button");b.type="button";b.textContent=String.fromCharCode(65+i)+"  "+o;b.onclick=()=>answerTransfer(i,b);$("#transferOptions").append(b)});feedback($("#transferFeedback"),"답을 고르면 근거를 확인할 수 있어요.");$("#transferNext").classList.add("hidden")}
function answerTransfer(choice,button){const t=data.transfer[transferIndex],correct=choice===t[4];$$('#transferOptions button').forEach(b=>b.classList.remove("correct","wrong"));button.classList.add(correct?"correct":"wrong");log("answer","transfer-"+transferIndex,{response:choice,correct});if(!correct){feedback($("#transferFeedback"),"새 글의 표현을 다시 확인하고 다른 답을 골라 보세요.","bad");return}feedback($("#transferFeedback"),t[5],"ok");$("#transferNext").classList.remove("hidden")}
function setupTransfer(){$("#transferNext").onclick=()=>{if(transferIndex<data.transfer.length-1){transferIndex++;renderTransfer()}else{feedback($("#transferFeedback"),"세 가지 전이 활동을 모두 마쳤어요.","ok");$("#transferNext").classList.add("hidden")}}}
function setupReflection(){$$('#reflectionChoices button').forEach(b=>b.onclick=()=>{$$('#reflectionChoices button').forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.reflection=b.textContent;state.reflectionStrategy=b.dataset.strategy;$("#reflectionStrategyText").textContent=state.reflectionStrategy;$("#reflectionStrategy").classList.remove("hidden");$("#finishLesson").classList.remove("hidden")});$("#finishLesson").onclick=finish}
function finish(){if(!state.reflection&&page===6){showToast("오늘 실수한 것과 가장 가까운 보기를 골라 주세요.");return}const record={level,mistake:state.reflection,strategy:state.reflectionStrategy,finishedAt:new Date().toISOString()};localStorage.setItem("oncuvate-energy-complete-"+level,JSON.stringify(record));$("#completionCard").classList.remove("hidden");$("#finishLesson").classList.add("hidden");$("#completionSignal").hidden=false;log("lesson_complete","lesson",record);showToast("수업을 마쳤어요!")}
function boot(){setupLevel();setupIntro();setupNavigation();setupAnnotationDock();renderPassage();setupVocab();setupPrediction();setupReadingFlow();setupQuestions();setupSpy();setupVerify();setupTransfer();setupReflection();renderPrediction();renderQuestion();renderSpy();renderBins();renderTransfer();showPage(0)}
document.addEventListener("DOMContentLoaded",boot);
})();
