(()=>{
  const lesson=window.WATER_PLAY_LESSON;
  if(!lesson)return;
  const pilotConfig=window.WATER_PLAY_PILOT_CONFIG||{};
  const role=window.ONCUVATE?.role||"child";
  const child=String(window.ONCUVATE?.child||"").trim();
  const liveRoom=String(window.ONCUVATE?.room||"").trim();
  const nicknameKey=pilotConfig.nicknameStorageKey||"water-play-pilot-nickname";
  const storedNickname=String(localStorage.getItem(nicknameKey)||"").trim();
  const nickname=role==="coach"?"코치":storedNickname;
  const allowedNicknames=Array.isArray(pilotConfig.nicknames)?pilotConfig.nicknames:[];
  if(role!=="coach"&&(!nickname||!allowedNicknames.includes(nickname))){
    const current=location.pathname.split("/").pop()||"course.html";
    location.replace("index.html?next="+encodeURIComponent(current));
    return;
  }
  const liveChild=String(child||(role==="coach"?"coach":"self")).replace(/[.#$\[\]\/]/g,"-");
  const LEGACY_STORE=`oncuvate-water-play-${lesson.id}-${lesson.id==="life"?"v5":"v4"}`;
  const STORE=`${LEGACY_STORE}-${nickname}`;
  const base={page:0,maxPage:0,answers:{},texts:{},substeps:{},readParts:{},completed:{},help:{},strategyOpen:{},exampleOpen:{},brainstormOwn:{},personalWords:{},final:"",beforeRevision:"",submittedAt:""};
  let state=load();
  state.brainstormOwn=state.brainstormOwn||{};
  state.personalWords=state.personalWords||{};
  state.exampleOpen=state.exampleOpen||{};
  let saveTimer,brainstormTimer,progTimer,brainstormBound=false,sharedBrainstorm=[],coachOpen=true;
  const coach={pageLocked:false,activityLocked:false,members:{},selected:""};

  /* 커스텀 계측 봉투 — 어휘 v0.2. schemaVersion 필수, t는 콘텐츠 상대시각(기준점은 트래커).
     주입되면 호출, 없으면 무시. 자체 전송은 하지 않는다(규격 5-1).
     🔴 작성 원문은 보내지 않는다 — 글자 수·낱말 수·편집량 같은 수치만 보낸다.
        원문을 담을 통로는 요청 중이다(의견교환함 36번). */
  const OC_T0=(window.performance&&performance.now)?performance.now():0;
  function ocNow(){return Math.round(((window.performance&&performance.now)?performance.now():0)-OC_T0)}
  function ocLog(type,data){try{const L=window.OncuLog;if(!L)return;const ev={schemaVersion:"0.2",t:ocNow(),content:document.documentElement.getAttribute("data-lesson-id")||"",type:type,data:data||{}};if(typeof L==="function")L(type,ev);else if(typeof L[type]==="function")L[type](ev);else if(typeof L.log==="function")L.log(type,ev)}catch(e){}}
  const metrics={page:-1,enteredAt:0,firstInput:{},edits:{},inserted:{},draft:""};
  function activityId(i){return `${lesson.id}-p${i+1}`}
  function textKeys(p){if(p.type==="write")return [p.key];if(p.type==="sequence")return p.stages.map(s=>s.key);if(p.type==="reasons")return ["reason1","detail1","reason2","detail2"];return []}
  function keptWords(key,text){const list=metrics.inserted[key]||[];const body=String(text||"");return list.filter(w=>body.includes(w)).length}
  function noteInput(key){if(metrics.firstInput[key]===undefined)metrics.firstInput[key]=Math.max(0,ocNow()-metrics.enteredAt);metrics.edits[key]=(metrics.edits[key]||0)+1}
  function noteInsert(key,word){(metrics.inserted[key]=metrics.inserted[key]||[]).push(word)}
  function pageStats(i){const p=lesson.pages[i];const out={activityId:activityId(i),type:p.type,durationMs:Math.max(0,ocNow()-metrics.enteredAt)};
    if(p.type==="choice"){out.chosen=String(p.multi?selected(p.key).join("·"):state.answers[p.key]||"").slice(0,30)}
    else if(p.type==="brainstorm"){out.ownWords=ownBrainstorm().length;out.pickedWords=personalBrainstorm().length}
    else if(p.type==="review"){const final=String(state.final||"");out.draftChars=metrics.draft.length;out.finalChars=final.length;out.changedChars=Math.abs(final.length-metrics.draft.length);out.rebuilt=Boolean(metrics.rebuilt)}
    else{const keys=textKeys(p);if(keys.length){out.steps=keys.map(k=>{const text=String(state.texts[k]||"");return {key:k,chars:text.length,edits:metrics.edits[k]||0,firstInputMs:metrics.firstInput[k]??null,insertedWords:(metrics.inserted[k]||[]).length,keptWords:keptWords(k,text)}})}}
    return out}
  function enterPage(i){if(metrics.page===i)return;if(metrics.page>=0)ocLog("activity_end",pageStats(metrics.page));metrics.page=i;metrics.enteredAt=ocNow();const p=lesson.pages[i];if(p.type==="review")metrics.draft=String(state.final||compose());ocLog("activity_start",{activityId:activityId(i),type:p.type,index:i+1,total:lesson.pages.length});if(p.type==="finish")ocLog("lesson_end",{pages:lesson.pages.length,completed:Object.keys(state.completed).length})}

  function load(){try{let raw=localStorage.getItem(STORE);if(!raw){raw=localStorage.getItem(LEGACY_STORE);if(raw)localStorage.setItem(STORE,raw)}return Object.assign({},base,JSON.parse(raw||"{}"))}catch{return structuredClone(base)}}
  function save(show=true){localStorage.setItem(STORE,JSON.stringify(state));publishProgress();if(show){const el=document.getElementById("saved");if(el){el.textContent="저장 중…";clearTimeout(saveTimer);saveTimer=setTimeout(()=>el.textContent="기기에 저장됨",350)}}renderJourney()}
  function esc(value){return String(value??"").replace(/[&<>'"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[m]))}
  function resolve(value){return typeof value==="function"?value(state):value}
  function selected(key){const value=state.answers[key];return Array.isArray(value)?value:[]}
  function pageDone(index){const p=lesson.pages[index];if(role==="coach")return true;if(state.completed[index])return true;if(p.type==="choice")return p.multi?selected(p.key).length>0:Boolean(state.answers[p.key]);if(p.type==="brainstorm")return personalBrainstorm().length>=3;if(p.type==="read")return Boolean(state.answers[`read-${index}`]);if(p.type==="sequence")return p.stages.every(s=>String(state.texts[s.key]||"").trim().length>=2);if(p.type==="write")return String(state.texts[p.key]||"").trim().length>=5;if(p.type==="reasons")return ["reason1","detail1","reason2","detail2"].every(k=>String(state.texts[k]||"").trim().length>=3);if(p.type==="review")return String(state.final||compose()).trim().length>=10;return true}
  function renderJourney(){const nav=document.getElementById("journey");if(!nav)return;nav.innerHTML=lesson.pages.map((p,i)=>`<button class="${i===state.page?"on":""} ${pageDone(i)?"done":""}" onclick="WaterLesson.go(${i})"><span class="step-dot">${pageDone(i)?"✓":i+1}</span><span><b>${esc(p.short)}</b><small>${esc(p.typeLabel||"")}</small></span></button>`).join("")}
  function header(p,i){return `<div class="lesson-head"><span class="mission"><b>${i+1}</b>${esc(lesson.genre)} · ${esc(resolve(p.kicker)||resolve(p.typeLabel)||"")}</span><h2>${esc(resolve(p.title))}</h2><p>${esc(resolve(p.instruction))}</p></div>`}
  function strategyTip(p,i){if(!p.strategy)return "";const s=p.strategy,open=Boolean(state.strategyOpen[i]);return `<section class="strategy-tip ${open?"open":""}"><div class="strategy-top"><span class="strategy-badge">${esc(s.level||"지금 써 볼 방법")}</span><div class="strategy-copy"><small>지금 써 볼 방법</small><strong>${esc(s.name)}</strong><p>${esc(s.cue)}</p></div><button class="strategy-toggle"${open?"":' data-track="hint" data-help-level="A1"'} aria-expanded="${open}" onclick="WaterLesson.toggleStrategy(${i})">${open?"접기":"언제·어떻게?"}</button></div>${open?`<div class="strategy-more"><p><b>이럴 때</b>${esc(s.when)}</p><p><b>이렇게</b>${esc(s.do)}</p><p><b>도움이 되는 까닭</b>${esc(s.why)}</p></div>`:""}</section>`}  function statusBar(i,p){return `<div class="status-actions"><span>${state.completed[i]?"이 단계는 다 했다고 표시했어요.":"활동을 마치면 표시해 주세요."}</span><button class="help-button"${state.help[i]?"":' data-track="hint" data-help-level="A2"'} onclick="WaterLesson.help(${i})">도와주세요</button><button class="done-button" data-track="activity-complete" data-activity-id="${esc(lesson.id)}-p${i+1}" onclick="WaterLesson.complete(${i})">${state.completed[i]?"완료됨 ✓":"다했어요"}</button></div>${state.help[i]?`<div class="help-box"><b>작은 도움</b><br>${esc(p.help||"한 문장만 먼저 적어도 괜찮아요. 가장 떠오르는 낱말부터 시작해 보세요.")}</div>`:""}`}
  function normalizeWord(value){return String(value||"").replace(/\s+/g," ").trim().slice(0,20)}
  function ownBrainstorm(){return Array.isArray(state.brainstormOwn[lesson.id])?state.brainstormOwn[lesson.id]:[]}
  function personalBrainstorm(){return Array.isArray(state.personalWords[lesson.id])?state.personalWords[lesson.id]:[]}
  function wordValues(value){if(Array.isArray(value))return value;return value&&typeof value==="object"?Object.values(value):[]}
  function aggregateBrainstorm(raw){const map=new Map();Object.values(raw||{}).forEach(person=>{wordValues(person?.words).forEach(item=>{const word=normalizeWord(item);if(!word)return;const key=word.toLocaleLowerCase("ko");const found=map.get(key);if(found)found.count+=1;else map.set(key,{word,count:1})})});if(!wordValues(raw?.[liveChild]?.words).length)ownBrainstorm().forEach(item=>{const word=normalizeWord(item),key=word.toLocaleLowerCase("ko");if(word&&!map.has(key))map.set(key,{word,count:1})});sharedBrainstorm=[...map.values()].sort((a,b)=>b.count-a.count||a.word.localeCompare(b.word,"ko"));updateBrainstormDOM()}
  function liveReady(){return Boolean(liveRoom&&window._firebaseReady===true&&typeof window.pth==="function"&&typeof window._set==="function"&&typeof window._onValue==="function")}
  function snap(value){return typeof value?.val==="function"?value.val():value}
  /* 공동 낱말 보드는 `board` 경로다 — 「모두가 같은 화면을 보기 위한 값」(의견교환함 32번 §3).
     `prog`는 코치만 읽을 수 있게 좁혀졌으므로 여기에 두면 아이 화면에 아무것도 오지 않는다. */
  function publishBrainstorm(){if(!liveReady())return;window._set(window.pth(`board/${lesson.id}/${liveChild}`),{words:ownBrainstorm(),updatedAt:Date.now()})?.catch?.(()=>{})}
  /* 진행 현황은 `prog` — 쓰기=수업대상, 읽기=코치만 (규격 6장). 아이 화면은 읽지 않는다. */
  function progressSnapshot(){const texts={};Object.keys(state.texts||{}).forEach(k=>{const v=String(state.texts[k]||"").trim();if(v)texts[k]=v});const page=lesson.pages[state.page]||{},choices=lesson.pages.filter(p=>p.type==="choice"&&p.key).map(p=>{const raw=state.answers[p.key],value=Array.isArray(raw)?raw.join(" · "):String(raw||"");return {label:String(p.short||p.title||p.key),value:value.slice(0,80)}}).filter(item=>item.value);
    return {name:nickname,lesson:lesson.id,genre:lesson.genre,session:String(lesson.session||""),page:state.page,pageLabel:String(page.short||""),pages:lesson.pages.length,done:Object.keys(state.completed||{}).length,help:Object.keys(state.help||{}).filter(k=>state.help[k]).length,words:personalBrainstorm().length,choices:choices,chars:Object.values(texts).reduce((n,v)=>n+v.length,0),texts:texts,final:String(state.final||"").trim(),updatedAt:Date.now()}}
  function publishProgress(){if(!liveReady()||role==="coach")return;clearTimeout(progTimer);progTimer=setTimeout(()=>{window._set(window.pth(`prog/${liveChild}`),progressSnapshot())?.catch?.(()=>{})},400)}
  function publishNav(){if(!liveReady()||role!=="coach")return;window._set(window.pth("nav"),{page:state.page,pageLocked:Boolean(coach.pageLocked),activityLocked:Boolean(coach.activityLocked),updatedAt:Date.now()})?.catch?.(()=>{})}
  function applyNav(value){const v=snap(value)||{},page=Number(v.page),pageLocked=Boolean(v.pageLocked??v.locked),activityLocked=Boolean(v.activityLocked);const changed=pageLocked!==coach.pageLocked||activityLocked!==coach.activityLocked||(pageLocked&&Number.isInteger(page)&&page!==state.page);coach.pageLocked=pageLocked;coach.activityLocked=activityLocked;if(pageLocked&&Number.isInteger(page)&&page>=0&&page<lesson.pages.length)state.page=page;if(changed)render()}
  function bindLive(){aggregateBrainstorm({});if(!liveRoom)return;let attempts=0;
    const connect=()=>{if(brainstormBound||!liveReady())return false;brainstormBound=true;
      window._onValue(window.pth(`board/${lesson.id}`),s=>aggregateBrainstorm(snap(s)||{}));
      if(role==="coach"){window._onValue(window.pth("prog"),s=>{coach.members=snap(s)||{};if(coachOpen)render()});publishNav()}
      else{window._onValue(window.pth("nav"),applyNav);publishProgress()}
      publishBrainstorm();return true};
    if(connect())return;clearInterval(brainstormTimer);
    brainstormTimer=setInterval(()=>{attempts+=1;if(connect()||attempts>80){clearInterval(brainstormTimer);updateBrainstormDOM()}},250)}
  function brainstormWordsMarkup(){const picked=personalBrainstorm().map(w=>w.toLocaleLowerCase("ko"));if(!sharedBrainstorm.length)return `<p class="brainstorm-empty">아직 모인 단어가 없어요. 첫 아이디어를 올려 보세요.</p>`;const maxCount=Math.max(...sharedBrainstorm.map(item=>item.count),1),tilts=[-3,2,-1,3,0,-2];return sharedBrainstorm.map((item,index)=>{const encoded=encodeURIComponent(item.word),on=picked.includes(item.word.toLocaleLowerCase("ko")),weight=maxCount===1?2:Math.max(1,Math.min(5,Math.ceil(item.count/maxCount*5)));return `<button class="brainstorm-chip cloud-${weight} ${on?"on":""}" style="--cloud-tilt:${tilts[index%tilts.length]}deg" type="button" aria-pressed="${on}" onclick="WaterLesson.pickShared('${encoded}')"><span>${esc(item.word)}</span>${item.count>1?`<small>${item.count}명</small>`:""}<i aria-hidden="true">${on?"✓":"+"}</i></button>`}).join("")}
  function personalWordsMarkup(){const words=personalBrainstorm();if(!words.length)return `<p class="brainstorm-empty">공동 보드의 단어를 누르거나 내 단어를 올리면 여기에 모여요.</p>`;return words.map(word=>`<button class="personal-chip" type="button" onclick="WaterLesson.pickShared('${encodeURIComponent(word)}')"><span>${esc(word)}</span><i>빼기</i></button>`).join("")}
  function brainstormStatus(){if(!liveRoom)return "혼자 모드 · 내가 적은 말로 단어풀을 만들어요.";return brainstormBound?"수업방과 실시간으로 공유 중 · 작성자 이름은 표시하지 않아요.":"수업방 연결을 준비하고 있어요."}
  function updateBrainstormDOM(){const board=document.getElementById("brainstormBoard"),mine=document.getElementById("personalBoard"),status=document.getElementById("brainstormLiveStatus");if(board)board.innerHTML=brainstormWordsMarkup();if(mine)mine.innerHTML=personalWordsMarkup();if(status)status.textContent=brainstormStatus()}
  function personalWordPool(key){const words=personalBrainstorm();if(!words.length)return "";return `<div class="personal-pool"><strong>함께 만든 단어에서 내가 고른 말</strong><div class="word-list">${words.map(word=>`<button class="word personal" type="button" data-track="hint" data-help-level="A2" onclick="WaterLesson.addPersonalWord('${key}','${encodeURIComponent(word)}')">${esc(word)}</button>`).join("")}</div></div>`}
  function imageCueMarkup(p){const cue=resolve(p.imageCues);if(!cue?.src)return "";const labels=Array.isArray(cue.galleryLabels)?cue.galleryLabels:Array.isArray(cue.labels)?cue.labels:[],positions=["top-left","top-right","bottom-left","bottom-right"];let items=[];if(Array.isArray(cue.gallery)&&cue.gallery.length)items=cue.gallery;else if(Array.isArray(cue.galleryFiles)&&cue.galleryFiles.length)items=cue.galleryFiles.map((src,index)=>({src,label:labels[index]||`살펴볼 장면 ${index+1}`,full:true}));else if(cue.relatedSrc){items=positions.map((position,index)=>({src:cue.relatedSrc,position,label:labels[index]||`살펴볼 장면 ${index+1}`}))}else if(labels.length>=4&&/-photo-cues\.webp$/i.test(cue.src))items=positions.map((position,index)=>({src:cue.src,position,label:labels[index]||`살펴볼 장면 ${index+1}`,selected:cue.focus===position}));else items=[{src:cue.src,label:labels[0]||"장면 자세히 보기",full:true}];return `<figure class="photo-cue-board photo-cue-gallery"><div class="photo-cue-grid">${items.map((item,index)=>`<div class="photo-cue-tile ${item.selected?"selected":""}"><div class="photo-cue-frame ${item.full?"full":`crop-${item.position||positions[index%4]}`}"><img src="${esc(item.src)}" alt="${esc(item.alt||cue.alt||"단어를 떠올리기 위한 물놀이 사진")}" loading="lazy" decoding="async"></div><span><b>${index+1}</b>${esc(item.label||labels[index]||"장면 살펴보기")}</span></div>`).join("")}</div></figure>`}
  function brainstormPage(p,i){const context=(p.contextKeys||[]).map(key=>state.answers[key]).filter(Boolean);return `${header(p,i)}<div class="lesson-body">${context.length?`<p class="selected-note">지금 떠올릴 내용 · ${context.map(esc).join(" · ")}</p>`:""}<div class="brainstorm-intro"><strong>문장으로 만들지 않아도 돼요</strong><p>${esc(p.prompt)}</p></div>${imageCueMarkup(p)}<form class="brainstorm-form" onsubmit="WaterLesson.addBrainstorm(event)"><label for="brainstormInput">낱말이나 짧은 구 하나</label><div><input class="input" id="brainstormInput" maxlength="20" autocomplete="off" placeholder="${esc(p.placeholder||"예: 반짝이는 물")}"><button type="submit">우리 방에 올리기</button></div><small>사람 이름이나 학교 이름은 쓰지 않고, 주제와 관련된 말만 올려요.</small></form><section class="brainstorm-section shared"><div class="brainstorm-heading"><div><small>TOGETHER</small><h3>우리 방 아이디어</h3></div><span id="brainstormLiveStatus">${esc(brainstormStatus())}</span></div><div class="brainstorm-cloud" id="brainstormBoard">${brainstormWordsMarkup()}</div></section><section class="brainstorm-section mine"><div class="brainstorm-heading"><div><small>MY WORD POOL</small><h3>내가 골라 만든 단어풀</h3></div><b>${personalBrainstorm().length}개</b></div><div class="brainstorm-cloud" id="personalBoard">${personalWordsMarkup()}</div></section>${statusBar(i,p)}</div>`}  function choicePage(p,i){const current=p.multi?selected(p.key):state.answers[p.key];return `${header(p,i)}<div class="lesson-body">${p.prompt?`<div class="prompt"><strong>${esc(p.promptTitle||"생각 열기")}</strong>${esc(p.prompt)}</div>`:""}<div class="choice-grid">${p.choices.map(c=>{const on=p.multi?current.includes(c.value):current===c.value;return `<button class="choice ${on?"on":""}" onclick="WaterLesson.choose('${p.key}','${esc(c.value)}',${Boolean(p.multi)},${p.max||0})"><b>${esc(c.label)}</b><span>${esc(c.desc||"")}</span><i class="choice-mark">✓</i></button>`}).join("")}</div>${p.multi?`<p class="selected-note">${current.length}개 선택 · 마음에 드는 것을 ${p.max||"여러 개"}까지 고를 수 있어요.</p>`:""}${statusBar(i,p)}</div>`}
  function pageParts(p){const parts=resolve(p.parts);return Array.isArray(parts)&&parts.length?parts:[{label:"예시",text:"예시를 준비하고 있어요."}]}
  function readPage(p,i){const parts=pageParts(p),part=Math.min(state.readParts[i]||0,parts.length-1),item=parts[part];return `${header(p,i)}<div class="lesson-body"><div class="read-card"><div class="read-meta"><strong>${esc(resolve(p.exampleLabel))}</strong><span class="part-chip">${part+1} / ${parts.length} · ${esc(item.label)}</span></div><p class="read-text">${esc(item.text)}</p><div class="read-nav"><div class="dots">${parts.map((_,n)=>`<i class="${n===part?"on":""}"></i>`).join("")}</div>${part<parts.length-1?`<button class="mini-button primary" onclick="WaterLesson.readNext(${i})">다음 부분 읽기</button>`:`<button class="mini-button primary" onclick="WaterLesson.readDone(${i})">읽기를 마쳤어요</button>`}</div></div>${state.answers[`read-${i}`]?`<div class="prompt" style="margin-top:14px"><strong>살펴본 점</strong>${esc(resolve(p.notice))}</div>`:""}${statusBar(i,p)}</div>`}
  function sequencePage(p,i){const step=Math.min(state.substeps[i]||0,p.stages.length-1),s=p.stages[step],value=state.texts[s.key]||"",exampleText=resolve(s.exampleText),exampleLabel=resolve(s.exampleLabel)||"이 단계의 예시";return `${header(p,i)}<div class="lesson-body"><div class="stage-card"><div class="stage-count">생각 ${step+1} / ${p.stages.length}</div><h3>${esc(s.title)}</h3><p>${esc(s.prompt)}</p>${exampleCard(`seq-${s.key}`,exampleLabel,exampleText)}${personalWordPool(s.key)}${wordPool(s.words,s.key)}<textarea class="area" placeholder="${esc(s.placeholder||"짧게 적어 보세요.")}" oninput="WaterLesson.setText('${s.key}',this.value)">${esc(value)}</textarea><div class="count"><span>한두 문장으로 충분해요.</span><span>${value.length}자</span></div><div class="read-nav"><button class="mini-button" ${step===0?"disabled":""} onclick="WaterLesson.substep(${i},-1)">이전 생각</button>${step<p.stages.length-1?`<button class="mini-button primary" onclick="WaterLesson.substep(${i},1)">다음 생각</button>`:`<span class="part-chip">계획 완성</span>`}</div></div>${statusBar(i,p)}</div>`}
  function wordPool(words,key){if(!words?.length)return "";return `<div class="word-pool"><strong>쓸 수 있는 낱말</strong><div class="word-list">${words.map(w=>`<button class="word" data-track="hint" data-help-level="A2" onclick="WaterLesson.addWord('${key}','${esc(w)}')">${esc(w)}</button>`).join("")}</div></div>`}
  function exampleCard(key,label,text){if(!text)return "";const open=Boolean(state.exampleOpen[key]);return `<div class="read-card step-example"><div class="read-meta"><strong>${esc(label)}</strong><button class="mini-button example-toggle"${open?"":' data-track="hint" data-help-level="A3"'} aria-expanded="${open}" onclick="WaterLesson.toggleExample('${key}')">${open?"예시 접기":"예시 보기"}</button></div>${open?`<p class="read-text">${esc(text)}</p>`:`<p class="example-hint">먼저 혼자 써 보세요. 막히면 예시를 펼쳐 봐도 괜찮아요.</p>`}</div>`}
  function writePage(p,i){const value=state.texts[p.key]||"",context=p.contextKey?(state.answers[p.contextKey]||state.texts[p.contextKey]||""):"",contextLabel=resolve(p.contextLabel)||"앞에서 고른 내용",exampleText=resolve(p.exampleText),exampleLabel=resolve(p.exampleLabel)||"이 단계의 예시",prompt=resolve(p.prompt),words=resolve(p.words),placeholder=resolve(p.placeholder),note=resolve(p.note)||"완벽하게 쓰려고 멈추지 말고, 떠오르는 문장부터 적어 보세요.";return `${header(p,i)}<div class="lesson-body">${context?`<p class="write-context"><b>${esc(contextLabel)}</b>${esc(context)}</p>`:""}${exampleCard(`write-${p.key}`,exampleLabel,exampleText)}${prompt?`<p class="write-cue">${esc(prompt)}</p>`:""}${personalWordPool(p.key)}${wordPool(words,p.key)}<textarea class="area" placeholder="${esc(placeholder)}" oninput="WaterLesson.setText('${p.key}',this.value)">${esc(value)}</textarea><div class="count"><span>${esc(note)}</span><span>${value.length}자</span></div>${statusBar(i,p)}</div>`}
  function reasonsPage(p,i){const step=Math.min(state.substeps[i]||0,1),side=state.answers.stance||"찬성",question=state.answers.question||"선택한 질문",seedSet=(p.seeds[question]?.[side]||p.fallback[side]||[]),reasonKey=`reason${step+1}`,detailKey=`detail${step+1}`,reason=state.texts[reasonKey]||"",detail=state.texts[detailKey]||"",examples=resolve(p.examples)||[],exampleText=examples[step]||"";return `${header(p,i)}<div class="lesson-body"><p class="selected-note">${esc(question)} · 나의 입장: ${esc(side)}</p>${exampleCard(`reason-${step}`,(state.answers.level||"1수준")+` 예시 · ${step+1}번째 근거`,exampleText)}<div class="stage-card"><div class="stage-count">근거 ${step+1} / 2</div><h3>근거 하나를 문장으로 만들어요</h3><p>씨앗은 낱말과 구일 뿐이에요. 마음에 드는 것을 눌러 내 문장으로 바꾸세요.</p>${personalWordPool(reasonKey)}${wordPool(seedSet,reasonKey)}<textarea class="area" style="min-height:120px" placeholder="이 씨앗이 내 주장을 왜 뒷받침하는지 한 문장으로 적어 보세요." oninput="WaterLesson.setText('${reasonKey}',this.value)">${esc(reason)}</textarea><div class="prompt" style="margin-top:13px"><strong>한 걸음 더</strong>구체적인 장면, 생기는 영향 또는 예상되는 결과를 한두 문장으로 덧붙여요.</div><textarea class="area" style="min-height:130px" placeholder="예를 들거나, 누구에게 어떤 변화가 생기는지 적어 보세요." oninput="WaterLesson.setText('${detailKey}',this.value)">${esc(detail)}</textarea><div class="read-nav"><button class="mini-button" ${step===0?"disabled":""} onclick="WaterLesson.substep(${i},-1)">첫 번째 근거</button><button class="mini-button primary" onclick="WaterLesson.substep(${i},1)">${step===0?"두 번째 근거로":"두 근거 확인"}</button></div></div>${statusBar(i,p)}</div>`}
  function compose(){if(lesson.compose)return lesson.compose(state).filter(Boolean).join("\n\n");return Object.values(state.texts).filter(Boolean).join("\n\n")}
  function reviewPage(p,i){if(!state.final)state.final=compose();if(!state.beforeRevision){state.beforeRevision=state.final;save(false)}const sections=p.sections||[];return `${header(p,i)}<div class="lesson-body">${sections.length?`<div class="review-list">${sections.map(s=>{const value=s.answerKey?state.answers[s.answerKey]:state.texts[s.key];return `<div class="review-item"><b>${esc(s.label)}</b><p class="${value?"":"empty"}">${esc(value||"아직 적지 않았어요.")}</p></div>`}).join("")}</div>`:""}<div class="stage-card" style="margin-top:13px"><h3>${esc(p.finalTitle||"나의 완성 글")}</h3><p>앞에서 쓴 내용이 모였어요. 겹치는 말이나 어색한 부분만 고쳐 보세요.</p><textarea class="area" style="min-height:310px" oninput="WaterLesson.setFinal(this.value)">${esc(state.final||compose())}</textarea><div class="finish-actions"><button class="mini-button" onclick="WaterLesson.rebuild()">앞의 글 다시 모으기</button><button class="mini-button primary" onclick="WaterLesson.copyFinal()">완성 글 복사</button></div></div>${statusBar(i,p)}</div>`}
  function finishPage(p,i){const submitted=Boolean(state.submittedAt);return `${header(p,i)}<div class="lesson-body"><div class="finish-card" data-track="lesson-complete"><div class="finish-mark">✓</div><h3>${esc(p.message||"한 편의 글을 완성했어요!")}</h3><p>${esc(p.detail||"기기에 자동으로 저장되어 있어요. 다시 읽고 고쳐도 괜찮아요.")}</p><div class="finish-actions"><button class="mini-button primary" onclick="WaterLesson.go(${lesson.pages.length-2})">첨삭 후 글 다시 보기</button></div><section class="pilot-submit"><h4>${esc(nickname)} 이름으로 제출해요</h4><p>처음 완성 페이지에 들어왔을 때의 글은 ‘첨삭 전’, 이후 고친 글은 ‘첨삭 후’로 함께 전송됩니다.</p><label class="pilot-privacy"><input id="pilotPrivacy" type="checkbox" ${submitted?"checked disabled":""}><span>두 글에 실명, 학교명, 학년·반, 연락처, 친구의 실명을 쓰지 않았어요.</span></label><button class="pilot-submit-button" type="button" onclick="WaterLesson.submitPilot(this)" ${submitted?"disabled":""}>${submitted?"제출 완료":"선생님께 제출하기"}</button><p class="pilot-submit-status" id="pilotSubmitStatus">${submitted?"제출했어요 · "+new Date(state.submittedAt).toLocaleString("ko-KR"):""}</p></section></div></div>`}
  function pilotPayload(){
    const beforeText=String(state.beforeRevision||state.final||compose()).trim();
    const afterText=String(state.final||compose()).trim();
    const message=["물놀이 글쓰기 파일럿 제출","","닉네임: "+nickname,"회차: "+lesson.session,"장르: "+lesson.genre,"수업: "+lesson.title,"","[첨삭 전]",beforeText,"","[첨삭 후]",afterText].join("\n");
    return {access_key:String(pilotConfig.web3formsAccessKey||"").trim(),subject:"[물놀이 글쓰기] "+lesson.session+" · "+lesson.title+" · "+nickname,from_name:"물놀이 글쓰기 파일럿 · "+nickname,name:nickname,nickname:nickname,session:lesson.session,genre:lesson.genre,lesson_title:lesson.title,before_revision:beforeText,after_revision:afterText,message:message,botcheck:""};
  }
  async function submitPilot(button){
    const status=document.getElementById("pilotSubmitStatus"),privacy=document.getElementById("pilotPrivacy"),payload=pilotPayload();
    if(!privacy?.checked){toast("개인정보 확인란을 먼저 체크해 주세요.");return}
    if(!payload.after_revision){toast("완성 글이 아직 없어요.");return}
    if(!payload.access_key){if(status)status.textContent="제출 설정을 확인해 주세요.";return}
    button.disabled=true;button.textContent="제출하는 중…";if(status)status.textContent=nickname+" 이름으로 첨삭 전·후 글을 보내고 있어요.";
    try{
      const response=await fetch("https://api.web3forms.com/submit",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(payload)});
      const result=await response.json().catch(()=>({}));
      if(!response.ok||result.success===false){const submitError=new Error(result.message||"submission_failed");submitError.status=response.status;throw submitError}
      state.submittedAt=new Date().toISOString();save(false);render();toast("선생님께 제출했어요.")
    }catch(error){
      const limited=error?.status===429||/rate.?limit|too many requests/i.test(String(error?.message||""));
      if(limited){button.disabled=true;button.textContent="1시간 후 다시 제출";if(status)status.textContent="인터넷 문제가 아니에요. Web3Forms 요청이 많아 1시간 동안 제한되었어요. 작성한 글은 이 기기에 저장되어 있으니 나중에 다시 제출해 주세요.";return}
      button.disabled=false;button.textContent="다시 제출하기";if(status)status.textContent="전송하지 못했어요. 잠시 후 다시 시도해 주세요. 작성한 글은 이 기기에 저장되어 있어요."
    }
  }
  function render(){const p=lesson.pages[state.page],i=state.page;document.body.dataset.lessonPage=String(i);document.getElementById("topTitle").textContent=lesson.title;document.title=`${lesson.session} · ${lesson.title} | Oncuvate`;const renderers={choice:choicePage,brainstorm:brainstormPage,read:readPage,sequence:sequencePage,write:writePage,reasons:reasonsPage,review:reviewPage,finish:finishPage};const strategy=(p.type==="write"||p.type==="reasons")?"":strategyTip(p,i),content=renderers[p.type](p,i).replace('<div class="lesson-body">',`<div class="lesson-body">${strategy}`);const childActivityLocked=role!=="coach"&&coach.activityLocked,lockChip=role!=="coach"&&(coach.pageLocked||coach.activityLocked)?`<div class="student-lock-chip">${coach.pageLocked?"페이지 잠금 · 코치 화면과 함께 이동해요.":""}${coach.pageLocked&&coach.activityLocked?"  |  ":""}${coach.activityLocked?"활동 잠금 · 설명을 들으며 기다려 주세요.":""}</div>`:"",lockCover=childActivityLocked?'<div class="activity-lock-cover"><div><b>활동이 잠시 잠겼어요</b><p>코치의 설명을 들으며 이 화면에서 기다려 주세요.</p></div></div>':"";document.getElementById("page").innerHTML=`${lockChip}<section class="panel ${childActivityLocked?"activity-locked":""}">${content}${lockCover}</section>${coachPanel()}`;if(childActivityLocked)document.querySelector(".panel .lesson-body")?.setAttribute("inert","");enterPage(i);document.getElementById("nav").innerHTML=`<button class="prev" ${i===0?"disabled":""} onclick="WaterLesson.go(${i-1})">이전 단계</button><span>${i+1} / ${lesson.pages.length}</span><button class="next" ${i===lesson.pages.length-1?"disabled":""} onclick="WaterLesson.next()">다음 단계</button>`;renderJourney();window.scrollTo({top:0,behavior:"smooth"})}
  /* ===== 콘텐츠 안의 코치 화면 — 수업 중 진행을 보고 화면을 맞추는 자리.
     저장·집계·보고서는 만들지 않는다(규격 26번 §10.2는 그쪽만 금지한다). ===== */
  function coachMembers(){return Object.entries(coach.members||{}).filter(([id,v])=>v&&typeof v==="object"&&id!=="coach").map(([id,v])=>Object.assign({id:id},v)).sort((a,b)=>String(a.name||a.id).localeCompare(String(b.name||b.id),"ko"))}
  function coachChoiceSummary(member){return (Array.isArray(member?.choices)?member.choices:[]).map(item=>String(item?.value||"")).filter(Boolean).slice(0,2).join(" · ")}
  function coachChoiceList(member){const items=Array.isArray(member?.choices)?member.choices:[];if(!items.length)return `<section class="coach-choice-list empty"><h4>선택한 내용</h4><p>아직 선택한 내용이 없어요.</p></section>`;return `<section class="coach-choice-list"><h4>선택한 내용</h4><div>${items.map(item=>`<p><span>${esc(item.label||"선택")}</span><b>${esc(item.value)}</b></p>`).join("")}</div></section>`}
  function coachStageList(member){const texts=member?.texts||{};const rows=lesson.pages.flatMap((p,i)=>{const keys=p.type==="write"?[[p.key,p.short]]:p.type==="sequence"?p.stages.map(s=>[s.key,s.title]):p.type==="reasons"?[["reason1","근거 1"],["detail1","뒷받침 1"],["reason2","근거 2"],["detail2","뒷받침 2"]]:[];return keys.filter(([k])=>texts[k])});
    if(!rows.length&&!member?.final)return `<p class="coach-empty">아직 쓴 글이 없어요.</p>`;
    return rows.map(([k,label])=>`<div class="coach-text"><b>${esc(label)}<span>${String(texts[k]).length}자</span></b><p>${esc(texts[k])}</p></div>`).join("")+(member?.final?`<div class="coach-text final"><b>완성 글<span>${String(member.final).length}자</span></b><p>${esc(member.final)}</p></div>`:"")}
  function coachPanel(){if(role!=="coach")return "";const list=coachMembers();const sel=list.find(m=>m.id===coach.selected)||list[0]||null;
    const cards=list.length?list.map(m=>`<button class="coach-card ${sel&&m.id===sel.id?"on":""}" type="button" onclick="WaterLesson.coachPick('${esc(m.id)}')"><b>${esc(m.name||m.id)}</b><span>${esc(m.pageLabel||"")} · ${Number(m.page||0)+1}/${Number(m.pages||lesson.pages.length)}</span><small class="coach-choice-summary">${esc(coachChoiceSummary(m)||"선택 전")}</small><small>${Number(m.chars||0)}자 · 완료 ${Number(m.done||0)}${Number(m.help||0)?` · <i>도움 요청 ${Number(m.help)}</i>`:""}</small><em class="coach-progress-mini" aria-label="${Number(m.page||0)+1}/${Number(m.pages||lesson.pages.length)} 페이지 진행"><span style="width:${Math.max(6,Math.round((Number(m.page||0)+1)/Math.max(1,Number(m.pages||lesson.pages.length))*100))}%"></span></em></button>`).join(""):`<p class="coach-empty">아직 들어온 참여자가 없어요.</p>`;
    return `<section class="coach-panel"><div class="coach-head"><div><small>COACH</small><h3>수업 진행 보기</h3></div><span class="coach-live">${liveRoom?(brainstormBound?`수업방 연결됨 · 참여자 ${list.length}명`:"수업방 연결 준비 중"):"혼자 보기 모드"}</span></div>
      <div class="coach-control-state"><span class="${coach.pageLocked?"on":""}">페이지 ${coach.pageLocked?"잠금 중":"자유 이동"}</span><span class="${coach.activityLocked?"on":""}">활동 ${coach.activityLocked?"잠금 중":"입력 가능"}</span></div>
      <div class="coach-actions"><button class="mini-button primary" onclick="WaterLesson.coachGather()">이 페이지로 모으기</button><button class="mini-button" onclick="WaterLesson.coachLock()">페이지 ${coach.pageLocked?"잠금 해제":"잠금"}</button><button class="mini-button" onclick="WaterLesson.coachActivityLock()">활동 ${coach.activityLocked?"잠금 해제":"잠금"}</button><button class="mini-button" onclick="WaterLesson.coachToggle()">${coachOpen?"패널 접기":"패널 펴기"}</button></div>
      ${coachOpen?`<div class="coach-grid">${cards}</div>${sel?`<div class="coach-detail"><div class="coach-detail-head"><b>${esc(sel.name||sel.id)}</b><span>${esc(sel.genre||lesson.genre)} · 낱말 ${Number(sel.words||0)}개</span></div>${coachChoiceList(sel)}${coachStageList(sel)}</div>`:""}<p class="coach-note">수업 중 지도를 위한 화면입니다. 아이가 쓴 글은 이 화면 밖으로 옮기지 마세요.</p>`:""}</section>`}
  function toast(message){const el=document.getElementById("toast");el.textContent=message;el.classList.add("on");setTimeout(()=>el.classList.remove("on"),1700)}
  window.WaterLesson={
    go(i){if(i<0||i>=lesson.pages.length)return;if(coach.pageLocked&&role!=="coach")return toast("페이지 잠금 중에는 코치 화면과 함께 이동해요.");state.page=i;state.maxPage=Math.max(state.maxPage,i);save(false);render();if(role==="coach")publishNav()},
    coachPick(id){coach.selected=id;render()},
    coachToggle(){coachOpen=!coachOpen;render()},
    coachLock(){coach.pageLocked=!coach.pageLocked;publishNav();render();toast(coach.pageLocked?"모든 학생의 페이지를 코치 화면과 연결했어요.":"학생이 페이지를 자유롭게 이동할 수 있어요.")},
    coachActivityLock(){coach.activityLocked=!coach.activityLocked;publishNav();render();toast(coach.activityLocked?"모든 학생의 활동 입력을 잠갔어요.":"학생이 다시 활동할 수 있어요.")},
    coachGather(){coach.pageLocked=true;publishNav();render();toast("모든 학생을 이 페이지로 모았어요.")},
    next(){if(coach.pageLocked&&role!=="coach")return toast("페이지 잠금 중에는 코치 화면과 함께 이동해요.");if(pageDone(state.page))state.completed[state.page]=true;state.maxPage=Math.max(state.maxPage,state.page+1);state.page=Math.min(lesson.pages.length-1,state.page+1);save();render();if(role==="coach")publishNav()},
    choose(key,value,multi,max){if(multi){const list=selected(key);const pos=list.indexOf(value);if(pos>=0)list.splice(pos,1);else if(!max||list.length<max)list.push(value);else return toast(`${max}개까지 고를 수 있어요.`);state.answers[key]=list}else state.answers[key]=value;state.final="";save();render()},
    addBrainstorm(event){event?.preventDefault?.();const input=document.getElementById("brainstormInput"),word=normalizeWord(input?.value);if(!word)return toast("낱말이나 짧은 구 하나를 적어 주세요.");const own=ownBrainstorm(),personal=personalBrainstorm(),key=word.toLocaleLowerCase("ko");if(!own.some(item=>item.toLocaleLowerCase("ko")===key)){if(own.length>=12)return toast("내가 올릴 수 있는 말은 12개까지예요.");own.push(word);state.brainstormOwn[lesson.id]=own}if(!personal.some(item=>item.toLocaleLowerCase("ko")===key)){if(personal.length<12)personal.push(word);state.personalWords[lesson.id]=personal}save();aggregateBrainstorm({});publishBrainstorm();if(input){input.value="";input.focus()}updateBrainstormDOM()},
    pickShared(encoded){const word=normalizeWord(decodeURIComponent(encoded)),words=personalBrainstorm(),key=word.toLocaleLowerCase("ko"),index=words.findIndex(item=>item.toLocaleLowerCase("ko")===key);if(index>=0)words.splice(index,1);else{if(words.length>=12)return toast("내 단어풀은 12개까지 담을 수 있어요.");words.push(word)}state.personalWords[lesson.id]=words;save();updateBrainstormDOM()},
    setText(key,value){noteInput(key);state.texts[key]=value;state.final="";save()},
    setFinal(value){state.final=value;save()},
    addPersonalWord(key,encoded){this.addWord(key,decodeURIComponent(encoded))},
    addWord(key,word){noteInsert(key,word);const current=String(state.texts[key]||"");state.texts[key]=current+(current&& !current.endsWith(" ")?" ":"")+word;state.final="";save();render()},
    readNext(i){state.readParts[i]=Math.min((state.readParts[i]||0)+1,pageParts(lesson.pages[i]).length-1);save(false);render()},
    readDone(i){state.answers[`read-${i}`]=true;state.completed[i]=true;save();render()},
    substep(i,delta){const p=lesson.pages[i],max=p.type==="reasons"?1:p.stages.length-1;state.substeps[i]=Math.max(0,Math.min(max,(state.substeps[i]||0)+delta));save(false);render()},
    toggleStrategy(i){state.strategyOpen[i]=!state.strategyOpen[i];save(false);render()},
    toggleExample(key){state.exampleOpen[key]=!state.exampleOpen[key];save(false);render()},
    help(i){state.help[i]=!state.help[i];save(false);render()},
    complete(i){state.completed[i]=true;state.maxPage=Math.max(state.maxPage,i+1);save();render()},
    rebuild(){metrics.rebuilt=true;state.final=compose();save();render();toast("앞에서 쓴 글을 다시 모았어요.")},
    async copyFinal(){try{await navigator.clipboard.writeText(state.final||compose());toast("완성 글을 복사했어요.")}catch{toast("복사하지 못했어요. 글을 직접 선택해 주세요.")}},
    submitPilot(button){return submitPilot(button)}
  };
  document.getElementById("sessionLabel").textContent=lesson.session;
  document.getElementById("sideTitle").textContent=lesson.title;
  document.getElementById("watermark").textContent=nickname;
  if(role==="coach")state.maxPage=lesson.pages.length-1;
  bindLive();
  ocLog("lesson_start",{genre:lesson.genre,session:String(lesson.session||""),pages:lesson.pages.length,resumedAt:state.page+1});
  window.addEventListener("pagehide",()=>{if(metrics.page>=0)ocLog("activity_end",pageStats(metrics.page))},{once:true});
  render();
})();
