// 1회차 데이터 — app.js의 lessons 객체에서 내용 변경 없이 옮겼습니다.
window.ONCUVATE_SESSION = 1;
window.ONCUVATE_LESSON = {
  title: '낯선 동네를 걸어요',
  subtitle: '받침 뒤에서 첫소리가 달라지는 낱말을 정확하게 읽어요.',
  thumb: 'assets/scenes/scene-03.jpg',
  steps: [
    { type: 'goal', title: '오늘 읽기', minutes: 2 },
    { type: 'scale', title: '시작 전 생각하기', minutes: 2 },
    { type: 'colorobservation', phase: 'pre_observation', supportLevel: 'none', title: '내 색이 나오면 빠르게 읽어요', minutes: 3,
      heading: '내 색이 나오면 빠르게 읽어요',
      description: '카드를 한 장씩 뒤집어요. 내 색 카드가 나오면 보이는 낱말을 읽어요.',
      items: [
        { word: '목걸이', expectedPronunciation: '목꺼리', targetRule: 'tensing', exposure: 'unseen' },
        { word: '학급', expectedPronunciation: '학끕', targetRule: 'tensing', exposure: 'unseen' },
        { word: '숙박', expectedPronunciation: '숙빡', targetRule: 'tensing', exposure: 'unseen' },
        { word: '약병', expectedPronunciation: '약뼝', targetRule: 'tensing', exposure: 'unseen' },
        { word: '늑대', expectedPronunciation: '늑때', targetRule: 'tensing', exposure: 'unseen' },
        { word: '국자', expectedPronunciation: '국짜', targetRule: 'tensing', exposure: 'unseen' }
      ],
      fillerItems: ['나무', '모자', '토끼', '바다', '우유', '고래'],
      colorCount: 4, rounds: 12 },
    { type: 'syllable', title: '끝소리 길게 이어 보기', minutes: 2,
      pairs: [['하', '학'], ['나', '낯'], ['와', '왔'], ['꼬', '꽃']],
      question: '‘학’의 끝소리를 길게 이어 말할 수 있을까요?', answer: '짧게 멈춰요' },
    { type: 'lettergame', title: '끝소리 느낌 찾기', minutes: 2,
      items: [
        { letter: '가', answer: 'open' }, { letter: '각', answer: 'closed' },
        { letter: '소', answer: 'open' }, { letter: '속', answer: 'closed' },
        { letter: '비', answer: 'open' }, { letter: '빛', answer: 'closed' }
      ] },
    { type: 'flipgame', title: '끝소리 카드 뒤집기', minutes: 4 },
    { type: 'soundchange', title: '젤리티처의 소리 변화 탐구실', minutes: 3,
      rounds: [
        { word: '학교도', syllables: ['학', '교', '도'], targets: [1], tensingTargets: [1], change: '교의 첫소리가 세게 바뀌어요.' },
        { word: '낯설어요', syllables: ['낯', '설', '어', '요'], targets: [1, 2], tensingTargets: [1], liaisonTargets: [2], change: '설의 첫소리가 세게 바뀌고, 앞의 끝소리는 어로 이어져요.' },
        { word: '찾을', syllables: ['찾', '을'], targets: [1], liaisonTargets: [1], change: '찾의 끝소리가 을로 이어져요.' },
        { word: '옆집은', syllables: ['옆', '집', '은'], targets: [1, 2], tensingTargets: [1], liaisonTargets: [2], change: '집의 첫소리가 세게 바뀌고, 집의 끝소리는 은으로 이어져요.' },
        { word: '빗자루', syllables: ['빗', '자', '루'], targets: [1], tensingTargets: [1], change: '자의 첫소리가 세게 바뀌어요.' }
      ] },
    { type: 'story', title: '그림책에서 읽기', minutes: 3, scene: 2,
      passage: '동네도, 학교도, 친구들도 모두 낯설어요.<br>바로 어제 이사를 왔거든요.',
      spoken: '동네도, 학교도, 친구들도 모두 낯설어요. 바로 어제 이사를 왔거든요.',
      chunks: ['동네도, 학교도, 친구들도', '모두 낯설어요.', '바로 어제', '이사를', '왔거든요.'],
      soundMarks: [{ surface: '학교도', indices: [1] }, { surface: '낯설어요', indices: [1], liaisonIndices: [2], otherIndices: [0] }, { surface: '왔거든요', indices: [1], otherIndices: [0, 3] }],
      targets: ['학교도', '낯설어요', '왔거든요'] },
    { type: 'story', title: '끊어읽기 연습', minutes: 3, scene: 3,
      passage: '“찾을 수 있어.”<br><span class="focus-word">대문을 나와</span> <span class="focus-word">타박타박 걸어갔어요.</span><br>왼쪽은 부동산, 오른쪽은 꽃집.<br>“여기도 아니야.”',
      spoken: '찾을 수 있어. 대문을 나와 타박타박 걸어갔어요. 왼쪽은 부동산, 오른쪽은 꽃집. 여기도 아니야.',
      chunks: ['“찾을 수 있어.”', '대문을 나와', '타박타박 걸어갔어요.', '왼쪽은 부동산,', '오른쪽은 꽃집.', '“여기도 아니야.”'],
      soundMarks: [{ surface: '찾을', liaisonIndices: [0, 1] }, { surface: '있어', liaisonIndices: [0, 1] }, { surface: '대문을', liaisonIndices: [1, 2] }, { surface: '걸어갔어요', liaisonIndices: [0, 1, 2, 3] }, { surface: '왼쪽은', liaisonIndices: [1, 2] }, { surface: '오른쪽은', liaisonIndices: [2, 3] }, { surface: '꽃집', indices: [1], otherIndices: [0] }],
      excludedSoundMarks: [{ surface: '찾을 수', indices: [2], reason: 'current-stage-out-of-scope' }],
      targets: ['꽃집'] },
    { type: 'story', title: '그림책에서 읽기', minutes: 3, scene: 4,
      passage: '매콤달콤 떡볶이랑 김밥을 파는 분식집.<br>옆집은 미역과 멸치를 파는 건어물 가게.<br>못, 망치, 빗자루를 파는 철물점.<br>“어디 있지?”',
      spoken: '매콤달콤 떡볶이랑 김밥을 파는 분식집. 옆집은 미역과 멸치를 파는 건어물 가게. 못, 망치, 빗자루를 파는 철물점. 어디 있지?',
      soundMarks: [{ surface: '떡볶이랑', indices: [1], liaisonIndices: [2] }, { surface: '김밥을', liaisonIndices: [1, 2] }, { surface: '분식집', indices: [2] }, { surface: '옆집은', indices: [1], liaisonIndices: [2], otherIndices: [0] }, { surface: '미역과', indices: [2] }, { surface: '건어물', liaisonIndices: [0, 1] }, { surface: '못', otherIndices: [0] }, { surface: '빗자루', indices: [1], otherIndices: [0] }, { surface: '있지', indices: [1], otherIndices: [0] }],
      excludedSoundMarks: [{ surface: '철물점', indices: [2], reason: 'current-stage-out-of-scope' }],
      targets: ['분식집', '옆집', '미역과', '빗자루', '있지'] },
    { type: 'game', title: '글자 조각 맞추기', minutes: 3,
      prompt: '그림 속 짧은 말을 떠올리며 글자 조각을 차례로 놓아 보세요.',
      pool: [
        { scene: 2, phrase: '모두 낯설어요', answer: ['모', '두', '낯', '설', '어', '요'], breakAfter: [1] },
        { scene: 2, phrase: '바로 어제', answer: ['바', '로', '어', '제'], breakAfter: [1] },
        { scene: 3, phrase: '찾을 수 있어', answer: ['찾', '을', '수', '있', '어'], breakAfter: [1, 2] },
        { scene: 3, phrase: '대문을 나와', answer: ['대', '문', '을', '나', '와'], breakAfter: [2] },
        { scene: 3, phrase: '오른쪽 꽃집', answer: ['오', '른', '쪽', '꽃', '집'], breakAfter: [2] },
        { scene: 3, phrase: '여기도 아니야', answer: ['여', '기', '도', '아', '니', '야'], breakAfter: [2] },
        { scene: 4, phrase: '김밥을 파는', answer: ['김', '밥', '을', '파', '는'], breakAfter: [2] },
        { scene: 4, phrase: '옆집은 미역과', answer: ['옆', '집', '은', '미', '역', '과'], breakAfter: [2] },
        { scene: 4, phrase: '빗자루를 파는', answer: ['빗', '자', '루', '를', '파', '는'], breakAfter: [3] },
        { scene: 4, phrase: '어디 있지', answer: ['어', '디', '있', '지'], breakAfter: [1] }
      ] },
    { type: 'reread', title: '한 번 더 읽기', minutes: 3, scene: 3,
      passage: '“찾을 수 있어.”<br>대문을 나와 타박타박 걸어갔어요.<br>왼쪽은 부동산, 오른쪽은 꽃집.<br>“여기도 아니야.”',
      spoken: '찾을 수 있어. 대문을 나와 타박타박 걸어갔어요. 왼쪽은 부동산, 오른쪽은 꽃집. 여기도 아니야.',
      soundMarks: [{ surface: '찾을', liaisonIndices: [0, 1] }, { surface: '있어', liaisonIndices: [0, 1] }, { surface: '대문을', liaisonIndices: [1, 2] }, { surface: '걸어갔어요', liaisonIndices: [0, 1, 2, 3] }, { surface: '왼쪽은', liaisonIndices: [1, 2] }, { surface: '오른쪽은', liaisonIndices: [2, 3] }, { surface: '꽃집', indices: [1], otherIndices: [0] }],
      excludedSoundMarks: [{ surface: '찾을 수', indices: [2], reason: 'current-stage-out-of-scope' }] },
    { type: 'generalization', title: '책 밖의 새 자료 읽기', minutes: 6,
      levels: [
        { code: 'T1', label: '스피드리딩', kind: 'words', passAt: 8, poolStart: 0,
          items: ['옷가게', '낮잠', '책상', '국밥', '약국', '옷장', '꽃병', '밥상', '책장', '입구'],
          pool: ['옷가게', '낮잠', '책상', '국밥', '약국', '옷장', '꽃병', '밥상', '책장', '입구', '국수', '숙제', '식당', '앞집', '빗방울', '꽃다발', '책가방', '옷걸이', '맥주', '작가', '축구', '약속', '깃발', '꽃밭', '낚시', '접시', '박수', '색종이', '각자', '법정'],
          instruction: '책에서 보지 않은 낱말 10개를 하나씩 도움 없이 읽어 보세요.' },
        { code: 'T2', label: '글자 바꾸기', kind: 'nonwords', passAt: 4, poolStart: 0,
          items: ['칙송', '닻점', '귝법', '압게', '삭조'],
          pool: ['칙송', '닻점', '귝법', '압게', '삭조', '봅성', '척중', '촉가', '졋붕', '넉소', '엇종', '갓벌', '줍새', '얍봉', '억고'],
          reviewStatus: 'human-review-required',
          instruction: '소리를 듣고 비단어를 글자 조각으로 나누거나 다시 하나의 말로 모아 보세요.' },
        { code: 'T3', label: '문장 순서 맞추기', kind: 'sentence-order', passAt: 4,
          items: ['옷가게 앞에서 낮잠을 잤어요.', '책상 위에 꽃병이 있어요.', '약국 옆 식당에서 국밥을 먹어요.', '새 책장을 방에 놓았어요.', '입구 옆에 옷장이 보여요.'],
          instruction: '새 문장의 낱말 순서를 맞춘 뒤 정확하게 읽어 보세요.' }
      ] },
    { type: 'reflection', title: '활동 후 돌아보기', minutes: 1 }
  ]
};
