(()=>{"use strict";
const data=window.LESSON_DATA,level=window.LESSON_LEVEL,pages=[...document.querySelectorAll(".page")];let page=0,predictIndex=0,questionIndex=0,questionAttempts=0,spyIndex=0,classifyIndex=0,verifyIndex=0,verifyCoachStep=0,transferIndex=0,toastTimer;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={classification:shuffle(data.classification.slice()),counts:Object.fromEntries(Object.keys(data.stages).map(key=>[key,0])),reflection:"",reflectionStrategy:""};
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function log(action,itemId,extra={}){const detail={lessonId:"l16-ondol-careful-reading",lessonVersion:"0.1.0",level,action,itemId,timestamp:new Date().toISOString(),...extra};document.dispatchEvent(new CustomEvent("oncuvate:log",{detail}));window.parent?.postMessage({type:"ONCUVATE_LESSON_EVENT",...detail},"*")}
function showToast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2200)}
function feedback(el,message,type){el.textContent=message;el.classList.remove("ok","bad");if(type)el.classList.add(type)}
function normalize(v){return String(v||"").replace(/[\s.,!?·'\"“”‘’]/g,"")}
function normalizeShortAnswer(v){return normalize(v).replace(/(입니다|이에요|예요|이다)$/,"")}
function showPage(next){page=Math.max(0,Math.min(pages.length-1,next));pages.forEach((p,i)=>p.classList.toggle("active",i===page));$$('.step-link').forEach((b,i)=>{b.classList.toggle("active",i===page);b.toggleAttribute("aria-current",i===page)});$$('.step-dots button').forEach((b,i)=>b.classList.toggle("active",i===page));$("#progressBar").style.width=((page+1)/pages.length*100)+"%";$("#backButton").disabled=page===0;$("#nextButton").textContent="다음";$("#nextButton").classList.toggle("hidden",page===pages.length-1);$("#stage").scrollTop=0;const dock=$("#annotationDock"),toolbar=$("#annotationToolbar"),dockToggle=$("#annotationDockToggle");if(dock){dock.classList.toggle("hidden",page!==1);if(page!==1){toolbar.classList.add("hidden");dockToggle.setAttribute("aria-expanded","false")}}log("page_view","page-"+(page+1));spyOnPage(page);window.dispatchEvent(new Event("resize"))}
function setupAnnotationDock(){const toggle=$("#annotationDockToggle"),toolbar=$("#annotationToolbar");toggle.onclick=()=>{const open=toolbar.classList.toggle("hidden")===false;toggle.setAttribute("aria-expanded",String(open));log("annotation_panel",open?"open":"close")}}
function setupNavigation(){const dots=$("#stepDots");pages.forEach((_,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",(i+1)+"단계로 이동");b.onclick=()=>showPage(i);dots.append(b)});$$('[data-go]').forEach(b=>b.onclick=()=>showPage(Number(b.dataset.go)));$("#backButton").onclick=()=>showPage(page-1);$("#nextButton").onclick=()=>{if(page===pages.length-1){finish()}else showPage(page+1)};$("#menuButton").onclick=()=>{const s=$("#sidebar"),open=!s.classList.contains("open");s.classList.toggle("open",open);$("#menuButton").textContent=open?"◀":"▶";$("#menuButton").setAttribute("aria-expanded",String(open))};$("#helpButton").onclick=()=>showToast(["제목과 그림을 보고 온돌에 나올 낱말을 예상해요.","본문을 가린 뒤 객관식 여섯 문제로 기억을 확인해요.","나와 젤리코치가 번갈아 칸을 골라요. 틀린 칸은 중립으로 남고 코치는 다른 칸을 골라요.","설명 카드를 알맞은 온돌 부분의 역할에 놓아요.","대상과 개수를 먼저 확인한 뒤 답을 골라요.","새 글에서도 열이 움직이는 순서를 확인해요.","오늘 실수한 것을 고르고, 다음에 사용할 방법을 확인해요."][page])}
function setupIntro(){const gate=$("#introGate"),start=$("#introStart"),params=new URLSearchParams(location.search),force=params.get("intro")==="1",seen=sessionStorage.getItem("l16-ondol-careful-reading:intro-seen")==="1";gate.classList.toggle("hidden",seen&&!force);start.onclick=()=>{sessionStorage.setItem("l16-ondol-careful-reading:intro-seen","1");gate.classList.add("hidden");const requested=params.get("level");if(requested!=="steady"&&requested!=="deep")$("#levelGate").classList.remove("hidden");log("intro_start","intro",{level:requested||"not-selected"})}}
function setupLevel(){const requested=new URLSearchParams(location.search).get("level");$("#levelGate").classList.toggle("hidden",requested==="steady"||requested==="deep");$$('[data-level-choice]').forEach(b=>b.onclick=()=>location.href="session01.html?level="+b.dataset.levelChoice);$("#changeLevel").onclick=()=>$("#levelGate").classList.remove("hidden");$("#levelPill").textContent=data.level+" · "+data.label;$("#readingLevel").textContent=data.label;$("#topTitle").textContent=data.title;$("#articleTitle").textContent=data.title}
function escapeHTML(v){const e=document.createElement("div");e.textContent=v;return e.innerHTML}
function renderPassage(){let html=data.paragraphs.map((p,i)=>'<p data-paragraph="'+i+'">'+escapeHTML(p)+'</p>').join("");data.vocab.forEach((v,i)=>{const word=escapeHTML(v[0]),button='<button class="vocab-word" type="button" data-vocab="'+i+'">'+word+'</button>';html=html.replace(word,button)});$("#passage").innerHTML=html;$$('[data-vocab]').forEach(b=>b.onclick=()=>openVocab(Number(b.dataset.vocab)));}
function openVocab(i){const v=data.vocab[i],saved=JSON.parse(localStorage.getItem("l16-ondol-careful-reading:vocab:"+level)||"[]");$("#vocabTitle").textContent=v[0];$("#vocabHanja").textContent=v[1];$("#vocabMeaning").textContent=v[2];$("#vocabExample").textContent=v[3];$("#vocabSave").dataset.index=i;$("#vocabSave").textContent=saved.includes(i)?"단어장에 담았어요":"단어장에 담기";$("#vocabDialog").classList.remove("hidden");log("vocab_open","vocab-"+i,{word:v[0]})}
function setupVocab(){$("#vocabClose").onclick=()=>$("#vocabDialog").classList.add("hidden");$("#vocabDialog").onclick=e=>{if(e.target===$("#vocabDialog"))$("#vocabDialog").classList.add("hidden")};$("#vocabSave").onclick=()=>{const i=Number($("#vocabSave").dataset.index),key="l16-ondol-careful-reading:vocab:"+level,saved=JSON.parse(localStorage.getItem(key)||"[]");if(!saved.includes(i))saved.push(i);localStorage.setItem(key,JSON.stringify(saved));$("#vocabSave").textContent="단어장에 담았어요";log("vocab_save","vocab-"+i,{word:data.vocab[i][0]})}}
function renderPrediction(){const item=data.prediction[predictIndex];$("#predictCounter").textContent=(predictIndex+1)+" / "+data.prediction.length;$("#predictProgress").style.width=((predictIndex+1)/data.prediction.length*100)+"%";$("#predictWord").textContent=item[0];feedback($("#predictFeedback"),"낱말을 살펴보고 판단해 보세요.");$("#predictNext").classList.add("hidden");$$('[data-predict-answer]').forEach(b=>{b.disabled=false;b.classList.remove("correct","wrong")})}
function setupPrediction(){$$('[data-predict-answer]').forEach(b=>b.onclick=()=>{const chosen=b.dataset.predictAnswer==="yes",correct=data.prediction[predictIndex][1];$$('[data-predict-answer]').forEach(x=>x.disabled=true);feedback($("#predictFeedback"),chosen===correct?(correct?"맞아요. 본문에서 이 낱말을 확인해 봐요.":"맞아요. 이 낱말은 주제와 관련이 없어요."):"그림과 제목의 주제를 다시 살펴보세요.",chosen===correct?"ok":"bad");log("answer","predict-"+predictIndex,{response:chosen,correct:chosen===correct});$("#predictNext").classList.remove("hidden")});$("#predictNext").onclick=()=>{if(predictIndex<data.prediction.length-1){predictIndex++;renderPrediction()}else{feedback($("#predictFeedback"),"예측을 마쳤어요. 이제 본문에서 확인해 봐요!","ok");$("#predictNext").classList.add("hidden")}}}
function addMemoryMessage(role,text,response=false){const row=document.createElement("div");row.className="memory-message "+role+(response?" memory-response":"");const label=document.createElement("span"),bubble=document.createElement("p");label.textContent=role==="coach"?"젤리코치":"나";bubble.textContent=text;row.append(label,bubble);$("#questionChat").append(row);$("#questionChat").scrollTop=$("#questionChat").scrollHeight}
function clearMemoryResponses(){$$(".memory-response",$("#questionChat")).forEach(x=>x.remove())}
function renderQuestion(){const q=data.questions[questionIndex],choices=$("#questionChoices"),next=$("#questionNext");questionAttempts=0;$("#questionCounter").textContent=(questionIndex+1)+" / "+data.questions.length;$("#questionChat").innerHTML="";addMemoryMessage("coach",q[0]);choices.innerHTML="";choices.classList.remove("hidden");q[1].forEach((text,i)=>{const b=document.createElement("button");b.type="button";b.innerHTML='<b>'+String.fromCharCode(65+i)+'</b><span>'+escapeHTML(text)+'</span>';b.onclick=()=>chooseMemoryAnswer(i,b);choices.append(b)});next.classList.add("hidden");next.textContent=questionIndex===data.questions.length-1?"확인 마치기":"다음 질문"}
function chooseMemoryAnswer(choice,button){const q=data.questions[questionIndex],correct=choice===q[2];questionAttempts++;log("answer","reading-q"+questionIndex,{response:choice,correct,attempt:questionAttempts});clearMemoryResponses();$$("button",$("#questionChoices")).forEach(b=>b.classList.remove("wrong"));if(!correct){button.classList.add("wrong");addMemoryMessage("coach","문장을 다시 떠올리고 다른 답을 골라 봐.",true);return}$$("button",$("#questionChoices")).forEach(b=>{b.disabled=true;b.classList.toggle("correct",b===button)});addMemoryMessage("coach",q[3],true);$("#questionNext").classList.remove("hidden")}
function setupReadingFlow(){const paper=$("#readingPaper"),cover=$("#passageCover"),panel=$("#questionPanel"),coach=$("#readingCoachPanel"),done=$("#readingDone"),toggle=$("#passageToggle");done.onclick=()=>{done.classList.add("hidden");paper.classList.add("covered");cover.classList.remove("hidden");coach.classList.add("hidden");panel.classList.remove("hidden");renderQuestion();log("reading_complete","reading-done",{level});window.dispatchEvent(new Event("resize"))};toggle.onclick=()=>{const peek=paper.classList.toggle("peek");toggle.textContent=peek?"본문 다시 가리기":"본문 다시 보기"}}function setupQuestions(){$("#questionNext").onclick=()=>{if(questionIndex<data.questions.length-1){questionIndex++;renderQuestion()}else{$("#questionChoices").classList.add("hidden");$("#questionNext").classList.add("hidden");clearMemoryResponses();addMemoryMessage("coach","여섯 문제를 모두 확인했어!",true)}}}
const SPY_LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const spy={status:[],used:[],attempts:[],lines:[],current:-1,phase:"",turn:"player",locateMiss:0,found:new Set(),audio:null,sound:true,particles:[],raf:0};
function spyCorrections(item){return Array.isArray(item[1])?item[1]:[]}
function spyTargets(tokens,item){return spyCorrections(item).map((pair,key)=>({key,from:pair[0],to:pair[1],index:tokens.findIndex(t=>t.includes(pair[0]))})).filter(x=>x.index>=0)}
function spySound(kind){if(!spy.sound)return;try{spy.audio=spy.audio||new (window.AudioContext||window.webkitAudioContext)();const ctx=spy.audio,now=ctx.currentTime,notes={open:[[520,0,.09],[780,.06,.12]],ok:[[660,0,.1],[880,.08,.1],[1320,.16,.18]],bad:[[220,0,.16],[180,.1,.18]],fix:[[520,0,.08],[700,.07,.08],[940,.14,.08],[1250,.21,.2]],bingo:[[523,0,.12],[659,.1,.12],[784,.2,.12],[1047,.3,.3]],pick:[[420,0,.05]]}[kind]||[];notes.forEach(([f,t,d])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=kind==="bad"?"triangle":"sine";o.frequency.setValueAtTime(f,now+t);g.gain.setValueAtTime(.0001,now+t);g.gain.exponentialRampToValueAtTime(.16,now+t+.015);g.gain.exponentialRampToValueAtTime(.0001,now+t+d);o.connect(g).connect(ctx.destination);o.start(now+t);o.stop(now+t+d+.05)})}catch(e){}}
function spyFxSize(){const c=$("#spyFx"),r=window.devicePixelRatio||1;c.width=innerWidth*r;c.height=innerHeight*r;c.getContext("2d").setTransform(r,0,0,r,0,0)}
function spyBurst(x,y,count,colors,power=1,confetti=false){if(reduceMotion)return;for(let i=0;i<count;i++){const a=confetti?Math.PI/2+(Math.random()-.5)*1.2:Math.random()*Math.PI*2,v=(confetti?3+Math.random()*5:2+Math.random()*5)*power;spy.particles.push({x:confetti?Math.random()*innerWidth:x,y:confetti?-20-Math.random()*120:y,vx:Math.cos(a)*v*(confetti?.5:1),vy:confetti?Math.random()*2:Math.sin(a)*v-2,life:confetti?160+Math.random()*80:50+Math.random()*30,age:0,size:confetti?6+Math.random()*6:3+Math.random()*4,color:colors[i%colors.length],rot:Math.random()*6,spin:(Math.random()-.5)*.3,shape:confetti||Math.random()<.4?"rect":"star"})}if(!spy.raf)spy.raf=requestAnimationFrame(spyTick)}
function spyTick(){const c=$("#spyFx"),ctx=c.getContext("2d");ctx.clearRect(0,0,innerWidth,innerHeight);spy.particles=spy.particles.filter(p=>p.age<p.life);spy.particles.forEach(p=>{p.age++;p.vy+=.12;p.vx*=.985;p.x+=p.vx;p.y+=p.vy;p.rot+=p.spin;ctx.save();ctx.globalAlpha=Math.max(0,1-p.age/p.life);ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.fillStyle=p.color;if(p.shape==="rect")ctx.fillRect(-p.size/2,-p.size/4,p.size,p.size/2);else{ctx.beginPath();for(let k=0;k<10;k++){const r=k%2?p.size*.45:p.size;ctx.lineTo(Math.cos(k*Math.PI/5)*r,Math.sin(k*Math.PI/5)*r)}ctx.closePath();ctx.fill()}ctx.restore()});spy.raf=spy.particles.length?requestAnimationFrame(spyTick):0}
function spyCenter(el){const r=el.getBoundingClientRect();return[r.left+r.width/2,r.top+r.height/2]}
function spyMsg(text,type){const el=$("#spyCaseMsg");el.textContent=text;el.classList.remove("ok","bad");if(type){void el.offsetWidth;el.classList.add(type)}}
function spyStamp(text,type){const s=$("#spyStamp");s.textContent=text;s.className="spy-stamp "+type;void s.offsetWidth;s.classList.add("show")}
function spyShake(el){el.classList.remove("shake");void el.offsetWidth;el.classList.add("shake")}
function renderSpyBoard(){const board=$("#spyBoard");board.innerHTML="";data.spy.forEach((item,i)=>{const b=document.createElement("button"),st=spy.status[i],done=Boolean(spy.used[i]),owner=st==="player"?"나":st==="coach"?"젤리코치":"아무도";b.type="button";b.className="spy-tile"+(done?" solved "+(st||"neutral"):"");b.dataset.index=i;b.style.setProperty("--i",i);b.disabled=spy.turn!=="player";b.setAttribute("aria-label",(i+1)+"번 문장"+(done?" · "+owner+"의 칸":" · 선택 가능"));const back=st==="coach"?'<em class="coach-mark">○</em><small>젤리코치</small>':st==="player"?'<em class="player-mark">×</em><small>나의 칸</small>':'<em class="neutral-mark">—</em><small>중립 칸</small>';b.innerHTML='<span class="spy-tile-inner"><span class="spy-face front"><i>'+(i+1)+'</i><span class="spy-shine"></span></span><span class="spy-face back">'+back+'</span></span>';b.onclick=()=>openSpyCase(i);board.append(b)});renderSpyLines(false);updateSpyHud()}
function renderSpyLines(animateIndex){const svg=$("#spyLines"),pos=[50,150,250];svg.classList.toggle("all-done",spy.used.every(Boolean)&&animateIndex===false);svg.innerHTML=spy.lines.map((entry,k)=>{const l=SPY_LINES[entry.line],a=l[0],z=l[2],x1=pos[a%3],y1=pos[Math.floor(a/3)],x2=pos[z%3],y2=pos[Math.floor(z/3)],ex=(x2-x1)*.14,ey=(y2-y1)*.14;return'<line class="'+entry.owner+(k===animateIndex?' draw':'')+'" x1="'+(x1-ex)+'" y1="'+(y1-ey)+'" x2="'+(x2+ex)+'" y2="'+(y2+ey)+'" pathLength="1" vector-effect="non-scaling-stroke"/>'}).join("")}
function updateSpyHud(){const mine=spy.status.filter(x=>x==="player").length,played=spy.used.filter(Boolean).length,myLines=spy.lines.filter(x=>x.owner==="player").length;$("#spySolved").textContent=mine;$("#spyBingo").textContent=myLines;$("#spyMeter").style.width=(played/data.spy.length*100)+"%";const turn=$("#spyTurn");if(turn){turn.textContent=spy.turn==="player"?"나의 차례":"젤리코치의 차례";turn.classList.toggle("coach",spy.turn==="coach")}}
function bump(el){el.classList.remove("bump");void el.offsetWidth;el.classList.add("bump")}
function renderSpySentence(done){const item=data.spy[spy.current],tokens=item[0].split(/\s+/),targets=spyTargets(tokens,item),box=$("#spySentence");box.innerHTML="";box.className="spy-sentence"+(done?"":" scan");tokens.forEach((t,k)=>{const hit=targets.find(x=>x.index===k),w=document.createElement("button");w.type="button";w.className="spy-word";w.style.setProperty("--k",k);w.disabled=done;w.textContent=done&&hit?t.replace(hit.from,hit.to):t;if(done&&hit)w.classList.add("fixed-static");w.onclick=()=>pickSpyWord(k,w);box.append(w);if(k<tokens.length-1)box.append(document.createTextNode(" "))})}
function openSpyCase(i){const tile=$('.spy-tile[data-index="'+i+'"]'),done=Boolean(spy.used[i]),owner=spy.status[i];if(!done&&spy.turn!=="player"){showToast("젤리코치가 칸을 고르고 있어요.");return}spy.current=i;spy.locateMiss=0;spy.found=new Set();spy.phase=done?"review":"locate";$("#spyCaseNo").textContent=i+1;$("#spyCaseKicker").textContent=done?(owner==="player"?"내가 얻은 칸":owner==="coach"?"젤리코치가 얻은 칸":"아무도 얻지 않은 칸"):"나의 차례";$("#spyCaseTitle").textContent=done?"바르게 고친 문장이에요":"잘못 읽힌 낱말을 모두 눌러요";renderSpySentence(done);$("#spyStamp").className="spy-stamp";$("#spyJudge").classList.add("hidden");$("#spyNext").classList.toggle("hidden",!done);$("#spyNext").textContent="보드로 돌아가기";$("#spyPeekPanel").classList.add("hidden");$("#spyPeek").textContent="본문 살짝 보기";const count=spyCorrections(data.spy[i]).length,doneMsg=owner==="player"?"잘못 읽힌 낱말을 모두 찾았어요.":owner==="coach"?"젤리코치가 고른 문장을 확인해 봐요.":"이 칸은 중립으로 남았어요. 바르게 고친 문장을 확인해 봐요.";spyMsg(done?doneMsg:"바뀐 낱말 "+count+"곳을 찾아요.",done?"ok":"");const modal=$("#spyModal"),card=$("#spyCase");modal.classList.remove("hidden","closing");modal.setAttribute("aria-hidden","false");tile.classList.add("opening");spySound("open");if(!reduceMotion&&card.animate){const t=tile.getBoundingClientRect(),c=card.getBoundingClientRect();card.animate([{transform:"translate("+(t.left+t.width/2-c.left-c.width/2)+"px,"+(t.top+t.height/2-c.top-c.height/2)+"px) scale("+(t.width/c.width)+","+(t.height/c.height)+") rotateY(90deg)",opacity:.3,borderRadius:"30px"},{transform:"none",opacity:1,borderRadius:"26px"}],{duration:520,easing:"cubic-bezier(.2,.9,.25,1.12)"});$$(".spy-word",card).forEach(w=>w.classList.add("enter"))}setTimeout(()=>tile.classList.remove("opening"),520);if(!done)$(".spy-word",card)?.focus({preventScroll:true});log("spy_open","spy-"+i,{review:done,owner:owner||"neutral"})}
function closeSpyCase(instant){const modal=$("#spyModal");if(modal.classList.contains("hidden"))return;const i=spy.current,tile=$('.spy-tile[data-index="'+i+'"]'),card=$("#spyCase"),finish=()=>{if(modal.classList.contains("hidden"))return;modal.classList.add("hidden");modal.classList.remove("closing");modal.setAttribute("aria-hidden","true");if(spy.phase==="solved"||spy.phase==="neutral"){spy.phase="";celebrateSpyTile(i)}};if(instant||reduceMotion||!card.animate||!tile){finish();return}const t=tile.getBoundingClientRect(),c=card.getBoundingClientRect();modal.classList.add("closing");setTimeout(finish,480);card.animate([{transform:"none",opacity:1},{transform:"translate("+(t.left+t.width/2-c.left-c.width/2)+"px,"+(t.top+t.height/2-c.top-c.height/2)+"px) scale("+(t.width/c.width)+","+(t.height/c.height)+")",opacity:0}],{duration:380,easing:"cubic-bezier(.5,0,.75,0)"}).onfinish=finish}
function pickSpyWord(k,w){if(spy.phase!=="locate")return;const item=data.spy[spy.current],tokens=item[0].split(/\s+/),targets=spyTargets(tokens,item),hit=targets.find(x=>x.index===k&&!spy.found.has(x.key));log("answer","spy-"+spy.current,{step:"locate",response:w.textContent,correct:Boolean(hit),found:spy.found.size});if(!hit){spy.locateMiss++;spy.attempts[spy.current]=(spy.attempts[spy.current]||0)+1;w.classList.add("miss");spyShake($("#spyCase"));spySound("bad");renderSpySentence(true);spyStamp("중립 칸","neutral");spyMsg("이 낱말은 바뀌지 않았어요. 이 칸은 아무도 얻지 않고, 코치는 다른 칸을 골라요.","bad");$("#spyCaseKicker").textContent="아무도 얻지 않은 칸";$("#spyCaseTitle").textContent="바뀐 낱말을 함께 확인해요";spyResolve(null);return}spy.found.add(hit.key);spySound("fix");const before=w.textContent,after=before.replace(hit.from,hit.to);w.innerHTML='<span class="spy-old">'+escapeHTML(before)+'</span><span class="spy-new">'+escapeHTML(after)+'</span>';w.classList.add("fixed-static");w.disabled=true;const [x,y]=spyCenter(w);spyBurst(x,y,26,["#16a37f","#ffd45c","#7a4fe0","#42c5d8"],.9);const remaining=targets.length-spy.found.size;if(remaining){spyMsg("찾았어요! 아직 "+remaining+"곳이 남았어요.","ok");return}spyStamp("나의 칸","fix");spyMsg("잘못 읽힌 낱말을 모두 찾았어요. 내가 이 칸을 얻었어요!","ok");$("#spyCaseKicker").textContent="내가 얻은 칸";$("#spyCaseTitle").textContent="문장을 바르게 고쳤어요";spyResolve("player")}
function spyResolve(owner){const i=spy.current;spy.status[i]=owner;spy.used[i]=true;spy.phase=owner?"solved":"neutral";$("#spyPeekPanel").classList.add("hidden");const last=spy.used.every(Boolean);$("#spyNext").textContent=last?"대결 결과 보기":"보드로 돌아가기";$("#spyNext").classList.remove("hidden");$("#spyNext").focus({preventScroll:true})}
function spyCoachChoice(){const open=spy.used.map((used,i)=>used?-1:i).filter(i=>i>=0);if(!open.length)return-1;const lineChoice=owner=>{for(const line of SPY_LINES){const owned=line.filter(i=>spy.status[i]===owner).length,candidates=line.filter(i=>!spy.used[i]);if(owned===2&&candidates.length===1)return candidates[0]}return-1};const winning=lineChoice("coach"),blocking=lineChoice("player");if(winning>=0)return winning;if(blocking>=0)return blocking;if(open.includes(4))return 4;for(const i of[0,2,6,8])if(open.includes(i))return i;return open[0]}
function spyCoachTakeTurn(){const i=spyCoachChoice();if(i<0){spyFinale();return}spy.turn="coach";renderSpyBoard();feedback($("#spyFeedback"),"젤리코치가 다른 빈칸을 고르고 있어요.");setTimeout(()=>{spy.current=i;spy.status[i]="coach";spy.used[i]=true;spy.phase="";spySound("pick");celebrateSpyTile(i)},reduceMotion?80:700)}
function celebrateSpyTile(i){const owner=spy.status[i];renderSpyBoard();const fresh=$('.spy-tile[data-index="'+i+'"]');fresh.classList.add(owner?"just-solved":"just-neutral");const [x,y]=spyCenter(fresh),colors=owner==="player"?["#ffd45c","#16a37f","#42c5d8","#ffffff"]:owner==="coach"?["#7a4fe0","#d8cff5","#ffffff"]:["#a5a6ad","#e7e5e0","#ffffff"];spyBurst(x,y,owner==="player"?40:owner==="coach"?22:12,colors);if(owner==="player")bump($("#spySolved"));const newLines=owner?SPY_LINES.map((l,k)=>({line:k,owner})).filter(entry=>!spy.lines.some(x=>x.line===entry.line&&x.owner===owner)&&SPY_LINES[entry.line].every(n=>spy.status[n]===owner)):[];let delay=300;newLines.forEach(entry=>{setTimeout(()=>{spy.lines.push(entry);renderSpyLines(spy.lines.length-1);updateSpyHud();if(owner==="player")bump($("#spyBingo"));spySound("bingo");SPY_LINES[entry.line].forEach((n,j)=>{setTimeout(()=>{$('.spy-tile[data-index="'+n+'"]')?.classList.add("line-glow")},j*110)});showSpyBanner(owner==="player"?"내가 한 줄!":"코치가 한 줄!")},delay);delay+=650});const played=spy.used.filter(Boolean).length,mine=spy.status.filter(x=>x==="player").length,coach=spy.status.filter(x=>x==="coach").length;if(played===data.spy.length){feedback($("#spyFeedback"),"대결이 끝났어요!","ok");setTimeout(spyFinale,delay+250);return}if(owner==="coach"){spy.turn="player";renderSpyBoard();feedback($("#spyFeedback"),"젤리코치가 다른 칸을 골랐어요. 이제 내 차례예요.");showToast("이제 내 차례예요.")}else{spy.turn="coach";renderSpyBoard();feedback($("#spyFeedback"),owner==="player"?"내 칸을 얻었어요. 이제 젤리코치 차례예요.":"틀린 칸은 중립으로 남았어요. 이제 젤리코치가 다른 칸을 골라요.",owner==="player"?"ok":"");setTimeout(spyCoachTakeTurn,delay+300)}$("#spyFeedback").setAttribute("aria-label","현재 나 "+mine+"칸, 젤리코치 "+coach+"칸, 진행 "+played+"칸")}
function showSpyBanner(text){const b=document.createElement("div");b.className="spy-banner";b.textContent=text;$("#spyGame .spy-board-wrap").append(b);setTimeout(()=>b.remove(),1300)}
function spyFinale(){$("#spyLines").classList.add("all-done");const mine=spy.status.filter(s=>s==="player").length,coach=spy.status.filter(s=>s==="coach").length,neutral=spy.used.filter((used,i)=>used&&!spy.status[i]).length,myLines=spy.lines.filter(x=>x.owner==="player").length,coachLines=spy.lines.filter(x=>x.owner==="coach").length;$("#spyFinaleText").textContent="나는 "+mine+"칸·"+myLines+"줄, 젤리코치는 "+coach+"칸·"+coachLines+"줄, 중립은 "+neutral+"칸이에요.";$("#spyFinale").classList.remove("hidden");spySound("bingo");spyBurst(0,0,160,["#7a4fe0","#42c5d8","#ffd45c","#16a37f","#ff7a8a"],1,true);log("spy_complete","word-spy",{mine,coach,neutral,myLines,coachLines})}
function openSpyPeek(auto){const panel=$("#spyPeekPanel");if(!auto&&!panel.classList.contains("hidden")){panel.classList.add("hidden");$("#spyPeek").textContent="본문 살짝 보기";return}panel.innerHTML=data.paragraphs.map(p=>"<p>"+escapeHTML(p)+"</p>").join("");panel.classList.remove("hidden");$("#spyPeek").textContent="본문 닫기";log("spy_peek","spy-"+spy.current,{auto:Boolean(auto)})}
function spyEnter(){const board=$("#spyBoard");board.classList.remove("intro");void board.offsetWidth;board.classList.add("intro");setTimeout(()=>board.classList.remove("intro"),1100)}
function setupSpy(){["#spyModal","#spyFinale","#spyFx"].forEach(s=>document.body.append($(s)));spy.status=data.spy.map(()=>null);spy.used=data.spy.map(()=>false);spy.attempts=data.spy.map(()=>0);spy.turn="player";try{spy.sound=localStorage.getItem("l16-ondol-careful-reading:spy-sound")!=="off"}catch(e){}const snd=$("#spySound"),syncSound=()=>{snd.textContent=spy.sound?"소리 켬":"소리 끔";snd.setAttribute("aria-pressed",String(spy.sound));snd.setAttribute("aria-label",spy.sound?"효과음 끄기":"효과음 켜기")};syncSound();snd.onclick=()=>{spy.sound=!spy.sound;try{localStorage.setItem("l16-ondol-careful-reading:spy-sound",spy.sound?"on":"off")}catch(e){}syncSound()};$("#spyNext").onclick=()=>closeSpyCase();$("#spyClose").onclick=()=>closeSpyCase();$("#spyModal").onclick=e=>{if(e.target===$("#spyModal"))closeSpyCase()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("#spyModal").classList.contains("hidden"))closeSpyCase()});$("#spyPeek").onclick=()=>openSpyPeek(false);$("#spyFinale").onclick=()=>$("#spyFinale").classList.add("hidden");spyFxSize();window.addEventListener("resize",spyFxSize)}
function renderSpy(){renderSpyBoard()}
function spyOnPage(p){if(p===2)spyEnter();else{closeSpyCase(true);$("#spyFinale").classList.add("hidden")}}
function clearDropTargets(){$$('.energy-bin').forEach(bin=>bin.classList.remove("drop-target"))}
function setupBinDrop(bin,type){bin.ondragover=e=>{e.preventDefault();clearDropTargets();bin.classList.add("drop-target")};bin.ondragleave=e=>{if(!bin.contains(e.relatedTarget))bin.classList.remove("drop-target")};bin.ondrop=e=>{e.preventDefault();clearDropTargets();classify(type)};bin.onclick=e=>{if(e.detail===0)classify(type)}}
function renderBins(){const box=$("#energyBins");box.innerHTML="";Object.entries(data.stages).forEach(([type,stage])=>{const b=document.createElement("button");b.type="button";b.className="energy-bin";b.dataset.type=type;b.setAttribute("aria-label",stage[0]+"에 현재 카드 놓기");b.innerHTML='<span class="sprite"></span><b>'+escapeHTML(stage[0])+'</b><small>'+state.counts[type]+' / '+stage[1]+'</small>';setupBinDrop(b,type);box.append(b)});renderClassifyCard()}
function enableClassifyDrag(){const card=$("#classifyCard"),item=state.classification[classifyIndex];card.draggable=Boolean(item);card.style.pointerEvents=item?"":"none";card.setAttribute("aria-grabbed","false");card.ondragstart=e=>{if(!item){e.preventDefault();return}e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",item.id);card.classList.add("dragging");card.setAttribute("aria-grabbed","true")};card.ondragend=()=>{card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets()};let touchDragging=false;card.onpointerdown=e=>{if(!item||e.pointerType==="mouse")return;touchDragging=true;card.setPointerCapture(e.pointerId);card.classList.add("dragging");card.setAttribute("aria-grabbed","true");e.preventDefault()};card.onpointermove=e=>{if(!touchDragging)return;e.preventDefault();clearDropTargets();const bin=document.elementFromPoint(e.clientX,e.clientY)?.closest(".energy-bin");if(bin)bin.classList.add("drop-target")};const endTouch=e=>{if(!touchDragging)return;touchDragging=false;const bin=document.elementFromPoint(e.clientX,e.clientY)?.closest(".energy-bin");card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets();if(bin)classify(bin.dataset.type)};card.onpointerup=endTouch;card.onpointercancel=()=>{touchDragging=false;card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets()}}
function renderClassifyCard(){const item=state.classification[classifyIndex];$("#classifyCounter").textContent=Math.min(classifyIndex+1,state.classification.length)+" / "+state.classification.length;const card=$("#classifyCard");if(!item){card.textContent="모든 설명 카드를 알맞게 분류했어요!";card.classList.add("complete-card");feedback($("#classifyFeedback"),"아궁이에서 굴뚝까지 각 부분의 역할을 확인했습니다.","ok");enableClassifyDrag();return}card.classList.remove("complete-card");card.innerHTML=(item.cue?'<small>'+escapeHTML(item.cue)+'</small>':"")+escapeHTML(item.text);enableClassifyDrag()}
function classify(type){const item=state.classification[classifyIndex];if(!item)return false;const correct=type===item.type;log("answer","classify-"+item.id,{response:type,correct});if(!correct){feedback($("#classifyFeedback"),"이 부분에서 불, 열, 연기, 돌 가운데 무엇이 움직이거나 따뜻해지는지 다시 살펴보세요.","bad");return false}const card=$("#classifyCard");card.draggable=false;card.style.pointerEvents="none";state.counts[type]++;const bin=$('.energy-bin[data-type="'+type+'"]');$('small',bin).textContent=state.counts[type]+" / "+data.stages[type][1];if(state.counts[type]===data.stages[type][1])bin.classList.add("complete");feedback($("#classifyFeedback"),"맞아요. "+data.stages[type][0]+"에 해당하는 설명입니다.","ok");classifyIndex++;setTimeout(renderClassifyCard,450);return true}
function getVerifyCoachPrompts(){
  if(verifyIndex===0)return[
    {tag:"본문 확인",q:"본문의 내용은 어떤 것이었나요?",options:["온돌의 구조와 방바닥이 따뜻해지는 과정","옛날 집의 지붕을 만드는 과정"],correct:0},
    {tag:"묻는 내용",q:"무엇을 연결한 보기를 고르라고 했나요?",options:["온돌의 부분과 하는 일","계절과 입는 옷"],correct:0},
    {tag:"답의 범위",q:"답은 몇 개 골라야 하나요?",options:["해당하는 것을 모두","가장 알맞은 것 하나"],correct:0},
    {tag:"본문과 비교",q:"굴뚝이 하는 일은 무엇이었나요?",options:["연기를 밖으로 내보낸다","불을 피운다"],correct:0}
  ];
  if(verifyIndex===1)return[
    {tag:"대상",q:"언제 일어나는 일을 묻고 있나요?",options:["아궁이에 불을 피운 뒤","비가 내린 뒤"],correct:0},
    {tag:"묻는 내용",q:"무엇을 고르라고 했나요?",options:["불을 피운 뒤 일어나는 일","온돌을 만든 사람의 이름"],correct:0},
    {tag:"답의 범위",q:"답은 몇 개 골라야 하나요?",options:["해당하는 것을 모두","가장 알맞은 것 하나"],correct:0},
    {tag:"본문과 비교",q:"뜨거운 공기가 지나면 무엇이 데워지나요?",options:["구들장과 방바닥","굴뚝과 지붕"],correct:0}
  ];
  return[
    {tag:"대상",q:"무엇에 관한 문제인가요?",options:["온돌의 특징과 장점","여름철 더위를 식히는 방법"],correct:0},
    {tag:"묻는 내용",q:"어떤 설명을 고르라고 했나요?",options:["본문에서 알 수 있는 온돌의 특징","본문에 없는 사람의 이름"],correct:0},
    {tag:"답의 범위",q:"답은 몇 개 골라야 하나요?",options:["해당하는 것을 모두","가장 알맞은 것 하나"],correct:0},
    {tag:"본문과 비교",q:"온돌방에 앉으면 몸은 어떻게 느껴지나요?",options:["몸 아래쪽은 따뜻하고 머리 쪽은 비교적 서늘하다","머리만 뜨겁고 몸 아래쪽은 차갑다"],correct:0}
  ]
}
function renderVerifyCoach(){const prompts=getVerifyCoachPrompts();if(verifyCoachStep>=prompts.length){$("#verifyStep").textContent="준비";$("#verifyPrompt").textContent="확인했어요. 왼쪽에서 답을 모두 고른 뒤 확인해요.";$("#verifyCoachChoices").innerHTML="";$$('#verifyOptions input').forEach(x=>x.disabled=false);$("#verifyCheck").disabled=false;feedback($("#verifyFeedback"),"문제에서 묻는 내용과 답의 범위를 확인하고, 보기를 본문과 비교했어요. 답을 골라 보세요.","ok");return}const p=prompts[verifyCoachStep];$("#verifyStep").textContent=(verifyCoachStep+1)+" / "+prompts.length;$("#verifyPrompt").innerHTML="<small>"+p.tag+"</small><strong>"+p.q+"</strong>";$("#verifyCoachChoices").innerHTML="";p.options.forEach((o,i)=>{const b=document.createElement("button");b.type="button";b.textContent=o;b.onclick=()=>{const correct=i===p.correct;log("answer","verify-"+verifyIndex+"-precheck-"+verifyCoachStep,{response:i,correct});if(!correct){showToast("문제와 보기를 다시 꼼꼼하게 읽어 보세요.");return}verifyCoachStep++;renderVerifyCoach()};$("#verifyCoachChoices").append(b)})}
function renderVerifyQuestion(){const v=data.verify[verifyIndex];verifyCoachStep=0;$("#verifyQuestionCount").textContent="문제 "+(verifyIndex+1)+" / "+data.verify.length;$("#verifyQuestion").textContent=v[0];$("#verifyOptions").innerHTML="";v[1].forEach((o,i)=>{const label=document.createElement("label");label.innerHTML='<input type="checkbox" value="'+i+'" disabled><span>'+escapeHTML(o)+'</span>';$("#verifyOptions").append(label)});$("#verifyCheck").classList.remove("hidden");$("#verifyCheck").disabled=true;$("#verifyNext").classList.add("hidden");feedback($("#verifyFeedback"),"먼저 오른쪽에서 질문을 확인해요.");renderVerifyCoach()}
function checkVerify(){const v=data.verify[verifyIndex],picked=$$('#verifyOptions input:checked').map(x=>Number(x.value)).sort(),answer=v[2].slice().sort(),correct=JSON.stringify(picked)===JSON.stringify(answer);log("answer","verify-main-"+verifyIndex,{response:picked,correct});if(!correct){feedback($("#verifyFeedback"),"아직 정답이 아니에요. 고른 보기와 빠뜨린 보기를 다시 살펴보세요.","bad");return}$$('#verifyOptions input').forEach(x=>x.disabled=true);$("#verifyCheck").classList.add("hidden");const done=(verifyIndex+1)+" / "+data.verify.length+" 완료";feedback($("#verifyFeedback"),"정답이에요! "+done+". "+v[3],"ok");if(verifyIndex<data.verify.length-1){$("#verifyNext").textContent="다음 문제";$("#verifyNext").classList.remove("hidden");$("#verifyStep").textContent="정답";$("#verifyPrompt").textContent="맞혔어요. 다음 문제에서도 묻는 말과 보기의 표현을 확인해요.";$("#verifyCoachChoices").innerHTML=""}else{$("#verifyStep").textContent="완료";$("#verifyPrompt").textContent="정답이에요. 세 문제를 모두 정확하게 풀었어요!";$("#verifyCoachChoices").innerHTML="";showToast("3문제를 모두 마쳤어요!")}}
function setupVerify(){$("#verifyCheck").onclick=checkVerify;$("#verifyNext").onclick=()=>{verifyIndex++;renderVerifyQuestion()};renderVerifyQuestion()}function renderTransfer(){const t=data.transfer[transferIndex];$("#transferLabel").textContent=t[0];$("#transferCounter").textContent=(transferIndex+1)+" / "+data.transfer.length;$("#transferPassage").textContent=t[1];$("#transferQuestion").textContent=t[2];$("#transferOptions").innerHTML="";t[3].forEach((o,i)=>{const b=document.createElement("button");b.type="button";b.textContent=String.fromCharCode(65+i)+"  "+o;b.onclick=()=>answerTransfer(i,b);$("#transferOptions").append(b)});feedback($("#transferFeedback"),"답을 고르면 근거를 확인할 수 있어요.");$("#transferNext").classList.add("hidden")}
function answerTransfer(choice,button){const t=data.transfer[transferIndex],correct=choice===t[4];$$('#transferOptions button').forEach(b=>b.classList.remove("correct","wrong"));button.classList.add(correct?"correct":"wrong");log("answer","transfer-"+transferIndex,{response:choice,correct});if(!correct){feedback($("#transferFeedback"),"새 글의 표현을 다시 확인하고 다른 답을 골라 보세요.","bad");return}feedback($("#transferFeedback"),t[5],"ok");$("#transferNext").classList.remove("hidden")}
function setupTransfer(){$("#transferNext").onclick=()=>{if(transferIndex<data.transfer.length-1){transferIndex++;renderTransfer()}else{feedback($("#transferFeedback"),"세 가지 전이 활동을 모두 마쳤어요.","ok");$("#transferNext").classList.add("hidden")}}}
function setupReflection(){$$('#reflectionChoices button').forEach(b=>b.onclick=()=>{$$('#reflectionChoices button').forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.reflection=b.textContent;state.reflectionStrategy=b.dataset.strategy;$("#reflectionStrategyText").textContent=state.reflectionStrategy;$("#reflectionStrategy").classList.remove("hidden");$("#finishLesson").classList.remove("hidden")});$("#finishLesson").onclick=finish}
function finish(){if(!state.reflection&&page===6){showToast("오늘 실수한 것과 가장 가까운 보기를 골라 주세요.");return}const record={level,mistake:state.reflection,strategy:state.reflectionStrategy,finishedAt:new Date().toISOString()};localStorage.setItem("l16-ondol-careful-reading:complete:"+level,JSON.stringify(record));$("#completionCard").classList.remove("hidden");$("#finishLesson").classList.add("hidden");$("#completionSignal").hidden=false;log("lesson_complete","lesson",record);showToast("수업을 마쳤어요!")}
function boot(){setupLevel();setupIntro();setupNavigation();setupAnnotationDock();renderPassage();setupVocab();setupPrediction();setupReadingFlow();setupQuestions();setupSpy();setupVerify();setupTransfer();setupReflection();renderPrediction();renderQuestion();renderSpy();renderBins();renderTransfer();showPage(0)}
document.addEventListener("DOMContentLoaded",boot);
})();
