(()=>{"use strict";
const LID=document.documentElement.dataset.lessonId||"lesson",SID=document.documentElement.dataset.session||"session01",SK=LID+":"+SID+":";
const data=window.LESSON_DATA,level=window.LESSON_LEVEL,pages=[...document.querySelectorAll(".page")];let page=0,predictIndex=0,questionIndex=0,questionAttempts=0,spyIndex=0,classifyIndex=0,verifyIndex=0,verifyCoachStep=0,transferIndex=0,toastTimer;
if(data.counsel){data.stages=data.stages||{};data.classification=data.classification||[]}
if(data.organizer){data.stages={};orgSlots(data.organizer).forEach(x=>data.stages[x.id]=[x.name,1,""])}
const CAT_CODE={"역사":"history","지리":"geography","과학":"science","사회":"society","경제":"economy","생활":"life","문화":"culture"},ERA_CODE={"선사 탐구":"prehistory","구석기":"paleolithic","신석기":"neolithic","선사 문화":"prehistoric-culture","청동기":"bronze-age","고구려":"goguryeo","신라":"silla","고려":"goryeo","조선":"joseon"};
const CONCEPT=new Set([...(data.hanjaTerms||[]).map(v=>v[0]),...(data.conceptVocab||[])]);
const TERMS=(()=>{const seen=new Set(),out=[];[...(data.vocab||[]),...(data.hanjaTerms||[])].forEach(v=>{if(!seen.has(v[0])){seen.add(v[0]);out.push(v)}});return out})();
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={classification:shuffle(data.classification.slice()),counts:Object.fromEntries(Object.keys(data.stages).map(k=>[k,0])),reflection:"",reflectionStrategy:""};
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function log(action,itemId,extra={}){const ds=(pages[page]&&pages[page].dataset)||{},detail={type:action,lessonId:LID,sessionId:SID,lessonVersion:document.documentElement.dataset.lessonVersion||"1.0.0",level,...(data.meta&&data.meta.category?{category:CAT_CODE[data.meta.category]||data.meta.category}:{}),...(data.meta&&data.meta.era?{era:ERA_CODE[data.meta.era]||data.meta.era}:{}),activityId:extra.activityId||ds.activityId||"",measureId:ds.measureId||"",itemId,timestamp:new Date().toISOString(),...extra};if(extra.attempt!=null&&detail.attemptNo==null)detail.attemptNo=extra.attempt;delete detail.attempt;window.dispatchEvent(new CustomEvent("oncuvate:log",{detail}))}
/* 도움 수준(규격 A1~A4): 도움을 주는 요소에 data-track="hint"+data-help-level. 문항이 끝나면 정확성 3값과 가장 강한 도움을 기록 */
const ASSIST={},HELP_RANK={A1:1,A2:2,A3:3,A4:4},HELP_TAG={A1:"다시 보기",A2:"힌트",A3:"함께 하기",A4:"정답 보기"};
function assistItem(id){return ASSIST[id]||(ASSIST[id]={tries:0,help:0,done:false})}
function noteHelp(itemId,lvl,type,trigger){const a=assistItem(itemId);if(lvl)a.help=Math.max(a.help,HELP_RANK[lvl]);log("help",itemId,{...(lvl?{helpLevel:lvl}:{}),helpType:type,helpTrigger:trigger||"child-request"})}
function helpButton(label,lvl,type,itemId,onUse,opt={}){const b=document.createElement("button");b.type="button";b.className="help-btn lv-"+lvl.toLowerCase();b.dataset.track="hint";b.dataset.helpLevel=lvl;b.dataset.helpType=type;b.dataset.helpTrigger=opt.trigger||"child-request";b.innerHTML="<i>"+HELP_TAG[lvl]+"</i>"+escapeHTML(label);b.onclick=()=>{if(b.dataset.used&&!opt.repeat)return;if(!opt.repeat){b.dataset.used="1";b.disabled=true}noteHelp(itemId,lvl,type,opt.trigger);onUse(b)};return b}
function helpBar(id,after){let bar=$("#"+id);if(!bar){bar=document.createElement("div");bar.id=id;bar.className="help-bar";after.after(bar)}bar.innerHTML="";return bar}
function itemResult(itemId,extra={}){const a=assistItem(itemId);if(a.done)return;a.done=true;const r={accuracy:extra.accuracy||(a.help>=2?"support":(a.tries>1?"self-corrected":"accurate")),attemptNo:Math.max(1,a.tries),...extra};if(a.help)r.helpLevel="A"+a.help;log("item-result",itemId,r)}
function showToast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove("show"),2200)}
function feedback(el,message,type){el.textContent=message;el.classList.remove("ok","bad");if(type)el.classList.add(type)}
function normalize(v){return String(v||"").replace(/[\s.,!?·'\"“”‘’]/g,"")}
function normalizeShortAnswer(v){return normalize(v).replace(/(입니다|이에요|예요|이다)$/,"")}
function showPage(next){page=Math.max(0,Math.min(pages.length-1,next));pages.forEach((p,i)=>p.classList.toggle("active",i===page));$$('.step-link').forEach((b,i)=>{b.classList.toggle("active",i===page);b.toggleAttribute("aria-current",i===page)});$$('.step-dots button').forEach((b,i)=>b.classList.toggle("active",i===page));$("#progressBar").style.width=((page+1)/pages.length*100)+"%";$("#backButton").disabled=page===0;$("#nextButton").textContent="다음";$("#nextButton").classList.toggle("hidden",page===pages.length-1);$("#stage").scrollTop=0;const dock=$("#annotationDock"),toolbar=$("#annotationToolbar"),dockToggle=$("#annotationDockToggle");if(dock){dock.classList.toggle("hidden",page!==1);if(page!==1){toolbar.classList.add("hidden");dockToggle.setAttribute("aria-expanded","false")}}log("page_view","page-"+(page+1));spyOnPage(page);window.dispatchEvent(new Event("resize"))}
function setupAnnotationDock(){const toggle=$("#annotationDockToggle"),toolbar=$("#annotationToolbar");toggle.onclick=()=>{const open=toolbar.classList.toggle("hidden")===false;toggle.setAttribute("aria-expanded",String(open));log("annotation_panel",open?"open":"close")}}
function setupNavigation(){const dots=$("#stepDots");pages.forEach((_,i)=>{const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",(i+1)+"단계로 이동");b.onclick=()=>showPage(i);dots.append(b)});$$('[data-go]').forEach(b=>b.onclick=()=>showPage(Number(b.dataset.go)));$("#backButton").onclick=()=>showPage(page-1);$("#nextButton").onclick=()=>{if(page===pages.length-1){finish()}else showPage(page+1)};$("#menuButton").onclick=()=>{const s=$("#sidebar"),open=!s.classList.contains("open");s.classList.toggle("open",open);$("#menuButton").textContent=open?"◀":"▶";$("#menuButton").setAttribute("aria-expanded",String(open))};$("#helpButton").onclick=()=>{noteHelp("page-"+(page+1),null,"child-request");showHelpToast()};function showHelpToast(){showToast(["제목과 그림을 보고 낱말을 예상해요.","본문을 가린 뒤 단어나 짧은 구로 기억을 확인해요.","숫자 타일을 골라 문장이 본문과 같은지 O·X로 판정하고, 다르면 틀린 낱말을 눌러요.","카드의 설명을 끝까지 읽고 글자를 만든 방법과 연결해요.","대상과 개수를 먼저 확인한 뒤 답을 골라요.","쉬운 말과 반대 문장을 오늘 배운 낱말로 바꾸고, 뽑은 낱말로 문장을 만들어요.","오늘 실수한 것을 고르고, 다음에 사용할 방법을 확인해요."][page])}}
function setupIntro(){/* 공용 도입 화면(intro/oncuvate-intro.js) — 매번 띄운다. 로컬 ?intro=0 만 건너뜀 */const gate=$("#introGate"),lg=$("#levelGate"),de=document.documentElement.dataset,params=new URLSearchParams(location.search),m=(data&&data.meta)||{};if(gate)gate.classList.add("hidden");const requested=de.fixedLevel||params.get("level"),picked=requested==="steady"||requested==="deep",begin=()=>{if(!picked&&lg)lg.classList.remove("hidden")};const PASS="onq-intro-pass:"+location.pathname;$$("[data-level-choice]").forEach(b=>b.addEventListener("click",()=>{try{sessionStorage.setItem(PASS,"1")}catch(e){}}));let pass=false;try{pass=sessionStorage.getItem(PASS)==="1";sessionStorage.removeItem(PASS)}catch(e){}if(!window.ONQ_INTRO||pass){begin();return}if(lg)lg.classList.add("hidden");const strip=v=>String(v||"").replace(/<br\s*\/?>/gi," ").replace(/<[^>]+>/g,"").replace(/\s+/g," ").trim(),h2=gate&&$("h2",gate),sub=m.introSub||(h2?h2.innerHTML:""),first=strip(String(sub).split(/<br\s*\/?>/i)[0]);let goal=first.replace(/보고$/,"봐요.").replace(/하고$/,"해요.");if(goal===first)goal=strip(sub)||strip(data.intro);const tag={steady:"차근차근",deep:"깊이"}[de.fixedLevel],num=parseInt(String(de.session||"").replace(/\D/g,""),10)||1,rv=$("#introReview"),o={series:(m.brand||"비문학 꼼꼼 읽기")+(tag?" · "+tag:""),session:num+"회차",title:m.title||document.title.split(" — ")[0]||data.title,goal,onStart(mode){begin();if(mode==="review"&&rv)rv.click()}};if(m.cover)o.image=m.cover;if(rv)o.review={label:"복습하기"};ONQ_INTRO.mount(o);const ow=document.querySelector(".oi-wrap");if(ow)ow.style.zIndex="100010"/* 이 시리즈 옆 메뉴(z 58) 위로 */}
function setupLevel(){const FIXED=document.documentElement.dataset.fixedLevel;const requested=FIXED||new URLSearchParams(location.search).get("level");$("#levelGate").classList.toggle("hidden",requested==="steady"||requested==="deep");if(FIXED){const c=$("#changeLevel");if(c)c.hidden=true}$$('[data-level-choice]').forEach(b=>b.onclick=()=>location.href=location.pathname.split("/").pop()+"?level="+b.dataset.levelChoice);$("#changeLevel").onclick=()=>$("#levelGate").classList.remove("hidden");$("#levelPill").textContent=data.level+" · "+data.label;$("#readingLevel").textContent=data.label;$("#topTitle").textContent=data.title;$("#articleTitle").textContent=data.title}
function escapeHTML(v){const e=document.createElement("div");e.textContent=v;return e.innerHTML}
function renderPassage(){const gates=data.gates||[];let html=data.paragraphs.map((p,i)=>{let t=escapeHTML(p);gates.filter(g=>g.after===i).forEach((g,k)=>{const e=escapeHTML(g.ev);t=t.replace(e,'<span class="ev" data-ev="'+gates.indexOf(g)+'">'+e+'</span>')});return '<p data-paragraph="'+i+'">'+t+'</p>'}).join("");TERMS.forEach((v,i)=>{const word=escapeHTML(v[0]),hj=CONCEPT.has(v[0])&&/[\u4e00-\u9fff]/.test(v[1]||""),button='<button class="vocab-word'+(hj?' hanja-term':'')+'" type="button" data-vocab="'+i+'">'+word+'</button>';const esc=word.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),alone=new RegExp('(^|>)([^<]*?)(?<![\uac00-\ud7a3])'+esc);html=alone.test(html)?html.replace(alone,(m,a,b)=>a+b+button):html.replace(new RegExp('(^|>)([^<]*?)'+esc),(m,a,b)=>a+b+button)});$("#passage").innerHTML=html;$$('[data-vocab]').forEach(b=>b.onclick=()=>openVocab(Number(b.dataset.vocab)));
  const cards=data.cards||{};Object.keys(cards).forEach(pi=>{const para=$('#passage p[data-paragraph="'+pi+'"]');if(!para)return;const box=document.createElement("div");box.className="glyph-cards";box.innerHTML='<small>'+escapeHTML(data.cardsLabel||"낱말 카드 · 먼저 떠올려 보고 눌러요")+'</small>';cards[pi].forEach(([g,ans])=>{const b=document.createElement("button");b.type="button";b.className="glyph-card";b.innerHTML='<b>'+escapeHTML(g)+'</b><span>'+escapeHTML(data.cardsPrompt||"무엇일까?")+'</span>';b.onclick=()=>{const open=!b.classList.contains("open");b.classList.toggle("open",open);b.querySelector("span").textContent=open?ans:(data.cardsPrompt||"무엇일까?");if(open)log("card_flip","card-"+g,{glyph:g})};box.append(b)});para.after(box)});
  if(data.gateMode==="after"||data.gateMode==="para"){$("#readingDone").classList.remove("hidden");const cp=$("#readingCoachPanel .coach-prompt");if(cp)cp.innerHTML="<strong>끝까지 천천히 읽어.</strong><p>어려운 낱말은 눌러 확인해. 다 읽으면 본문을 가리고 확인 문제가 나와.</p>";if(data.gateMode==="para")paraShow(0);return}
  gates.forEach((g,gi)=>{const para=$('#passage p[data-paragraph="'+g.after+'"]');let anchor=para;while(anchor.nextElementSibling&&anchor.nextElementSibling.classList.contains("glyph-cards"))anchor=anchor.nextElementSibling;const box=document.createElement("div");box.className="p-gate";box.dataset.gate=gi;box.innerHTML='<strong><i>확인</i>'+escapeHTML(g.q)+'</strong><div class="p-gate-opts"></div><p class="p-gate-msg" role="status"></p>';const id="gate-"+(gi+1),opts=$(".p-gate-opts",box),msg=$(".p-gate-msg",box);
    g.opts.forEach((o,oi)=>{const b=document.createElement("button");b.type="button";b.textContent=o;b.dataset.track="answer";b.dataset.correct=String(oi===g.a);b.onclick=()=>{const a=assistItem(id);a.tries++;const ok=oi===g.a;log("answer",id,{response:o,correct:ok,attempt:a.tries,activityId:"careful-reading"});
      if(!ok){b.classList.add("wrong");b.disabled=true;msg.textContent="그 문단을 끝까지 다시 읽고 골라 봐요.";const bar=helpBar("gateHelp"+gi,msg);bar.append(helpButton("근거 문장 반짝이기","A2","evidence-highlight",id,()=>$$('#passage .ev[data-ev="'+gi+'"]').forEach(x=>x.classList.add("evidence"))));if(a.tries>=2)bar.append(helpButton("정답 보기","A4","answer-reveal",id,()=>$$("button",opts)[g.a].classList.add("reveal")));return}
      b.classList.add("correct");$$("button",opts).forEach(x=>x.disabled=true);helpBar("gateHelp"+gi,msg);coachFace(5);msg.textContent=a.help>=2?"맞아요. 도움을 잘 썼어요.":a.tries>1?"스스로 고쳤어요!":"맞아요!";itemResult(id,{activityId:"careful-reading"});box.classList.add("passed");unlockParagraph(g.after+1)};opts.append(b)});
    anchor.after(box)});
  unlockParagraph(0)}
let gateQuizItem=null;
function startGateQuiz(list,onFinish,lastLabel){const gates=data.gates,panel=$("#questionPanel"),hideSel=[".memory-chat-heading","#questionChat","#questionForm"];hideSel.forEach(x=>{const e=$(x,panel);if(e)e.classList.add("hidden")});
  let box=$("#gateQuiz");if(!box){box=document.createElement("div");box.id="gateQuiz";box.className="gate-quiz";$(".coach-title",panel).after(box)}let k=0;
  const show=()=>{const gi=list[k],g=gates[gi],id="gate-"+(gi+1),a=assistItem(id);gateQuizItem=id;$("#questionCounter").textContent=(data.gateMode==="para"?"단락 ":"확인 ")+(gi+1)+" / "+gates.length;coachFace(4);
    box.innerHTML='<p class="gq-kicker">'+(data.gateMode==="para"?"단락을 가렸어요. 방금 읽은 내용을 떠올려 골라요.":"본문을 가렸어요. 읽은 내용을 떠올려 골라요.")+'</p><strong class="gq-q">'+escapeHTML(g.q)+'</strong><div class="p-gate-opts"></div><p class="p-gate-msg" role="status"></p><button class="primary hidden gq-next" type="button"></button>';
    const opts=$(".p-gate-opts",box),msg=$(".p-gate-msg",box),next=$(".gq-next",box);
    g.opts.forEach((o,oi)=>{const b=document.createElement("button");b.type="button";b.textContent=o;b.dataset.track="answer";b.dataset.correct=String(oi===g.a);b.onclick=()=>{a.tries++;const ok=oi===g.a;log("answer",id,{response:o,correct:ok,attempt:a.tries,activityId:"careful-reading"});
      if(!ok){b.classList.add("wrong");b.disabled=true;coachFace(4);msg.textContent=a.tries===1?"다시 떠올려 봐요. 가린 글을 다시 봐도 괜찮아요.":"한 번 더 해 봐요. 아래 도움을 써도 괜찮아요.";const bar=helpBar("gqHelp",msg);setTimeout(()=>bar.scrollIntoView({block:"nearest",behavior:"smooth"}),30);
        bar.append(helpButton("근거 문장 보기","A2","evidence-sentence",id,()=>{msg.textContent="글에는 이렇게 쓰여 있어요: “"+g.ev+"”"}));
        if(a.tries>=2)bar.append(helpButton("정답 보기","A4","answer-reveal",id,()=>$$("button",opts)[g.a].classList.add("reveal")));return}
      b.classList.add("correct");$$("button",opts).forEach(x=>x.disabled=true);helpBar("gqHelp",msg);coachFace(5);msg.textContent=a.help>=2?"맞아요. 도움을 잘 썼어요.":a.tries>1?"스스로 고쳤어요!":"맞아요!";itemResult(id,{activityId:"careful-reading"});
      next.textContent=k<list.length-1?"다음 확인 문제":lastLabel;next.classList.remove("hidden");setTimeout(()=>next.scrollIntoView({block:"nearest",behavior:"smooth"}),30);next.focus({preventScroll:true})};opts.append(b)});
    next.onclick=()=>{if(k<list.length-1){k++;show()}else{gateQuizItem=null;box.remove();if(lastLabel==="기억 질문으로"){hideSel.forEach(x=>{const e=$(x,panel);if(e)e.classList.remove("hidden")});$("#questionCounter").textContent=(questionIndex+1)+" / "+data.questions.length}onFinish()}}};
  show()}
let paraIdx=0;
function paraShow(i){setTimeout(()=>showParaPic(i),0);paraIdx=i;const paper=$("#readingPaper");paper.classList.remove("covered","peek");$("#passageToggle").textContent="본문 다시 보기";$("#passageCover").classList.add("hidden");$("#readingCoachPanel").classList.remove("hidden");$("#questionPanel").classList.add("hidden");
  $$("#passage p[data-paragraph]").forEach(p=>p.classList.toggle("p-locked",Number(p.dataset.paragraph)!==i));$$("#passage .glyph-cards").forEach(c=>c.classList.toggle("p-locked",Number(c.previousElementSibling&&c.previousElementSibling.dataset.paragraph)!==i));
  const n=data.paragraphs.length,d=$("#readingDone");d.classList.remove("hidden");d.textContent="이 단락 다 읽었어요 ("+(i+1)+"/"+n+")";
  const cp=$("#readingCoachPanel .coach-prompt");if(cp)cp.innerHTML="<strong>"+(i+1)+"번째 단락을 읽어요.</strong><p>천천히 끝까지 읽고 버튼을 눌러. 단락을 가리면 문제 하나가 나와.</p>";$("#passage").scrollTop=0;coachFace(4)}
function paraDone(){const paper=$("#readingPaper"),n=data.paragraphs.length,last=paraIdx>=n-1;paper.classList.add("covered");paper.classList.remove("peek");$("#passageCover").classList.remove("hidden");$("#readingDone").classList.add("hidden");$("#readingCoachPanel").classList.add("hidden");$("#questionPanel").classList.remove("hidden");if(document.body.classList.contains("kid-skin"))kidFitCover();log("paragraph_read","para-"+(paraIdx+1),{activityId:"careful-reading"});const cs=$("#passageCover strong");if(cs)cs.textContent="단락을 가렸어요.";
  const finish=()=>{if(!last){paraShow(paraIdx+1);return}const cs2=$("#passageCover strong");if(cs2)cs2.textContent="본문을 가렸어요.";$$("#passage p[data-paragraph], #passage .glyph-cards").forEach(e=>e.classList.remove("p-locked"));log("reading_complete","reading-done",{level});$("#questionInput").focus()};
  const gi=(data.gates||[]).findIndex(g=>g.after===paraIdx);if(gi<0){finish();return}startGateQuiz([gi],finish,last?"기억 질문으로":"다음 단락 읽기")}
function unlockParagraph(n){const gates=data.gates||[],paras=$$("#passage p[data-paragraph]");let shownTo=n;const g=gates.find(x=>x.after>=n);const stop=g?g.after:paras.length-1;
  paras.forEach((p,i)=>p.classList.toggle("p-locked",i>stop));$$("#passage .glyph-cards").forEach(c=>c.classList.toggle("p-locked",Number(c.previousElementSibling&&c.previousElementSibling.dataset.paragraph)>stop));
  $$("#passage .p-gate").forEach(b=>{const gg=gates[b.dataset.gate];b.classList.toggle("p-locked",gg.after>stop)});
  const allOpen=!gates.some(x=>!$('#passage .p-gate[data-gate="'+gates.indexOf(x)+'"]').classList.contains("passed"))&&stop>=paras.length-1;$("#readingDone").classList.toggle("hidden",!allOpen);if(allOpen)showToast("끝까지 읽었어요. ‘다 읽었어요’를 눌러요.");
  if(n>0){const first=paras[n];if(first){const box=$("#passage");box.scrollTo({top:first.offsetTop-box.offsetTop-12,behavior:"smooth"})}}}
function openVocab(i){const v=TERMS[i];if(!v)return;const raw=v[1]||"",parts=raw.split("·"),hj=parts[0].trim(),gloss=parts.slice(1).join("·").trim();$("#vocabTitle").textContent=v[0];$("#vocabHanja").innerHTML=/[\u4e00-\u9fff]/.test(hj)?"<b>"+escapeHTML(hj)+"</b>"+(gloss?"<span>"+escapeHTML(gloss)+"</span>":"")+(v[4]?"<em>"+escapeHTML(v[4])+"</em>":""):"<span>"+escapeHTML(raw)+"</span>";$("#vocabMeaning").textContent=v[2];$("#vocabExample").textContent=v[3];{let pic=$("#vocabPic");if(!pic){pic=document.createElement("img");pic.id="vocabPic";pic.alt="";pic.className="vocab-pic";$("#vocabHanja").after(pic)}const src=(data.pictures&&data.pictures.words||{})[v[0]];pic.hidden=!src;if(src)pic.src=src}const added=wordbookAdd(v);$("#vocabSave").textContent=added?"✓ 단어장에 담았어요":"✓ 단어장에 있어요";$("#vocabDialog").classList.remove("hidden");log("vocab_open","vocab-"+i,{word:v[0]});if(added)log("vocab_save","vocab-"+i,{word:v[0],auto:true})}
function setupVocab(){$("#vocabClose").onclick=()=>$("#vocabDialog").classList.add("hidden");$("#vocabDialog").onclick=e=>{if(e.target===$("#vocabDialog"))$("#vocabDialog").classList.add("hidden")};$("#vocabSave").onclick=()=>{$("#vocabDialog").classList.add("hidden");openWordbook()};wordbookCount()}
function renderPrediction(){const item=data.prediction[predictIndex];$("#predictCounter").textContent=(predictIndex+1)+" / "+data.prediction.length;$("#predictProgress").style.width=((predictIndex+1)/data.prediction.length*100)+"%";$("#predictWord").textContent=item[0];feedback($("#predictFeedback"),"낱말을 살펴보고 판단해 보세요.");$("#predictNext").classList.add("hidden");$$('[data-predict-answer]').forEach(b=>{b.disabled=false;b.classList.remove("correct","wrong")})}
function setupPrediction(){$$('[data-predict-answer]').forEach(b=>b.onclick=()=>{const chosen=b.dataset.predictAnswer==="yes",correct=data.prediction[predictIndex][1];$$('[data-predict-answer]').forEach(x=>x.disabled=true);feedback($("#predictFeedback"),chosen===correct?(correct?"맞아요. 본문에서 이 낱말을 확인해 봐요.":"맞아요. 이 낱말은 주제와 관련이 없어요."):"그림과 제목의 주제를 다시 살펴보세요.",chosen===correct?"ok":"bad");log("answer","predict-"+predictIndex,{response:String(chosen),correct:chosen===correct});itemResult("predict-"+predictIndex,{accuracy:"notApplicable"});$("#predictNext").classList.remove("hidden")});$("#predictNext").onclick=()=>{if(predictIndex<data.prediction.length-1){predictIndex++;renderPrediction()}else{feedback($("#predictFeedback"),"예측을 마쳤어요. 이제 본문에서 확인해 봐요!","ok");$("#predictNext").classList.add("hidden")}}}
function addMemoryMessage(role,text,response=false){const row=document.createElement("div");row.className="memory-message "+role+(response?" memory-response":"");const label=document.createElement("span"),bubble=document.createElement("p");label.textContent=role==="coach"?"젤리코치":"나";bubble.textContent=text;row.append(label,bubble);$("#questionChat").append(row);$("#questionChat").scrollTop=$("#questionChat").scrollHeight}
function clearMemoryResponses(){$$(".memory-response",$("#questionChat")).forEach(x=>x.remove())}
function renderQuestion(){const q=data.questions[questionIndex];questionAttempts=0;$("#questionCounter").textContent=(questionIndex+1)+" / "+data.questions.length;$("#questionChat").innerHTML="";addMemoryMessage("coach",q[0]);const input=$("#questionInput"),submit=$("#questionSubmit"),form=$("#questionForm"),next=$("#questionNext");input.value="";input.disabled=false;submit.disabled=false;form.classList.remove("hidden");next.classList.add("hidden");next.textContent=questionIndex===data.questions.length-1?"확인 마치기":"다음 질문"}
function submitMemoryAnswer(){const q=data.questions[questionIndex],input=$("#questionInput"),raw=input.value.trim(),id="reading-q"+questionIndex,a=assistItem(id);if(!raw){clearMemoryResponses();addMemoryMessage("coach","단어나 짧은 구로 답해 줘.",true);input.focus();return}questionAttempts++;a.tries++;const response=normalizeShortAnswer(raw),correct=q[1].some(x=>normalizeShortAnswer(x)===response);log("answer",id,{response:raw,correct,attempt:questionAttempts});clearMemoryResponses();addMemoryMessage("user",raw,true);
  if(!correct){coachFace(4);addMemoryMessage("coach",questionAttempts===1?"아직 아니야. 천천히 다시 떠올려 봐.":"한 번 더 해 보자. 아래 도움을 써도 괜찮아.",true);input.select();
    const bar=helpBar("qHelp",$("#questionForm"));
    bar.append(helpButton("실마리 보기","A2","clue",id,()=>addMemoryMessage("coach","실마리: "+q[3],true)));
    if(questionAttempts>=2)bar.append(helpButton("정답 보고 따라 쓰기","A4","answer-reveal",id,()=>addMemoryMessage("coach","정답은 ‘"+q[1][0]+"’이야. 그대로 써서 보내 보자.",true)));return}
  helpBar("qHelp",$("#questionForm"));itemResult(id);coachFace(5);addMemoryMessage("coach",(a.help>=2?"맞아. 도움을 잘 썼어. ":questionAttempts>1?"스스로 고쳤어! ":"")+q[2],true);input.disabled=true;$("#questionSubmit").disabled=true;$("#questionNext").classList.remove("hidden")}
function setupReadingFlow(){const paper=$("#readingPaper"),cover=$("#passageCover"),panel=$("#questionPanel"),coach=$("#readingCoachPanel"),done=$("#readingDone"),toggle=$("#passageToggle");done.onclick=()=>{if(data.gateMode==="para"){paraDone();return}done.classList.add("hidden");paper.classList.add("covered");cover.classList.remove("hidden");coach.classList.add("hidden");panel.classList.remove("hidden");log("reading_complete","reading-done",{level});coachFace(4);if(document.body.classList.contains("kid-skin"))kidFitCover();if(data.gateMode==="after"&&(data.gates||[]).length)startGateQuiz(data.gates.map((_,i)=>i),()=>$("#questionInput").focus(),"기억 질문으로");else $("#questionInput").focus();window.dispatchEvent(new Event("resize"))};toggle.dataset.track="hint";toggle.dataset.helpLevel="A1";toggle.dataset.helpType="reread";toggle.onclick=()=>{const peek=paper.classList.toggle("peek");toggle.textContent=peek?"본문 가리기":"본문 다시 보기";if(peek)noteHelp(gateQuizItem||("reading-q"+questionIndex),"A1","reread")}}function setupQuestions(){$("#questionForm").onsubmit=e=>{e.preventDefault();submitMemoryAnswer()};$("#questionNext").onclick=()=>{if(questionIndex<data.questions.length-1){questionIndex++;renderQuestion();$("#questionInput").focus()}else{$("#questionForm").classList.add("hidden");$("#questionNext").classList.add("hidden");coachFace(5);addMemoryMessage("coach","여섯 가지 기억 실마리를 모두 확인했어!",true)}}}
const SPY_LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]],reduceMotion=window.matchMedia("(prefers-reduced-motion: reduce)").matches;
const spy={status:[],used:[],attempts:[],lines:[],current:-1,phase:"",turn:"player",locateMiss:0,found:new Set(),audio:null,sound:true,particles:[],raf:0};
function spyCorrections(item){return Array.isArray(item[1])?item[1]:[]}
function spyTargets(tokens,item){return spyCorrections(item).map((pair,key)=>({key,from:pair[0],to:pair[1],index:tokens.findIndex(t=>t.includes(pair[0]))})).filter(x=>x.index>=0)}
function spySound(kind){if(!spy.sound)return;try{spy.audio=spy.audio||new (window.AudioContext||window.webkitAudioContext)();const ctx=spy.audio,now=ctx.currentTime,notes={open:[[520,0,.09],[780,.06,.12]],ok:[[660,0,.1],[880,.08,.1],[1320,.16,.18]],bad:[[220,0,.16],[180,.1,.18]],fix:[[520,0,.08],[700,.07,.08],[940,.14,.08],[1250,.21,.2]],bingo:[[523,0,.12],[659,.1,.12],[784,.2,.12],[1047,.3,.3]],pick:[[420,0,.05]]}[kind]||[];notes.forEach(([f,t,d])=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=kind==="bad"?"triangle":"sine";o.frequency.setValueAtTime(f,now+t);g.gain.setValueAtTime(.0001,now+t);g.gain.exponentialRampToValueAtTime(.16,now+t+.015);g.gain.exponentialRampToValueAtTime(.0001,now+t+d);o.connect(g).connect(ctx.destination);o.start(now+t);o.stop(now+t+d+.05)})}catch(e){}}
function spyFxSize(){const c=$("#spyFx"),r=window.devicePixelRatio||1;c.width=innerWidth*r;c.height=innerHeight*r;c.getContext("2d").setTransform(r,0,0,r,0,0)}
function spyBurst(x,y,count,colors,power=1,confetti=false){if(reduceMotion)return;for(let i=0;i<count;i++){const a=confetti?Math.PI/2+(Math.random()-.5)*1.2:Math.random()*Math.PI*2,v=(confetti?3+Math.random()*5:2+Math.random()*5)*power;spy.particles.push({x:confetti?Math.random()*innerWidth:x,y:confetti?-20-Math.random()*120:y,vx:Math.cos(a)*v*(confetti?.5:1),vy:confetti?Math.random()*2:Math.sin(a)*v-2,life:confetti?160+Math.random()*80:50+Math.random()*30,age:0,size:confetti?6+Math.random()*6:3+Math.random()*4,color:colors[i%colors.length],rot:Math.random()*6,spin:(Math.random()-.5)*.3,shape:confetti||Math.random()<.4?"rect":"star"})}if(!spy.raf)spy.raf=requestAnimationFrame(spyTick)}
function spyTick(){const c=$("#spyFx"),ctx=c.getContext("2d");ctx.clearRect(0,0,innerWidth,innerHeight);spy.particles=spy.particles.filter(p=>p.age<p.life);spy.particles.forEach(p=>{p.age++;p.vy+=.12;p.vx*=.985;p.x+=p.vx;p.y+=p.vy;p.rot+=p.spin;ctx.save();ctx.globalAlpha=Math.max(0,1-p.age/p.life);ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.fillStyle=p.color;if(p.shape==="rect")ctx.fillRect(-p.size/2,-p.size/4,p.size,p.size/2);else{ctx.beginPath();for(let k=0;k<10;k++){const r=k%2?p.size*.45:p.size;ctx.lineTo(Math.cos(k*Math.PI/5)*r,Math.sin(k*Math.PI/5)*r)}ctx.closePath();ctx.fill()}ctx.restore()});spy.raf=spy.particles.length?requestAnimationFrame(spyTick):0}
function spyCenter(el){const r=el.getBoundingClientRect();return[r.left+r.width/2,r.top+r.height/2]}
function spyMsg(text,type){const el=$("#spyCaseMsg");el.textContent=text;el.classList.remove("ok","bad");if(type){void el.offsetWidth;el.classList.add(type)}}
function spyStamp(text,type){const s=$("#spyStamp");s.textContent=text;s.className="spy-stamp "+type;void s.offsetWidth;s.classList.add("show")}
function spyShake(el){el.classList.remove("shake");void el.offsetWidth;el.classList.add("shake")}
function renderSpyBoard(){const board=$("#spyBoard");board.innerHTML="";data.spy.forEach((item,i)=>{const b=document.createElement("button"),st=spy.status[i],done=Boolean(spy.used[i]),owner=st==="player"?"나":st==="coach"?"젤리코치":"아무도";b.type="button";b.className="spy-tile"+(done?" solved "+(st||"neutral"):"");b.dataset.index=i;b.style.setProperty("--i",i);b.disabled=spy.turn!=="player";b.setAttribute("aria-label",(i+1)+"번 문장"+(done?" · "+owner+"의 칸":" · 선택 가능"));const back=st==="coach"?'<em class="coach-mark">○</em><small>젤리코치</small>':st==="player"?'<em class="player-mark">×</em><small>나의 칸</small>':'<em class="neutral-mark">—</em><small>중립 칸</small>';b.innerHTML='<span class="spy-tile-inner"><span class="spy-face front"><i>'+(i+1)+'</i><span class="spy-shine"></span></span><span class="spy-face back">'+back+'</span></span>';b.onclick=()=>openSpyCase(i);board.append(b)});renderSpyLines(false);updateSpyHud()}
function renderSpyLines(animateIndex){const svg=$("#spyLines"),pos=[50,150,250];svg.classList.toggle("all-done",spy.used.every(Boolean)&&animateIndex===false);svg.innerHTML=spy.lines.map((entry,k)=>{const l=SPY_LINES[entry.line],a=l[0],z=l[2],x1=pos[a%3],y1=pos[Math.floor(a/3)],x2=pos[z%3],y2=pos[Math.floor(z/3)],ex=(x2-x1)*.14,ey=(y2-y1)*.14;return'<line class="'+entry.owner+(k===animateIndex?' draw':'')+'" x1="'+(x1-ex)+'" y1="'+(y1-ey)+'" x2="'+(x2+ex)+'" y2="'+(y2+ey)+'" pathLength="1" vector-effect="non-scaling-stroke"/>'}).join("")}
function updateSpyHud(){const mine=spy.status.filter(x=>x==="player").length,played=spy.used.filter(Boolean).length,myLines=spy.lines.filter(x=>x.owner==="player").length;$("#spySolved").textContent=mine;$("#spyBingo").textContent=myLines;$("#spyMeter").style.width=(played/data.spy.length*100)+"%";const turn=$("#spyTurn");if(turn){turn.textContent=spy.turn==="player"?"나의 차례":"젤리코치의 차례";turn.classList.toggle("coach",spy.turn==="coach")}}
function bump(el){el.classList.remove("bump");void el.offsetWidth;el.classList.add("bump")}
function renderSpySentence(done){const item=data.spy[spy.current],tokens=item[0].split(/\s+/),targets=spyTargets(tokens,item),box=$("#spySentence");box.innerHTML="";box.className="spy-sentence"+(done?"":" scan");tokens.forEach((t,k)=>{const hit=targets.find(x=>x.index===k),w=document.createElement("button");w.type="button";w.className="spy-word";w.style.setProperty("--k",k);w.disabled=done;w.textContent=done&&hit?t.replace(hit.from,hit.to):t;if(done&&hit)w.classList.add("fixed-static");w.onclick=()=>pickSpyWord(k,w);box.append(w);if(k<tokens.length-1)box.append(document.createTextNode(" "))});spyHintRefresh(done)}
function spyHintRefresh(done){const id="spy-"+spy.current,bar=helpBar("spyHelp",$("#spyCaseMsg"));if(done||spy.phase!=="locate")return;bar.append(helpButton("바뀐 낱말 하나 반짝이기","A2","location",id,()=>{const item=data.spy[spy.current],tokens=item[0].split(/\s+/),t=spyTargets(tokens,item).find(x=>!spy.found.has(x.key));if(t)$$(".spy-word",$("#spySentence"))[t.index].classList.add("hint")}))}
function openSpyCase(i){const tile=$('.spy-tile[data-index="'+i+'"]'),done=Boolean(spy.used[i]),owner=spy.status[i];if(!done&&spy.turn!=="player"){showToast("젤리코치가 칸을 고르고 있어요.");return}spy.current=i;spy.locateMiss=0;spy.found=new Set();spy.phase=done?"review":"locate";$("#spyCaseNo").textContent=i+1;$("#spyCaseKicker").textContent=done?(owner==="player"?"내가 얻은 칸":owner==="coach"?"젤리코치가 얻은 칸":"아무도 얻지 않은 칸"):"나의 차례";$("#spyCaseTitle").textContent=done?"바르게 고친 문장이에요":"잘못 읽힌 낱말을 모두 눌러요";renderSpySentence(done);$("#spyStamp").className="spy-stamp";$("#spyJudge").classList.add("hidden");$("#spyNext").classList.toggle("hidden",!done);$("#spyNext").textContent="보드로 돌아가기";$("#spyPeekPanel").classList.add("hidden");$("#spyPeek").textContent="본문 살짝 보기";const count=spyCorrections(data.spy[i]).length,doneMsg=owner==="player"?"잘못 읽힌 낱말을 모두 찾았어요.":owner==="coach"?"젤리코치가 고른 문장을 확인해 봐요.":"이 칸은 중립으로 남았어요. 바르게 고친 문장을 확인해 봐요.";spyMsg(done?doneMsg:"바뀐 낱말 "+count+"곳을 찾아요.",done?"ok":"");const modal=$("#spyModal"),card=$("#spyCase");modal.classList.remove("hidden","closing");modal.setAttribute("aria-hidden","false");tile.classList.add("opening");spySound("open");if(!reduceMotion&&card.animate){const t=tile.getBoundingClientRect(),c=card.getBoundingClientRect();card.animate([{transform:"translate("+(t.left+t.width/2-c.left-c.width/2)+"px,"+(t.top+t.height/2-c.top-c.height/2)+"px) scale("+(t.width/c.width)+","+(t.height/c.height)+") rotateY(90deg)",opacity:.3,borderRadius:"30px"},{transform:"none",opacity:1,borderRadius:"26px"}],{duration:520,easing:"cubic-bezier(.2,.9,.25,1.12)"});$$(".spy-word",card).forEach(w=>w.classList.add("enter"))}setTimeout(()=>tile.classList.remove("opening"),520);if(!done)$(".spy-word",card)?.focus({preventScroll:true});log("spy_open","spy-"+i,{review:done,owner:owner||"neutral"})}
function closeSpyCase(instant){const modal=$("#spyModal");if(modal.classList.contains("hidden"))return;const i=spy.current,tile=$('.spy-tile[data-index="'+i+'"]'),card=$("#spyCase"),finish=()=>{if(modal.classList.contains("hidden"))return;modal.classList.add("hidden");modal.classList.remove("closing");modal.setAttribute("aria-hidden","true");if(spy.phase==="solved"||spy.phase==="neutral"){spy.phase="";celebrateSpyTile(i)}};if(instant||reduceMotion||!card.animate||!tile){finish();return}const t=tile.getBoundingClientRect(),c=card.getBoundingClientRect();modal.classList.add("closing");setTimeout(finish,480);card.animate([{transform:"none",opacity:1},{transform:"translate("+(t.left+t.width/2-c.left-c.width/2)+"px,"+(t.top+t.height/2-c.top-c.height/2)+"px) scale("+(t.width/c.width)+","+(t.height/c.height)+")",opacity:0}],{duration:380,easing:"cubic-bezier(.5,0,.75,0)"}).onfinish=finish}
function pickSpyWord(k,w){if(spy.phase!=="locate")return;const item=data.spy[spy.current],tokens=item[0].split(/\s+/),targets=spyTargets(tokens,item),hit=targets.find(x=>x.index===k&&!spy.found.has(x.key));if(!hit)assistItem("spy-"+spy.current).tries++;log("answer","spy-"+spy.current,{step:"locate",response:w.textContent,correct:Boolean(hit),found:spy.found.size});if(!hit){spy.locateMiss++;spy.attempts[spy.current]=(spy.attempts[spy.current]||0)+1;w.classList.add("miss");spyShake($("#spyCase"));spySound("bad");renderSpySentence(true);spyStamp("중립 칸","neutral");spyMsg("이 낱말은 바뀌지 않았어요. 이 칸은 아무도 얻지 않고, 코치는 다른 칸을 골라요.","bad");$("#spyCaseKicker").textContent="아무도 얻지 않은 칸";$("#spyCaseTitle").textContent="바뀐 낱말을 함께 확인해요";noteHelp("spy-"+spy.current,"A4","answer-reveal","error");itemResult("spy-"+spy.current,{outcome:"missed"});spyResolve(null);return}spy.found.add(hit.key);spySound("fix");const before=w.textContent,after=before.replace(hit.from,hit.to);w.innerHTML='<span class="spy-old">'+escapeHTML(before)+'</span><span class="spy-new">'+escapeHTML(after)+'</span>';w.classList.add("fixed-static");w.disabled=true;const [x,y]=spyCenter(w);spyBurst(x,y,26,["#16a37f","#ffd45c","#7a4fe0","#42c5d8"],.9);const remaining=targets.length-spy.found.size;if(remaining){spyMsg("찾았어요! 아직 "+remaining+"곳이 남았어요.","ok");return}spyStamp("나의 칸","fix");spyMsg("잘못 읽힌 낱말을 모두 찾았어요. 내가 이 칸을 얻었어요!","ok");$("#spyCaseKicker").textContent="내가 얻은 칸";$("#spyCaseTitle").textContent="문장을 바르게 고쳤어요";itemResult("spy-"+spy.current,{outcome:"found-all"});spyResolve("player")}
function spyResolve(owner){const i=spy.current;spy.status[i]=owner;spy.used[i]=true;spy.phase=owner?"solved":"neutral";$("#spyPeekPanel").classList.add("hidden");const last=spy.used.every(Boolean);$("#spyNext").textContent=last?"대결 결과 보기":"보드로 돌아가기";$("#spyNext").classList.remove("hidden");$("#spyNext").focus({preventScroll:true})}
function spyCoachChoice(){const open=spy.used.map((used,i)=>used?-1:i).filter(i=>i>=0);if(!open.length)return-1;const lineChoice=owner=>{for(const line of SPY_LINES){const owned=line.filter(i=>spy.status[i]===owner).length,candidates=line.filter(i=>!spy.used[i]);if(owned===2&&candidates.length===1)return candidates[0]}return-1};const winning=lineChoice("coach"),blocking=lineChoice("player");if(winning>=0)return winning;if(blocking>=0)return blocking;if(open.includes(4))return 4;for(const i of[0,2,6,8])if(open.includes(i))return i;return open[0]}
function spyCoachTakeTurn(){const i=spyCoachChoice();if(i<0){spyFinale();return}spy.turn="coach";renderSpyBoard();feedback($("#spyFeedback"),"젤리코치가 다른 빈칸을 고르고 있어요.");setTimeout(()=>{spy.current=i;spy.status[i]="coach";spy.used[i]=true;spy.phase="";spySound("pick");celebrateSpyTile(i)},reduceMotion?80:700)}
function celebrateSpyTile(i){const owner=spy.status[i];renderSpyBoard();const fresh=$('.spy-tile[data-index="'+i+'"]');fresh.classList.add(owner?"just-solved":"just-neutral");const [x,y]=spyCenter(fresh),colors=owner==="player"?["#ffd45c","#16a37f","#42c5d8","#ffffff"]:owner==="coach"?["#7a4fe0","#d8cff5","#ffffff"]:["#a5a6ad","#e7e5e0","#ffffff"];spyBurst(x,y,owner==="player"?40:owner==="coach"?22:12,colors);if(owner==="player")bump($("#spySolved"));const newLines=owner?SPY_LINES.map((l,k)=>({line:k,owner})).filter(entry=>!spy.lines.some(x=>x.line===entry.line&&x.owner===owner)&&SPY_LINES[entry.line].every(n=>spy.status[n]===owner)):[];let delay=300;newLines.forEach(entry=>{setTimeout(()=>{spy.lines.push(entry);renderSpyLines(spy.lines.length-1);updateSpyHud();if(owner==="player")bump($("#spyBingo"));spySound("bingo");SPY_LINES[entry.line].forEach((n,j)=>{setTimeout(()=>{$('.spy-tile[data-index="'+n+'"]')?.classList.add("line-glow")},j*110)});showSpyBanner(owner==="player"?"내가 한 줄!":"코치가 한 줄!")},delay);delay+=650});const played=spy.used.filter(Boolean).length,mine=spy.status.filter(x=>x==="player").length,coach=spy.status.filter(x=>x==="coach").length;if(played===data.spy.length){feedback($("#spyFeedback"),"대결이 끝났어요!","ok");setTimeout(spyFinale,delay+250);return}if(owner==="coach"){spy.turn="player";renderSpyBoard();feedback($("#spyFeedback"),"젤리코치가 다른 칸을 골랐어요. 이제 내 차례예요.");showToast("이제 내 차례예요.")}else{spy.turn="coach";renderSpyBoard();feedback($("#spyFeedback"),owner==="player"?"내 칸을 얻었어요. 이제 젤리코치 차례예요.":"틀린 칸은 중립으로 남았어요. 이제 젤리코치가 다른 칸을 골라요.",owner==="player"?"ok":"");setTimeout(spyCoachTakeTurn,delay+300)}$("#spyFeedback").setAttribute("aria-label","현재 나 "+mine+"칸, 젤리코치 "+coach+"칸, 진행 "+played+"칸")}
function showSpyBanner(text){const b=document.createElement("div");b.className="spy-banner";b.textContent=text;$("#spyGame .spy-board-wrap").append(b);setTimeout(()=>b.remove(),1300)}
function spyFinale(){$("#spyLines").classList.add("all-done");const mine=spy.status.filter(s=>s==="player").length,coach=spy.status.filter(s=>s==="coach").length,neutral=spy.used.filter((used,i)=>used&&!spy.status[i]).length,myLines=spy.lines.filter(x=>x.owner==="player").length,coachLines=spy.lines.filter(x=>x.owner==="coach").length;$("#spyFinaleText").textContent="나는 "+mine+"칸·"+myLines+"줄, 젤리코치는 "+coach+"칸·"+coachLines+"줄, 중립은 "+neutral+"칸이에요.";$("#spyFinale").classList.remove("hidden");spySound("bingo");spyBurst(0,0,160,["#7a4fe0","#42c5d8","#ffd45c","#16a37f","#ff7a8a"],1,true);log("spy_complete","word-spy",{mine,coach,neutral,myLines,coachLines})}
function openSpyPeek(auto){const panel=$("#spyPeekPanel");if(!auto&&!panel.classList.contains("hidden")){panel.classList.add("hidden");$("#spyPeek").textContent="본문 살짝 보기";return}panel.innerHTML=data.paragraphs.map(p=>"<p>"+escapeHTML(p)+"</p>").join("");panel.classList.remove("hidden");$("#spyPeek").textContent="본문 닫기";log("spy_peek","spy-"+spy.current,{auto:Boolean(auto)})}
function spyEnter(){const board=$("#spyBoard");board.classList.remove("intro");void board.offsetWidth;board.classList.add("intro");setTimeout(()=>board.classList.remove("intro"),1100)}
function setupSpy(){["#spyModal","#spyFinale","#spyFx"].forEach(s=>document.body.append($(s)));spy.status=data.spy.map(()=>null);spy.used=data.spy.map(()=>false);spy.attempts=data.spy.map(()=>0);spy.turn="player";try{spy.sound=localStorage.getItem(SK+"spy-sound")!=="off"}catch(e){}const snd=$("#spySound"),syncSound=()=>{snd.textContent=spy.sound?"소리 켬":"소리 끔";snd.setAttribute("aria-pressed",String(spy.sound));snd.setAttribute("aria-label",spy.sound?"효과음 끄기":"효과음 켜기")};syncSound();snd.onclick=()=>{spy.sound=!spy.sound;try{localStorage.setItem(SK+"spy-sound",spy.sound?"on":"off")}catch(e){}syncSound()};$("#spyNext").onclick=()=>closeSpyCase();$("#spyClose").onclick=()=>closeSpyCase();$("#spyModal").onclick=e=>{if(e.target===$("#spyModal"))closeSpyCase()};document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!$("#spyModal").classList.contains("hidden"))closeSpyCase()});const pk=$("#spyPeek");pk.dataset.track="hint";pk.dataset.helpLevel="A1";pk.dataset.helpType="reread";pk.onclick=()=>{if($("#spyPeekPanel").classList.contains("hidden"))noteHelp("spy-"+spy.current,"A1","reread");openSpyPeek(false)};$("#spyFinale").onclick=()=>$("#spyFinale").classList.add("hidden");spyFxSize();window.addEventListener("resize",spyFxSize)}
function renderSpy(){renderSpyBoard()}
function spyOnPage(p){verifyOnPage(p);kidOnPage(p);if(p===2)spyEnter();else{closeSpyCase(true);$("#spyFinale").classList.add("hidden")}}
function clearDropTargets(){$$('.energy-bin').forEach(bin=>bin.classList.remove("drop-target"))}
function setupBinDrop(bin,type){bin.ondragover=e=>{e.preventDefault();clearDropTargets();bin.classList.add("drop-target")};bin.ondragleave=e=>{if(!bin.contains(e.relatedTarget))bin.classList.remove("drop-target")};bin.ondrop=e=>{e.preventDefault();clearDropTargets();classify(type)};bin.onclick=e=>{if(e.detail===0)classify(type)}}
function renderBins(){if(data.counsel){renderCounsel();return}if(data.feed){renderFeed();return}if(data.organizer){renderOrganizer();return}const box=$("#energyBins");box.innerHTML="";Object.entries(data.stages).forEach(([type,stage])=>{const b=document.createElement("button");b.type="button";b.className="energy-bin";b.dataset.type=type;b.setAttribute("aria-label",stage[0]+"에 현재 카드 놓기");b.innerHTML=(stage[2]?'<span class="sprite glyph" aria-hidden="true">'+escapeHTML(stage[2])+'</span>':'<span class="sprite"></span>')+'<b>'+escapeHTML(stage[0])+'</b><small>'+state.counts[type]+' / '+stage[1]+'</small>';setupBinDrop(b,type);box.append(b)});renderClassifyCard()}
function enableClassifyDrag(){const card=$("#classifyCard"),item=state.classification[classifyIndex];card.draggable=Boolean(item);card.style.pointerEvents=item?"":"none";card.setAttribute("aria-grabbed","false");card.ondragstart=e=>{if(!item){e.preventDefault();return}e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",item.id);card.classList.add("dragging");card.setAttribute("aria-grabbed","true")};card.ondragend=()=>{card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets()};let touchDragging=false;card.onpointerdown=e=>{if(!item||e.pointerType==="mouse")return;touchDragging=true;card.setPointerCapture(e.pointerId);card.classList.add("dragging");card.setAttribute("aria-grabbed","true");e.preventDefault()};card.onpointermove=e=>{if(!touchDragging)return;e.preventDefault();clearDropTargets();const bin=document.elementFromPoint(e.clientX,e.clientY)?.closest(".energy-bin");if(bin)bin.classList.add("drop-target")};const endTouch=e=>{if(!touchDragging)return;touchDragging=false;const bin=document.elementFromPoint(e.clientX,e.clientY)?.closest(".energy-bin");card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets();if(bin)classify(bin.dataset.type)};card.onpointerup=endTouch;card.onpointercancel=()=>{touchDragging=false;card.classList.remove("dragging");card.setAttribute("aria-grabbed","false");clearDropTargets()}}
function renderClassifyCard(){const item=state.classification[classifyIndex];$("#classifyCounter").textContent=Math.min(classifyIndex+1,state.classification.length)+" / "+state.classification.length;const card=$("#classifyCard");if(!item){card.textContent="모든 카드를 알맞은 칸에 놓았어요!";if(data.organizer)orgFinish();if(data.feed)feedFinish();card.classList.add("complete-card");feedback($("#classifyFeedback"),(data.feed&&data.feed.done)||(data.organizer&&data.organizer.done)||data.classifyDone||"카드를 모두 알맞은 칸에 놓았어요.","ok");enableClassifyDrag();return}card.classList.remove("complete-card","feed-sentence");card.innerHTML=(item.cue?'<small>'+escapeHTML(item.cue)+'</small>':"")+escapeHTML(item.text);enableClassifyDrag()}
function classify(type){const item=state.classification[classifyIndex];if(!item)return false;const correct=type===item.type,id="classify-"+item.id,a=assistItem(id);a.tries++;log("answer",id,{response:type,correct,attempt:a.tries});if(!correct){feedback($("#classifyFeedback"),(data.feed&&feedSpit(type,item))||(data.organizer&&data.organizer.retry)||"카드의 설명을 끝까지 다시 읽고 다른 칸으로 옮겨 보세요.","bad");const bar=helpBar("classifyHelp",$("#classifyFeedback"));bar.append(helpButton("칸 두 개로 줄이기","A2","narrow-choices",id,()=>{const others=Object.keys(data.stages).filter(t=>t!==item.type&&t!==type);[type,...others.slice(1)].forEach(t=>$('.energy-bin[data-type="'+t+'"]').classList.add("dimmed"))}));if(a.tries>=2)bar.append(helpButton("알맞은 칸 보기","A4","answer-reveal",id,()=>$('.energy-bin[data-type="'+item.type+'"]').classList.add("reveal")));return false}helpBar("classifyHelp",$("#classifyFeedback"));$$(".energy-bin").forEach(b=>b.classList.remove("dimmed","reveal"));itemResult(id);const card=$("#classifyCard");card.draggable=false;card.style.pointerEvents="none";state.counts[type]++;const bin=$('.energy-bin[data-type="'+type+'"]');$('small',bin).textContent=state.counts[type]+" / "+data.stages[type][1];if(state.counts[type]===data.stages[type][1])bin.classList.add("complete");feedback($("#classifyFeedback"),data.feed?feedEat(bin,item,type):data.organizer?orgPlaced(bin,item):"맞아요. "+data.stages[type][0]+"의 특징입니다.","ok");classifyIndex++;setTimeout(renderClassifyCard,450);return true}function getVerifyCoachPrompts(){return (data.verifyCoach&&data.verifyCoach[verifyIndex])||[]}
function renderVerifyCoach(){$("#verifyStep").textContent="기억";$("#verifyPrompt").innerHTML="<strong>문제를 기억하며 풀어요.</strong><p>무엇을, 몇 개 고르라고 했는지 떠올려요. 잊었으면 아래 버튼을 눌러요.</p>";const box=$("#verifyCoachChoices");box.innerHTML="";box.append(helpButton("문제 다시 보기","A1","reread-question","verify-main-"+verifyIndex,()=>openQuestionPop(false),{repeat:true}))}
let qPopPending=false,qPopAt=0;
function openQuestionPop(first){const v=data.verify[verifyIndex];let pop=$("#qPop");if(!pop){pop=document.createElement("div");pop.id="qPop";pop.className="q-pop";pop.setAttribute("role","dialog");pop.setAttribute("aria-modal","true");pop.innerHTML='<div class="q-pop-card"><small id="qPopNo"></small><p id="qPopText"></p><span id="qPopHint">문제를 끝까지 읽고 기억해요.</span></div>';document.body.append(pop)}
  $("#qPopNo").textContent="문제 "+(verifyIndex+1)+" / "+data.verify.length;$("#qPopText").textContent=v[0];$("#qPopHint").textContent="문제를 끝까지 읽고 기억해요.";pop.classList.remove("ready");pop.hidden=false;qPopAt=Date.now();qPopPending=false;
  setTimeout(()=>{pop.classList.add("ready");$("#qPopHint").textContent="기억했으면 아무 곳이나 눌러요."},1000);
  const close=e=>{if(Date.now()-qPopAt<1000)return;pop.hidden=true;pop.removeEventListener("pointerdown",close);document.removeEventListener("keydown",close);log("question_view","verify-main-"+verifyIndex,{readMs:Date.now()-qPopAt,reopen:!first});if(first){verifyCoachDone=true;verifyUnlock()}};
  pop.addEventListener("pointerdown",close);document.addEventListener("keydown",close)}
function verifyOnPage(p){const pop=$("#qPop");if(p!==4){if(pop&&!pop.hidden){pop.hidden=true;qPopPending=!verifyCoachDone}return}if(qPopPending&&!verifyCoachDone)openQuestionPop(true)}
let verifyCoachDone=false;
function verifyEv(){return (data.verifyEvidence||[])[verifyIndex]||null}
function verifyHits(){return $$("#verifyEvidence .w.on")}
function verifyUnlock(){const ev=null,need=false;const ready=verifyCoachDone&&!need;$$('#verifyOptions input').forEach(x=>x.disabled=!ready);$("#verifyCheck").disabled=!ready;
  if(!verifyCoachDone)return;if(ev)$("#verifyEvidence").classList.remove("hidden");feedback($("#verifyFeedback"),need?"① 본문에서 답의 근거가 되는 말을 눌러 형광펜을 칠해요.":"문제를 떠올리며 답을 골라요. 다 고르면 확인해요.",need?"":"ok")}
function renderVerifyEvidence(){const box=$("#verifyEvidence");box.innerHTML="";box.classList.add("hidden")}
function renderVerifyQuestion(){const v=data.verify[verifyIndex];verifyCoachStep=0;verifyCoachDone=false;$("#verifyQuestionCount").textContent="문제 "+(verifyIndex+1)+" / "+data.verify.length;$("#verifyQuestion").innerHTML='<span class="q-hidden">문제를 떠올리며 풀어요</span>';$("#verifyOptions").innerHTML="";v[1].forEach((o,i)=>{const label=document.createElement("label");label.innerHTML='<input type="checkbox" value="'+i+'" disabled><span>'+escapeHTML(o)+'</span>';$("#verifyOptions").append(label)});$("#verifyCheck").classList.remove("hidden");$("#verifyCheck").disabled=true;$("#verifyNext").classList.add("hidden");helpBar("verifyHelp",$("#verifyFeedback"));renderVerifyEvidence();feedback($("#verifyFeedback"),"먼저 문제를 읽고 기억해요.");renderVerifyCoach();qPopPending=true;if(page===4)openQuestionPop(true)}
function checkVerify(){const v=data.verify[verifyIndex],picked=$$('#verifyOptions input:checked').map(x=>Number(x.value)).sort(),answer=v[2].slice().sort(),correct=JSON.stringify(picked)===JSON.stringify(answer),id="verify-main-"+verifyIndex,a=assistItem(id);a.tries++;log("answer",id,{response:picked.join(","),correct,attempt:a.tries});if(!correct){feedback($("#verifyFeedback"),"아직 정답이 아니에요. 고른 보기와 빠뜨린 보기를 본문과 다시 비교해 보세요.","bad");const bar=helpBar("verifyHelp",$("#verifyFeedback"));bar.append(helpButton("정답이 몇 개인지 보기","A2","count",id,()=>feedback($("#verifyFeedback"),"정답은 "+v[2].length+"개예요. 보기 하나하나를 본문과 비교해 보세요.")));if(a.tries>=2)bar.append(helpButton("정답과 까닭 보기","A4","answer-reveal",id,()=>{$$("#verifyOptions input").forEach(x=>x.checked=v[2].includes(Number(x.value)));feedback($("#verifyFeedback"),v[3]+" 정답에 표시해 두었어요. 읽어 보고 ‘내 답 확인하기’를 눌러요.")}));return}$("#verifyQuestion").textContent=v[0];helpBar("verifyHelp",$("#verifyFeedback"));itemResult(id);$$('#verifyOptions input').forEach(x=>x.disabled=true);$("#verifyCheck").classList.add("hidden");const done=(verifyIndex+1)+" / "+data.verify.length+" 완료";feedback($("#verifyFeedback"),"정답이에요! "+done+". "+v[3],"ok");if(verifyIndex<data.verify.length-1){$("#verifyNext").textContent="다음 문제";$("#verifyNext").classList.remove("hidden");$("#verifyStep").textContent="정답";$("#verifyPrompt").textContent="맞혔어요. 다음 문제에서도 묻는 말과 보기의 표현을 확인해요.";$("#verifyCoachChoices").innerHTML=""}else{$("#verifyStep").textContent="완료";$("#verifyPrompt").textContent="정답이에요. "+data.verify.length+"문제를 모두 풀었어요!";$("#verifyCoachChoices").innerHTML="";showToast(data.verify.length+"문제를 모두 마쳤어요!")}verifyProofStart()}
function verifyProofStart(){const pr=(data.verifyProof||[])[verifyIndex];if(!pr)return;const next=$("#verifyNext"),wasShown=!next.classList.contains("hidden"),box=$("#verifyEvidence"),id="verify-proof-"+verifyIndex,a=assistItem(id);next.classList.add("hidden");
  $("#verifyStep").textContent="근거";$("#verifyPrompt").innerHTML="<strong>내 답이 맞다는 걸 보여 주는 문장을 골라요.</strong>";$("#verifyCoachChoices").innerHTML="";
  box.classList.remove("hidden");box.innerHTML='<small>근거 대기 · 글에서 가져온 문장이에요</small><div class="proof-list"></div><p class="proof-msg" role="status"></p>';const list=$(".proof-list",box),msg=$(".proof-msg",box);
  pr.s.forEach((t,ti)=>{const b=document.createElement("button");b.type="button";b.className="proof-opt";b.textContent=t.split(" + ").join("  /  ");b.dataset.track="answer";b.dataset.correct=String(ti===pr.a);
    b.onclick=()=>{a.tries++;const ok=ti===pr.a;log("answer",id,{response:t,correct:ok,attempt:a.tries});
      if(!ok){b.classList.add("wrong");b.disabled=true;msg.textContent=a.tries===1?"그 문장으로는 이 답을 보여 주기 어려워요. 문제에서 묻는 것과 이어지는 문장을 찾아요.":"한 번 더 골라 봐요. 아래 도움을 써도 괜찮아요.";const bar=helpBar("proofHelp",msg);if(a.tries>=2)bar.append(helpButton("근거 문장 보기","A4","answer-reveal",id,()=>$$(".proof-opt",list)[pr.a].classList.add("reveal")));return}
      b.classList.add("correct");$$(".proof-opt",list).forEach(x=>x.disabled=true);helpBar("proofHelp",msg);coachFace(5);msg.textContent=a.help>=2?"근거를 확인했어요.":a.tries>1?"스스로 고쳐 찾았어요!":"딱 맞는 근거예요!";itemResult(id);
      $("#verifyStep").textContent="정답";$("#verifyPrompt").innerHTML="<strong>답과 근거를 모두 찾았어요.</strong>";if(wasShown)next.classList.remove("hidden")};list.append(b)});
  setTimeout(()=>box.scrollIntoView({block:"nearest",behavior:"smooth"}),40)}
function setupVerify(){$("#verifyCheck").onclick=checkVerify;$("#verifyNext").onclick=()=>{verifyIndex++;renderVerifyQuestion()};renderVerifyQuestion()}/* 6단계 어휘확장: 쉬운 말→오늘 낱말, 반대(짝) 문장→오늘 낱말 문장, 뽑은 낱말로 문장 만들기 */
const vx={rounds:[],i:0,tries:0,drawn:[],redraw:1,cur:null};
function vxBuildRounds(){const w=data.wordWork||{syn:[],ant:[],make:[]};vx.rounds=[...w.syn.map((d,n)=>({part:"syn",n,d})),...w.ant.map((d,n)=>({part:"ant",n,d})),{part:"make",n:0},{part:"make",n:1}].filter(r=>r.part!=="make"||w.make.length>r.n)}
function vxMark(t,cls){return escapeHTML(t).replace(/\{([^}]*)\}/,(m,x)=>'<mark class="'+cls+'">'+x+'</mark>')}
function vxChips(choices,onPick){const box=document.createElement("div");box.className="vx-chips";choices.forEach(c=>{const b=document.createElement("button");b.type="button";b.textContent=c;b.dataset.track="answer";b.onclick=()=>onPick(c,b,box);box.append(b)});return box}
function renderTransfer(){const r=vx.rounds[vx.i];if(!r)return;vx.tries=0;const ob=$("#vxHelp");if(ob)ob.innerHTML="";$("#vxCounter").textContent=(vx.i+1)+" / "+vx.rounds.length;
  $$("#vxSteps li").forEach(li=>{const p=li.dataset.vxPart;li.classList.toggle("on",p===r.part);li.classList.toggle("done",!vx.rounds.slice(vx.i).some(x=>x.part===p))});
  const body=$("#vxBody");body.innerHTML="";$("#vxNext").classList.add("hidden");
  if(r.part==="syn")vxSyn(r,body);else if(r.part==="ant")vxAnt(r,body);else vxMake(r,body)}
function vxAfterWrong(r,b,ans){vx.tries++;b.classList.add("wrong");const id="vocab-"+r.part+"-"+r.n,v=data.vocab.find(x=>x[0]===r.d.word);assistItem(id).tries=vx.tries;
  feedback($("#vxFeedback"),"그 낱말을 넣어 문장을 소리 내어 읽어 보세요. 뜻이 자연스러운가요?","bad");const bar=helpBar("vxHelp",$("#vxFeedback"));
  if(v)bar.append(helpButton("뜻 힌트 보기","A2","meaning",id,()=>feedback($("#vxFeedback"),"힌트: ‘"+v[2]+"’ 이런 뜻의 낱말이에요.")));
  if(vx.tries>=2)bar.append(helpButton("정답 보기","A4","answer-reveal",id,()=>$$("#vxBody .vx-chips button").forEach(x=>{if(x.textContent===ans)x.classList.add("reveal")})))}
function vxRight(r){const id="vocab-"+r.part+"-"+r.n;assistItem(id).tries=vx.tries+1;helpBar("vxHelp",$("#vxFeedback"));itemResult(id)}
function vxChipCorrect(choice,word){return choice===word?"true":"false"}
function vxSyn(r,body){const d=r.d,ans=d.answer||d.word;body.innerHTML='<p class="vx-kicker">밑줄 친 쉬운 말을 오늘 배운 낱말로 바꿔요</p><p class="vx-sent" id="vxSent">'+vxMark(d.sentence,"easy")+'</p>';
  feedback($("#vxFeedback"),"어떤 낱말로 바꾸면 뜻이 같을까요?");
  const chips=vxChips(d.choices,(c,b,box)=>{const ok=c===ans;log("answer","vocab-syn-"+r.n,{response:c,correct:ok,attempt:vx.tries+1,word:d.word});
    if(!ok){vxAfterWrong(r,b,ans);return}vxRight(r);b.classList.add("correct");$$("button",box).forEach(x=>x.disabled=true);
    $("#vxSent").innerHTML=vxMark(d.sentence.replace(/\{[^}]*\}/,"{"+ans+"}"),"target");
    const was=document.createElement("p");was.className="vx-was";was.innerHTML='<span>바꾸기 전</span> '+vxMark(d.sentence,"easy");body.append(was);
    feedback($("#vxFeedback"),"‘"+d.easy+"’ → ‘"+ans+"’. 뜻은 같고, 더 정확한 낱말이 됐어요.","ok");vxDone()});
  $$("button",chips).forEach(b=>b.dataset.correct=vxChipCorrect(b.textContent,ans));body.append(chips)}
function vxAnt(r,body){const d=r.d,blank='<span class="vx-blank" id="vxBlank">?</span>';
  body.innerHTML='<p class="vx-kicker">'+(d.rel==="반대말"?"반대말이 쓰인 문장을 보고, 뜻이 반대인 문장을 완성해요":"짝 낱말이 쓰인 문장을 보고, 다른 짝으로 문장을 완성해요")+'</p>'+
    '<div class="vx-pair"><p class="vx-sent from"><small>'+escapeHTML(d.rel)+' 문장</small>'+vxMark(d.from,"opp")+'</p><span class="vx-arrow" aria-hidden="true">↓ '+escapeHTML(d.rel)+'</span><p class="vx-sent to"><small>오늘 낱말로 바꾼 문장</small>'+escapeHTML(d.to).replace("{}",blank)+'</p></div>';
  feedback($("#vxFeedback"),"빈칸에 들어갈 오늘 낱말을 골라요.");
  const chips=vxChips(d.choices,(c,b,box)=>{const ok=c===d.word;log("answer","vocab-ant-"+r.n,{response:c,correct:ok,attempt:vx.tries+1,word:d.word});
    if(!ok){vxAfterWrong(r,b,d.word);return}vxRight(r);b.classList.add("correct");$$("button",box).forEach(x=>x.disabled=true);
    const bl=$("#vxBlank");bl.textContent=d.word;bl.classList.add("filled");
    feedback($("#vxFeedback"),"‘"+d.opp+"’ ↔ ‘"+d.word+"’. 두 문장을 이어서 읽어 보세요.","ok");vxDone()});
  $$("button",chips).forEach(b=>b.dataset.correct=vxChipCorrect(b.textContent,d.word));body.append(chips)}
function vxPick(){const pool=data.wordWork.make.filter(m=>!vx.drawn.includes(m.word));return pool[Math.floor(Math.random()*pool.length)]}
function vxMake(r,body){vx.cur=null;body.innerHTML='<p class="vx-kicker">낱말 카드를 뽑아, 그 낱말이 들어간 문장을 만들어요 ('+(r.n+1)+' / 2)</p>'+
  '<div class="vx-draw"><button type="button" class="vx-card-btn" id="vxDraw"><span class="vx-card-face">?</span><small>눌러서 뽑기</small></button><div class="vx-word-info hidden" id="vxInfo"></div></div>'+
  '<div class="vx-write hidden" id="vxWrite"><label for="vxText">내 문장</label><textarea id="vxText" rows="2" maxlength="120" placeholder="뽑은 낱말을 넣어 문장을 써요"></textarea>'+
  '<div class="vx-row"><button type="button" class="vx-redraw" id="vxRedraw">다른 낱말 뽑기</button><button type="button" class="primary" id="vxCheck">문장 확인</button></div></div>'+
  '<div class="vx-self hidden" id="vxSelf"><strong>스스로 확인해요</strong><label><input type="checkbox"> 낱말의 뜻에 맞게 썼어요</label><label><input type="checkbox"> 누가(무엇이)·어떻게가 들어갔어요</label><label><input type="checkbox"> 문장을 끝까지 맺었어요</label><p class="vx-example" id="vxExample"></p></div>';
  feedback($("#vxFeedback"),"카드를 눌러 낱말을 뽑아요.");
  const show=()=>{const m=vx.cur,card=$("#vxDraw");card.querySelector(".vx-card-face").textContent=m.word;card.querySelector("small").textContent="뽑은 낱말";card.disabled=true;
    $("#vxInfo").innerHTML='<b>'+escapeHTML(m.word)+'</b><span>'+escapeHTML(m.meaning)+'</span>';$("#vxInfo").classList.remove("hidden");$("#vxWrite").classList.remove("hidden");
    const hb=helpBar("vxHelp",$("#vxFeedback"));hb.append(helpButton("예문 먼저 보기","A3","model-sentence","vocab-make-"+r.n,()=>feedback($("#vxFeedback"),"예문: "+m.example+" 이 모양을 참고해 내 문장을 써요.")));$("#vxRedraw").disabled=vx.redraw<1;$("#vxRedraw").textContent=vx.redraw<1?"다른 낱말 뽑기 (다 썼어요)":"다른 낱말 뽑기 (한 번)";feedback($("#vxFeedback"),"뽑은 낱말을 넣어 문장을 써요.");$("#vxText").focus()};
  $("#vxDraw").onclick=()=>{vx.cur=vxPick();if(!vx.cur)return;vx.drawn.push(vx.cur.word);log("vocab_draw","vocab-make-"+r.n,{word:vx.cur.word});show()};
  $("#vxRedraw").onclick=()=>{if(vx.redraw<1)return;const next=vxPick();if(!next)return;vx.redraw--;vx.cur=next;vx.drawn.push(next.word);log("vocab_redraw","vocab-make-"+r.n,{word:next.word});$("#vxText").value="";show()};
  $("#vxCheck").onclick=()=>{const m=vx.cur,t=$("#vxText").value.trim(),has=m.forms.some(f=>t.includes(f)),ended=/[다요죠까네!?.]$/.test(t),long=t.replace(/\s/g,"").length>=8;
    vx.tries++;log("vocab_sentence","vocab-make-"+r.n,{word:m.word,text:t,containsWord:has,ended,correct:has&&ended&&long,attempt:vx.tries});
    if(!has){feedback($("#vxFeedback"),"뽑은 낱말 ‘"+m.word+"’, 문장에 들어 있나요? 다시 확인해요.","bad");return}
    if(!long){feedback($("#vxFeedback"),"누가, 무엇을, 어떻게 했는지 조금 더 넣어 문장을 길게 써 봐요.","bad");return}
    if(!ended){feedback($("#vxFeedback"),"문장 끝을 ‘~요.’나 ‘~다.’처럼 맺어 봐요.","bad");return}
    $("#vxText").readOnly=true;$("#vxCheck").disabled=true;$("#vxRedraw").disabled=true;$("#vxSelf").classList.remove("hidden");
    $("#vxExample").innerHTML='<span>이렇게도 쓸 수 있어요</span>'+escapeHTML(m.example);
    feedback($("#vxFeedback"),"낱말이 잘 들어갔어요. 아래 세 가지를 스스로 확인해요.","ok");
    helpBar("vxHelp",$("#vxFeedback"));const boxes=$$("#vxSelf input");boxes.forEach(x=>x.onchange=()=>{if(boxes.every(y=>y.checked)){log("vocab_selfcheck","vocab-make-"+r.n,{word:m.word});log("writing-draft","vocab-make-"+r.n,{text:t,word:m.word,accuracy:"notApplicable"});itemResult("vocab-make-"+r.n,{accuracy:"notApplicable"});vxDone()}})}}
function vxDone(){const last=vx.i>=vx.rounds.length-1;$("#vxNext").textContent=last?"어휘확장 마치기":"다음";$("#vxNext").classList.remove("hidden")}
function answerTransfer(){}
function setupTransfer(){vxBuildRounds();$("#vxNext").onclick=()=>{if(vx.i<vx.rounds.length-1){vx.i++;renderTransfer()}else{$("#vxNext").classList.add("hidden");$$("#vxSteps li").forEach(li=>{li.classList.remove("on");li.classList.add("done")});const words=new Set(vx.rounds.filter(x=>x.d).map(x=>x.d.word).concat(vx.drawn.slice(-2)));feedback($("#vxFeedback"),"어휘확장을 모두 마쳤어요. 오늘 낱말 "+words.size+"개를 직접 바꾸고 써 봤어요!","ok");log("activity_complete","vocab-expansion",{rounds:vx.rounds.length})}}}

function setupReflection(){$$('#reflectionChoices button').forEach(b=>b.onclick=()=>{$$('#reflectionChoices button').forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.reflection=b.textContent;state.reflectionStrategy=b.dataset.strategy;$("#reflectionStrategyText").textContent=state.reflectionStrategy;$("#reflectionStrategy").classList.remove("hidden");$("#finishLesson").classList.remove("hidden")});$("#finishLesson").onclick=finish}
function finish(){if(!state.reflection&&page===6){showToast("오늘 실수한 것과 가장 가까운 보기를 골라 주세요.");return}const record={level,mistake:state.reflection,strategy:state.reflectionStrategy,finishedAt:new Date().toISOString()};localStorage.setItem(SK+"complete-"+level,JSON.stringify(record));$("#completionCard").classList.remove("hidden");$("#finishLesson").classList.add("hidden");$("#completionSignal").hidden=false;log("lesson_complete","lesson",record);showToast("수업을 마쳤어요!")}
function boot(){applyMeta();setupLevel();setupIntro();setupNavigation();setupAnnotationDock();renderPassage();setupVocab();setupPrediction();setupReadingFlow();setupQuestions();setupSpy();setupVerify();setupTransfer();setupReflection();renderPrediction();renderQuestion();renderSpy();renderBins();renderTransfer();showPage(0)}
/* 아이 화면(견본: 2단계만) — 징검다리 길 + 젤리 표정 + 말랑한 글꼴·하늘색 */
const KID_PAGES=[0,1,2,3,4,5,6];
function coachFace(n){$$(".coach-title img").forEach(img=>{img.src="assets/jelly-face-"+n+".webp";img.classList.remove("bounce");void img.offsetWidth;img.classList.add("bounce")})}
function kidFitCover(){const meta=$("#readingPaper .reading-meta"),cv=$("#passageCover");if(!meta||!cv)return;cv.style.top=(document.body.classList.contains("kid-skin")?meta.offsetTop+meta.offsetHeight+10:74)+"px"}
function kidOnPage(p){const on=KID_PAGES.includes(p);document.body.classList.toggle("kid-skin",on);document.body.dataset.kidStage=String(p);if(!on)return;

  const h=$(".reading-page .page-head h1");if(h&&!h.dataset.kid){h.dataset.kid="1";h.dataset.orig=h.textContent;h.textContent="천천히, 끝까지 읽어요"}
  kidFitCover();const cover=$("#passageCover>div");if(cover&&!$(".kid-face",cover)){const cp=$("p",cover);if(cp)cp.textContent="읽은 내용을 떠올려 오른쪽 문제를 풀어요.";const img=document.createElement("img");img.className="kid-face";img.alt="";img.src="assets/jelly-cover.webp";cover.prepend(img)}
  $$(".coach-title img").forEach(img=>{if(!img.dataset.kid){img.dataset.kid="1";img.src="assets/jelly-face-4.webp"}})}
function applyMeta(){const m=data.meta||{},set=(sel,v,html)=>{const e=$(sel);if(e&&v!=null){if(html)e.innerHTML=v;else e.textContent=v}};
  set("#introTitle",m.introTitleHTML,true);set("#introSub",m.introSub,true);set("#introTags",(m.tags||[]).map(t=>"<span>"+escapeHTML(t)+"</span>").join(""),true);
  set("#brandLabel",m.brand);set("#step4Label",m.classifyStep);set("#step4Eyebrow","4 · "+(m.classifyStep||"분류"));set("#subjectLine",m.subject);
  set("#classifyH1",m.classifyH1);set("#classifyKicker",m.classifyKicker);set("#classifyH2",m.classifyH2);
  const hero=$("#heroBox");if(hero&&m.hero){hero.setAttribute("aria-label",m.hero.title);hero.innerHTML='<div class="topic-hero'+(m.cover?' has-cover':'')+'">'+(m.cover?'<img class="topic-cover" src="'+escapeHTML(m.cover)+'" alt="">':'')+'<span class="topic-kicker">'+escapeHTML(m.hero.kicker||"오늘의 글")+'</span><b>'+escapeHTML(m.hero.title)+'</b><p>'+escapeHTML(m.hero.question||"")+'</p></div>'}
  const art=$(".intro-art");if(art&&m.cover){art.classList.add("has-cover");art.innerHTML='<img class="intro-cover" src="'+escapeHTML(m.cover)+'" alt=""><img class="intro-jelly" src="assets/jelly-coach-square.png" alt="젤리코치">'}}
/* 글 짜임 칸(organizer): chain=흐름 잇기, compare=비교 표 */
function orgSlots(o){if(o.kind==="compare"){const out=[];o.rows.forEach((r,i)=>o.cols.forEach((c,j)=>out.push({id:"r"+i+"c"+j,name:c+" · "+r})));return out}return o.steps.map((_,i)=>({id:"s"+(i+1),name:(i+1)+"번째"}))}
function orgSlotBtn(id,name,ph){const b=document.createElement("button");b.type="button";b.className="energy-bin org-slot";b.dataset.type=id;b.setAttribute("aria-label",name+" 칸에 현재 카드 놓기");b.innerHTML='<span class="org-fill">'+escapeHTML(ph||"여기에 놓아요")+'</span><small></small>';setupBinDrop(b,id);return b}
function renderOrganizer(){const o=data.organizer,box=$("#energyBins");box.innerHTML="";box.className="energy-bins org-board org-"+o.kind;if(o.title)$("#classifyH2").textContent=o.title;
  if(o.kind==="compare"){box.style.setProperty("--org-cols",o.cols.length);box.append(Object.assign(document.createElement("span"),{className:"org-corner"}));o.cols.forEach(c=>box.append(Object.assign(document.createElement("b"),{className:"org-colhead",textContent:c})));o.rows.forEach((r,i)=>{box.append(Object.assign(document.createElement("b"),{className:"org-rowhead",textContent:r}));o.cols.forEach((c,j)=>box.append(orgSlotBtn("r"+i+"c"+j,c+" · "+r,"")))})}
  else{o.steps.forEach((_,i)=>{const row=document.createElement("div");row.className="org-row";row.innerHTML='<span class="org-num">'+(i+1)+'</span>';row.append(orgSlotBtn("s"+(i+1),(i+1)+"번째",(i+1)+"번째 내용"));box.append(row);if(i<o.steps.length-1)box.append(Object.assign(document.createElement("span"),{className:"org-link",textContent:"▼"}))})}
  $("#classifyH2").classList.remove("org-done-title");renderClassifyCard()}
function orgPlaced(bin,item){bin.classList.add("filled");$(".org-fill",bin).textContent=item.short||item.text;bin.classList.remove("pop");void bin.offsetWidth;bin.classList.add("pop");
  const o=data.organizer;if(o.kind!=="compare"){const row=bin.closest(".org-row"),prev=row&&row.previousElementSibling,next=row&&row.nextElementSibling;if(prev&&prev.classList.contains("org-link")&&prev.previousElementSibling&&$(".org-slot.filled",prev.previousElementSibling))prev.classList.add("on");if(next&&next.classList.contains("org-link")&&next.nextElementSibling&&$(".org-slot.filled",next.nextElementSibling))next.classList.add("on");return "맞아요! "+(item.slotSay||"흐름이 이어졌어요.")}
  return "맞아요! "+escapeHTML(data.stages[bin.dataset.type][0])+" 칸이에요."}
function orgFinish(){const h=$("#classifyH2");if(h.classList.contains("org-done-title"))return;h.textContent=data.organizer.done||"다 채웠어요!";h.classList.add("org-done-title");$("#energyBins").classList.add("org-complete");$$(".org-link").forEach(x=>x.classList.add("on"))}
/* 젤리 몬스터 먹이 주기(feed): 칸=몬스터, 다 먹으면 비밀 문장 조각이 열림 */
const FEED_FACE={idle:"assets/jelly-face-4.webp",eat:"assets/jelly-face-5.webp",yuck:"assets/jelly-face-1.webp",full:"assets/jelly-face-5.webp"};
function feedFace(bin,k){const im=$(".feed-face",bin);if(im)im.src=FEED_FACE[k]}
function feedSay(bin,t){const b=$(".feed-bubble",bin);if(!b)return;b.textContent=t;b.classList.remove("show");void b.offsetWidth;b.classList.add("show")}
function renderFeed(){const box=$("#energyBins");box.innerHTML="";box.className="energy-bins feed-board";
  const zoo=document.createElement("div");zoo.className="feed-zoo";box.append(zoo);
  Object.entries(data.stages).forEach(([type,stage])=>{const b=document.createElement("button");b.type="button";b.className="energy-bin feed-monster";b.dataset.type=type;b.setAttribute("aria-label",stage[0]+" 몬스터에게 현재 카드 주기");
    b.innerHTML='<span class="feed-bubble" aria-hidden="true"></span><img class="feed-face" alt="" src="'+FEED_FACE.idle+'"><b>'+(stage[2]?'<i aria-hidden="true">'+escapeHTML(stage[2])+'</i> ':'')+escapeHTML(stage[0])+'</b><span class="feed-belly" aria-hidden="true">'+'<em></em>'.repeat(stage[1])+'</span><small>'+state.counts[type]+' / '+stage[1]+'</small>';setupBinDrop(b,type);zoo.append(b)});
  const sec=document.createElement("div");sec.className="feed-secret";sec.innerHTML='<span class="feed-secret-label">비밀 문장</span>'+Object.keys(data.stages).map(t=>'<span class="feed-piece" data-type="'+t+'"><i aria-hidden="true">🔒</i><span>'+escapeHTML(data.feed.secret[t]||"")+'</span></span>').join("");box.append(sec);
  renderClassifyCard();setTimeout(()=>{const first=$(".feed-monster");if(first)feedSay(first,"배고파요!")},500)}
function feedFly(bin){const c=$("#classifyCard"),f=$(".feed-face",bin);if(!c||!f)return;const a=c.getBoundingClientRect(),z=f.getBoundingClientRect(),g=c.cloneNode(true);g.removeAttribute("id");g.className="current-card feed-fly";g.style.cssText="position:fixed;left:"+a.left+"px;top:"+a.top+"px;width:"+a.width+"px;height:"+a.height+"px;margin:0;z-index:60;pointer-events:none";document.body.append(g);
  requestAnimationFrame(()=>{g.style.transition="transform .42s cubic-bezier(.5,0,.75,0),opacity .42s";g.style.transform="translate("+(z.left+z.width/2-a.left-a.width/2)+"px,"+(z.top+z.height*.6-a.top-a.height/2)+"px) scale(.08) rotate(-20deg)";g.style.opacity=".4"});setTimeout(()=>g.remove(),460)}
function feedEat(bin,item,type){feedFly(bin);const n=state.counts[type],max=data.stages[type][1],full=n>=max;
  setTimeout(()=>{feedFace(bin,"eat");bin.classList.remove("chomp");void bin.offsetWidth;bin.classList.add("chomp");$$(".feed-belly em",bin).forEach((e,i)=>e.classList.toggle("on",i<n));bin.style.setProperty("--belly",n/max);feedSay(bin,full?"배불러!":"냠냠!")},380);
  setTimeout(()=>{feedFace(bin,full?"full":"idle");if(full){bin.classList.add("full");const pc=$('.feed-piece[data-type="'+type+'"]');if(pc)pc.classList.add("open")}},1150);
  return full?"냠냠! "+escapeHTML(data.stages[type][0])+" 몬스터가 배불러서 비밀 문장 한 조각을 열어 줬어요.":"냠냠! "+escapeHTML(data.stages[type][0])+" 몬스터가 맛있게 먹었어요."}
function feedSpit(type,item){const bin=$('.energy-bin[data-type="'+type+'"]');if(!bin)return "";feedFace(bin,"yuck");feedSay(bin,"퉤!");bin.classList.remove("spit");void bin.offsetWidth;bin.classList.add("spit");const c=$("#classifyCard");if(c){c.classList.remove("bounce");void c.offsetWidth;c.classList.add("bounce")}setTimeout(()=>feedFace(bin,bin.classList.contains("full")?"full":"idle"),900);
  return "퉤! 이 몬스터는 "+data.stages[type][0]+" 카드만 먹어요. 카드를 끝까지 다시 읽고 다른 몬스터에게 줘 보세요."}
function feedFinish(){const sec=$(".feed-secret");if(!sec||sec.classList.contains("done"))return;setTimeout(()=>{sec.classList.add("done");const cd=$("#classifyCard");cd.classList.add("feed-sentence");cd.innerHTML="<small>🔓 비밀 문장</small>"+escapeHTML(Object.keys(data.stages).map(t=>data.feed.secret[t]||"").join(" "));$$(".feed-monster").forEach((b,i)=>setTimeout(()=>feedSay(b,"고마워!"),i*150))},1250)}
/* 문제 해결사(counsel): 친구의 문제를 글에서 배운 것으로 해결 */
let counselIndex=0;
function renderCounsel(){const C=data.counsel,box=$("#energyBins"),sec=box.closest(".page");if(sec){sec.dataset.measureId="situationApplication";sec.classList.add("counsel-page")}
  box.className="energy-bins counsel-board";const head=$(".classify-board-head");if(head)head.classList.add("counsel-head");
  const panel=$(".current-card-panel");panel.classList.add("counsel-panel");$(".current-card-panel>strong").textContent="어떻게 도와줄까?";$("#classifyCard").classList.add("hidden");
  if(!$("#counselOpts")){const o=document.createElement("div");o.id="counselOpts";o.className="counsel-opts";$("#classifyCard").after(o)}
  counselIndex=0;counselShow()}
function counselQueue(){return '<div class="counsel-queue" aria-hidden="true">'+data.counsel.guests.map((g,i)=>'<span class="'+(i<counselIndex?"done":i===counselIndex?"now":"wait")+'"><img src="assets/jelly-face-'+(i<counselIndex?5:4)+'.webp" alt="">'+(i<counselIndex?"<i>✓</i>":"")+'</span>').join("")+'</div>'}
function counselShow(){const C=data.counsel,g=C.guests[counselIndex],box=$("#energyBins");$("#classifyCounter").textContent=Math.min(counselIndex+1,C.guests.length)+" / "+C.guests.length;
  helpBar("classifyHelp",$("#classifyFeedback"));const hb=$("#classifyHelp");if(hb)hb.innerHTML="";
  if(!g){$("#classifyH2").textContent="오늘 해결 임무 끝!";box.innerHTML='<div class="counsel-stage done"><div class="counsel-guest"><img class="counsel-face" src="assets/jelly-face-5.webp" alt=""></div><p class="counsel-bubble">'+escapeHTML(C.done||"문제를 모두 해결해 줘서 고마워!")+'</p></div>'+counselQueue();$("#counselOpts").innerHTML="";feedback($("#classifyFeedback"),"친구 "+C.guests.length+"명의 문제를 모두 해결했어요!","ok");return}
  $("#classifyH2").textContent=(counselIndex+1)+"번째 친구, "+g.name;
  box.innerHTML='<div class="counsel-stage"><div class="counsel-guest"><span class="counsel-prop" aria-hidden="true">'+propHTML(g.prop)+'</span><span class="counsel-react" id="counselReact" aria-hidden="true"></span><img class="counsel-face" src="assets/jelly-face-4.webp" alt=""><b>'+escapeHTML(g.name)+'</b></div><p class="counsel-bubble" id="counselBubble">'+escapeHTML(g.worry)+'</p></div>'+counselQueue();
  const stage=$(".counsel-stage",box);stage.classList.add("enter");
  const opts=$("#counselOpts");opts.innerHTML="";g.opts.forEach((t,i)=>{const b=document.createElement("button");b.type="button";b.className="counsel-opt";b.dataset.track="answer";b.dataset.correct=String(i===g.a);b.textContent=t;b.onclick=()=>counselAnswer(i,b);opts.append(b)});
  feedback($("#classifyFeedback"),"문제를 끝까지 읽고, 글에서 알게 된 것으로 해결해 줘요.","")}
function counselFace(n){const f=$(".counsel-face");if(f){f.src="assets/jelly-face-"+n+".webp";f.classList.remove("bob");void f.offsetWidth;f.classList.add("bob")}}
function counselAnswer(i,btn){const C=data.counsel,g=C.guests[counselIndex];if(!g)return;const id="problem-solver-"+(counselIndex+1),a=assistItem(id);if(a.done)return;a.tries++;const correct=i===g.a;log("answer",id,{response:i,correct,attempt:a.tries});
  if(!correct){btn.disabled=true;btn.classList.add("no");counselFace(2);const rc=$("#counselReact");if(rc){rc.textContent=g.no||"음… 아닌 것 같아";rc.classList.remove("show");void rc.offsetWidth;rc.classList.add("show")}setTimeout(()=>{if(!assistItem(id).done)counselFace(4)},1400);const st=$(".counsel-stage");st.classList.remove("shake");void st.offsetWidth;st.classList.add("shake");
    feedback($("#classifyFeedback"),g.hint||"문제를 다시 읽고, 글에서 배운 것을 떠올려 봐요.","bad");const bar=helpBar("classifyHelp",$("#classifyFeedback"));bar.innerHTML="";
    if(g.ev)bar.append(helpButton("글에서 찾아보기","A3","evidence-sentence",id,()=>{feedback($("#classifyFeedback"),"글에서: 「"+g.ev+"」","")}));
    if(a.tries>=2)bar.append(helpButton("알맞은 답 보기","A4","answer-reveal",id,()=>$$(".counsel-opt")[g.a].classList.add("reveal")));return}
  itemResult(id);$$(".counsel-opt").forEach(b=>b.disabled=true);btn.classList.add("yes");counselFace(5);$("#counselBubble").textContent=g.thanks||"고마워! 이제 알겠어!";$(".counsel-stage").classList.add("happy");
  const hb=$("#classifyHelp");if(hb)hb.innerHTML="";feedback($("#classifyFeedback"),"문제 해결! "+g.name+"의 얼굴이 밝아졌어요.","ok");
  const next=document.createElement("button");next.type="button";next.className="counsel-next";next.textContent=counselIndex+1<C.guests.length?"다음 친구 만나기":"해결 임무 마치기";next.onclick=()=>{counselIndex++;counselShow()};$("#counselOpts").append(next)}
function hintOnOpenOnly(btn,isOpen){if(!btn||btn.dataset.hintOnOpen)return;btn.dataset.hintOnOpen="1";const set=()=>{if(isOpen())btn.removeAttribute("data-track");else btn.dataset.track="hint"};btn.addEventListener("pointerdown",set,true);btn.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" ")set()},true)}
document.addEventListener("DOMContentLoaded",()=>{hintOnOpenOnly($("#passageToggle"),()=>$("#readingPaper").classList.contains("peek"));hintOnOpenOnly($("#spyPeek"),()=>!$("#spyPeekPanel").classList.contains("hidden"))});
/* 단어장: 눌러 본 낱말이 저절로 담김(폴더 단위로 쌓임) */
const WB_KEY=LID+":wordbook";
function wordbookGet(){try{return JSON.parse(localStorage.getItem(WB_KEY)||"[]")}catch(e){return[]}}
function wordbookAdd(v){const wb=wordbookGet();if(wb.some(x=>x.w===v[0]))return false;wb.push({w:v[0],h:v[1]||"",m:v[2]||"",e:v[3]||"",s:SID,t:(data.meta&&data.meta.title)||""});try{localStorage.setItem(WB_KEY,JSON.stringify(wb))}catch(e){}wordbookCount();return true}
function wordbookCount(){const b=$("#wordbookButton");if(b)b.innerHTML="📒 단어장 <b>"+wordbookGet().length+"</b>"}
function openWordbook(){const wb=wordbookGet(),list=$("#wordbookList");list.innerHTML=wb.length?wb.slice().reverse().map(x=>{const parts=x.h.split("·"),hj=/[\u4e00-\u9fff]/.test(parts[0])?parts[0].trim():"";return '<li><details><summary><b>'+escapeHTML(x.w)+'</b>'+(hj?'<span class="wb-hanja">'+escapeHTML(hj)+'</span>':'')+'<small>'+escapeHTML(x.m)+'</small></summary>'+(hj&&parts[1]?'<p class="wb-gloss">'+escapeHTML(parts.slice(1).join("·").trim())+'</p>':'')+'<p class="wb-ex">'+escapeHTML(x.e)+'</p></details></li>'}).join(""):'<li class="wb-empty">아직 담긴 낱말이 없어요. 글에서 점선이 그어진 낱말을 눌러 보세요.</li>';$("#wordbookDialog").classList.remove("hidden");log("wordbook_open","wordbook",{count:wb.length})}
document.addEventListener("DOMContentLoaded",()=>{const tools=$(".footer-tools");if(tools&&!$("#wordbookButton")){const b=document.createElement("button");b.type="button";b.id="wordbookButton";b.className="wordbook-button";b.onclick=openWordbook;tools.insertBefore(b,tools.children[1]||null)}
  if(!$("#wordbookDialog")){const d=document.createElement("div");d.className="vocab-dialog wordbook-dialog hidden";d.id="wordbookDialog";d.innerHTML='<section role="dialog" aria-modal="true" aria-labelledby="wordbookTitle"><button class="vocab-close" id="wordbookClose" aria-label="닫기">×</button><small>내가 찾아본 낱말</small><h2 id="wordbookTitle">📒 나의 단어장</h2><ul class="wordbook-list" id="wordbookList"></ul></section>';document.body.append(d);d.onclick=e=>{if(e.target===d)d.classList.add("hidden")};$("#wordbookClose").onclick=()=>d.classList.add("hidden")}
  wordbookCount()});
/* 그림: 단락 그림·소품 그림 */
const PROP_IMG={"🔍": "assets/props/magnifier.webp", "📒": "assets/props/notebook.webp", "📋": "assets/props/clipboard.webp", "📝": "assets/props/memo.webp", "🧺": "assets/props/basket.webp", "🗺️": "assets/props/map.webp", "🎒": "assets/props/backpack.webp", "🪣": "assets/props/bucket.webp", "🖍️": "assets/props/crayon.webp", "📷": "assets/props/camera.webp", "✏️": "assets/props/pencil.webp", "🔭": "assets/props/telescope.webp", "🧸": "assets/props/teddy.webp", "🏺": "assets/props/jar.webp", "📱": "assets/props/phone.webp", "📖": "assets/props/book.webp", "🪵": "assets/props/log.webp", "🔦": "assets/props/flashlight.webp", "🧭": "assets/props/compass.webp", "🛒": "assets/props/cart.webp", "☂️": "assets/props/umbrella.webp", "🎈": "assets/props/balloon.webp", "🪴": "assets/props/plant.webp", "📜": "assets/props/scroll.webp", "⏰": "assets/props/clock.webp", "✉️": "assets/props/letter.webp", "🥄": "assets/props/spoon.webp", "⚽": "assets/props/ball.webp", "🧹": "assets/props/broom.webp", "🪁": "assets/props/kite.webp"};
function propHTML(e){const src=PROP_IMG[e];return src?'<img src="'+src+'" alt="">':escapeHTML(e||"")}
function showParaPic(i){const box=$("#readingCoachPanel");if(!box)return;let wrap=$("#paraPic");if(!wrap){wrap=document.createElement("div");wrap.id="paraPic";wrap.className="para-pic";const btn=$("#readingDone");box.insertBefore(wrap,btn)}const list=((data.pictures&&data.pictures.paras)||{})[String(i)]||[];wrap.innerHTML=list.map(src=>'<img src="'+escapeHTML(src)+'" alt="">').join("");wrap.hidden=!list.length}
document.addEventListener("DOMContentLoaded",boot);
})();
