/* 「박혁거세와 알영」 읽기유창성 — 세 회차분 데이터.
 *
 * 회차 배정은 「목표_본문」 배정표를 따랐다.
 *   1회차 2~4쪽 · H11 낯선 단어가 포함된 문장
 *   2회차 5~7쪽 · H9  문장 안 복수 음운규칙
 *   3회차 8~10쪽 · H11 낯선 단어가 포함된 문장
 *
 * 본문은 **원문 그대로**다(배정표의 「원문 유지」). 쉽게 고쳐 쓰지 않는다.
 * rule 값은 음운규칙 정본 열셋에서만 고른다.
 */
window.ONQ_CONTENT_PACK = Object.freeze({
  version: "0.1.0",
  series: "읽기유창성",
  bookTitle: "박혁거세와 알영",
  credit: {
    title: "박혁거세와 알영",
    originalText: "이한",
    originalArt: "이소리",
    koreanText: "김은파 · 이수인",
    source: "두루책방",
    license: "CC BY 4.0",
    modified: "변경함 — 읽기유창성 수업용으로 재구성(회차 분할·활동 추가)",
    programRights: "읽기유창성 프로그램 활동 · 평가 설계 © 온큐베이트",
    allRights: "© 2026 온큐베이트. All rights reserved."
  },
  sourceLicense: "CC BY 4.0 · © 2019 Enuma, Inc. & The Foundation SeeArt for Book Culture",

  sessions: {
    // ── 1회차 ─────────────────────────────────────────────────────────────
    // 겨냥: 처음 보는 낱말(서라벌·촌장·의논)에도 받침 이어 읽기를 그대로 적용하기.
    session01: {
      lessonId: "reading.fluency.phg-alyeong.s01",
      sessionLabel: "1회차",
      range: "그림책 2~4쪽",
      coverTitle: "임금을 찾아라",
      goal: "처음 보는 낱말도 규칙대로 읽어 문장으로 이어 읽어요.",
      coverImage: "assets/book/page-01.webp",
      focusRules: [
        "받침 뒤에 모음이 오면 소리를 자연스럽게 이어 읽어요.",
        "처음 보는 낱말도 아는 규칙을 그대로 적용해 읽어요.",
        "긴 문장은 뜻이 이어지는 짧은 덩어리로 나누어 읽어요."
      ],
      game2: [
        { word: "서라벌이라는", phrase: "서라벌이라는 곳이", rule: "liaison" },
        { word: "한반도의", phrase: "먼 옛날 한반도의", rule: "liaison" },
        { word: "마을이", phrase: "여섯 마을이", rule: "liaison" },
        { word: "있었고", phrase: "마을이 있었고", rule: "liaison" },
        { word: "사람들은", phrase: "마을 사람들은", rule: "liaison" },
        { word: "살았습니다", phrase: "오순도순 살았습니다", rule: "nasalization" },
        { word: "촌장들은", phrase: "여섯 마을의 촌장들은", rule: "liaison" },
        { word: "의논했습니다", phrase: "함께 모여 의논했습니다", rule: "nasalization" },
        { word: "훌륭한", phrase: "훌륭한 임금", rule: "lateralization" },
        { word: "임금을", phrase: "훌륭한 임금을", rule: "liaison" },
        { word: "고민이었습니다", phrase: "어디서 찾을지가 고민이었습니다", rule: "liaison" },
        { word: "달려갔습니다", phrase: "곳으로 달려갔습니다", rule: "nasalization" }
      ],
      game1: [
        { word: "서라벌이라는", chunks: ["서","라","벌","이","라","는"], distractors: ["써","나","버","리","나","능"], hint: "셋째 글자에는 받침 ㄹ이 있어요.", rule: "liaison" },
        { word: "한반도의", chunks: ["한","반","도","의"], distractors: ["한","방","토","에"], hint: "둘째 글자 받침은 ㄴ이에요.", rule: "liaison" },
        { word: "마을이", chunks: ["마","을","이"], distractors: ["마","은","리"], hint: "둘째 글자 받침 ㄹ이 뒤로 넘어가요.", rule: "liaison" },
        { word: "있었고", chunks: ["있","었","고"], distractors: ["이","엇","꼬"], hint: "첫 글자에는 받침 ㅆ이 있어요.", rule: "liaison" },
        { word: "사람들은", chunks: ["사","람","들","은"], distractors: ["싸","남","들","는"], hint: "마지막 글자는 앞 받침이 넘어와요.", rule: "liaison" },
        { word: "살았습니다", chunks: ["살","았","습","니","다"], distractors: ["살","앋","씀","미","타"], hint: "「습니다」는 「슴니다」로 소리 나요.", rule: "nasalization" },
        { word: "촌장들은", chunks: ["촌","장","들","은"], distractors: ["촌","잔","득","는"], hint: "둘째 글자 받침은 ㅇ이에요.", rule: "liaison" },
        { word: "의논했습니다", chunks: ["의","논","했","습","니","다"], distractors: ["이","놈","핻","씀","미","타"], hint: "「했습니다」는 「핻씀니다」로 소리 나요.", rule: "nasalization" },
        { word: "훌륭한", chunks: ["훌","륭","한"], distractors: ["훌","늉","안"], hint: "받침 ㄹ 뒤의 ㄹ소리를 이어 읽어요.", rule: "lateralization" },
        { word: "임금을", chunks: ["임","금","을"], distractors: ["임","끔","은"], hint: "마지막 글자에 앞 받침 ㅁ이 넘어와요.", rule: "liaison" },
        { word: "고민이었습니다", chunks: ["고","민","이","었","습","니","다"], distractors: ["코","밈","리","엇","씀","미","타"], hint: "「민이」는 「미니」로 이어 읽어요.", rule: "liaison" },
        { word: "달려갔습니다", chunks: ["달","려","갔","습","니","다"], distractors: ["딸","여","갇","씀","미","타"], hint: "「갔습니다」는 「갇씀니다」로 소리 나요.", rule: "nasalization" }
      ],
      wordPool: [
        { word: "서라벌이라는", related: true },
        { word: "촌장들은", related: true },
        { word: "임금을", related: true },
        { word: "하얀 말이", related: true },
        { word: "의논했습니다", related: true },
        { word: "달려갔습니다", related: true },
        { word: "지하철이", related: false },
        { word: "냉장고를", related: false },
        { word: "축구공은", related: false },
        { word: "휴대전화가", related: false },
        { word: "놀이터에서", related: false },
        { word: "아이스크림을", related: false }
      ],
      vocab: [
        { word: "촌장",
          image: "assets/vocab/vocab-s01-01-chief.webp", alt: "마을 사람들 앞에 서서 손을 들어 이야기를 이끄는 나이 든 어른",
          bookImage: "assets/book/art/page-03-art.webp", bookAlt: "여섯 마을의 어른들이 둘러서서 의논하는 그림",
          daily: { frame: ["마을을 이끄는 어른을 ", "이라고 해요."], answer: "촌장", other: "손님" },
          book: { frame: ["어느 날, 여섯 마을의 ", "들은 함께 모여 의논했습니다."], answer: "촌장", other: "손님" },
          meaning: "마을을 대표해서 이끄는 어른이에요." },
        { word: "의논하다",
          image: "assets/vocab/vocab-s01-02-discuss.webp", alt: "아이 셋이 머리를 맞대고 종이를 함께 보며 의견을 나누는 모습",
          bookImage: "assets/book/art/page-03-art.webp", bookAlt: "촌장들이 모여 이야기를 나누는 그림",
          daily: { frame: ["친구들과 머리를 맞대고 ", "."], answer: "의논해요", other: "의심해요" },
          book: { frame: ["촌장들은 함께 모여 ", "."], answer: "의논했습니다", other: "의심했습니다" },
          meaning: "어떻게 할지 서로 이야기해서 정하는 거예요." },
        { word: "고민",
          image: "assets/vocab/vocab-s01-03-worry.webp", alt: "턱을 괴고 눈썹을 모은 채 골똘히 생각하는 아이",
          bookImage: "assets/book/art/page-03-art.webp", bookAlt: "임금을 어디서 찾을지 생각에 잠긴 촌장들 그림",
          daily: { frame: ["어떻게 할지 몰라 ", "이에요."], answer: "고민", other: "구경" },
          book: { frame: ["훌륭한 임금을 어디서 찾을지가 ", "이었습니다."], answer: "고민", other: "구경" },
          meaning: "어떻게 해야 할지 몰라 마음속으로 걱정하며 생각하는 거예요." },
        { word: "오순도순",
          image: "assets/vocab/vocab-s01-04-harmony.webp", alt: "한 상에 둘러앉아 웃으며 함께 밥을 먹는 가족",
          bookImage: "assets/book/art/page-02-art.webp", bookAlt: "여섯 마을이 나란히 자리 잡은 서라벌 그림",
          daily: { frame: ["가족이 둘러앉아 ", " 밥을 먹어요."], answer: "오순도순", other: "허둥지둥" },
          book: { frame: ["마을 사람들은 임금 없이 ", " 살았습니다."], answer: "오순도순", other: "허둥지둥" },
          meaning: "서로 사이좋게 어울려 지내는 모습이에요." },
        { word: "훌륭하다",
          image: "assets/vocab/vocab-s01-05-splendid.webp", alt: "상장을 두 손으로 들고 환하게 웃는 아이",
          bookImage: "assets/book/art/page-03-art.webp", bookAlt: "훌륭한 임금을 세우자고 이야기하는 촌장들 그림",
          daily: { frame: ["아주 잘해서 ", " 솜씨라고 해요."], answer: "훌륭한", other: "흐릿한" },
          book: { frame: ["“우리도 나라를 만들고 ", " 임금을 세우자!”"], answer: "훌륭한", other: "흐릿한" },
          meaning: "아주 잘하고 뛰어나서 칭찬받을 만한 거예요." }
      ],
      sentences: [
        { page: 2, text: "먼 옛날 한반도의 남쪽에 서라벌이라는 곳이 있었습니다.",
          focus: "서라벌이라는", guide: "처음 보는 낱말이라도 끊지 말고 한 덩어리로 이어 읽어요.",
          apply: "경주라는 곳이 있었습니다.", rule: "liaison" },
        { page: 2, text: "그곳에는 여섯 마을이 있었고 마을 사람들은 임금 없이 오순도순 살았습니다.",
          focus: "마을이", guide: "받침 ㄹ이 뒤로 넘어가 「마으리」로 소리 나요.",
          apply: "마을이 아주 조용했어요.", rule: "liaison" },
        { page: 3, text: "어느 날, 여섯 마을의 촌장들은 함께 모여 의논했습니다.",
          focus: "의논했습니다", guide: "「했습니다」는 「핻씀니다」로 콧소리가 나요.",
          apply: "우리도 함께 의논했습니다.", rule: "nasalization" },
        { page: 3, text: "“우리도 나라를 만들고 훌륭한 임금을 세우자!”",
          focus: "임금을", guide: "받침 ㅁ이 뒤로 넘어가 「임그믈」로 소리 나요.",
          apply: "훌륭한 임금을 기다렸어요.", rule: "liaison" },
        { page: 3, text: "그런데 훌륭한 임금을 어디서 찾을지가 고민이었습니다.",
          focus: "고민이었습니다", guide: "「민이」를 「미니」로 이어 읽어요.",
          apply: "밤새 고민이었습니다.", rule: "liaison" },
        { page: 4, text: "그때였습니다. 하늘에서 하얀 말이 내려왔습니다!",
          focus: "말이", guide: "받침 ㄹ이 뒤로 넘어가 「마리」로 소리 나요.",
          apply: "하얀 말이 달려왔어요.", rule: "liaison" },
        { page: 4, text: "깜짝 놀란 촌장들은 말이 내려온 곳으로 달려갔습니다.",
          focus: "촌장들은", guide: "「들은」을 「드른」으로 이어 읽어요.",
          apply: "촌장들은 서둘러 모였어요.", rule: "liaison" }
      ],
      questions: [
        { prompt: "서라벌에는 마을이 몇 개 있었나요?", answer: 1 },
        { prompt: "촌장들이 함께 모여 하려던 일은 무엇인가요?", answer: 3 },
        { prompt: "촌장들의 고민은 무엇이었나요?", answer: 4 },
        { prompt: "하늘에서 내려온 것은 무엇인가요?", answer: 5 },
        { prompt: "촌장들이 달려간 까닭이 드러난 문장을 찾아보세요.", answer: 6 }
      ]
    },

    // ── 2회차 ─────────────────────────────────────────────────────────────
    // 겨냥: 한 문장 안에 규칙이 둘 이상 걸려도 흐름을 잃지 않기.
    session02: {
      lessonId: "reading.fluency.phg-alyeong.s02",
      sessionLabel: "2회차",
      range: "그림책 5~7쪽",
      coverTitle: "알에서 나온 아이",
      goal: "한 문장에 규칙이 둘 이상 있어도 흐름을 이어 읽어요.",
      coverImage: "assets/book/page-01.webp",
      focusRules: [
        "한 문장 안에 여러 소리 규칙이 함께 걸려도 흐름을 유지해 읽어요.",
        "겹받침은 하나만 남거나 나뉘어 넘어가는 것을 가려 읽어요.",
        "긴 문장은 뜻이 이어지는 짧은 덩어리로 나누어 읽어요."
      ],
      game2: [
        { word: "앉아", phrase: "우물가에 앉아", rule: "clusterLiaison" },
        { word: "알을", phrase: "커다란 알을", rule: "liaison" },
        { word: "낳았습니다", phrase: "알을 낳았습니다", rule: "hDeletion" },
        { word: "높이", phrase: "하늘 높이", rule: "liaison" },
        { word: "날아가", phrase: "하늘 높이 날아가", rule: "liaison" },
        { word: "알이", phrase: "알이 깨어지며", rule: "liaison" },
        { word: "빛이", phrase: "몸에서는 빛이", rule: "neutralizedLiaison" },
        { word: "났고", phrase: "빛이 났고", rule: "tensification" },
        { word: "알에서", phrase: "둥근 알에서", rule: "liaison" },
        { word: "박씨가", phrase: "박씨가 되었습니다", rule: "tensification" },
        { word: "밝게", phrase: "밝게 빛난다는", rule: "clusterReduction" },
        { word: "빛난다는", phrase: "밝게 빛난다는 뜻", rule: "nasalization" }
      ],
      game1: [
        { word: "앉아", chunks: ["앉","아"], distractors: ["안","나"], hint: "겹받침 ㄵ 중 ㅈ이 뒤로 넘어가요.", rule: "clusterLiaison" },
        { word: "알을", chunks: ["알","을"], distractors: ["알","은"], hint: "받침 ㄹ이 뒤로 넘어가요.", rule: "liaison" },
        { word: "낳았습니다", chunks: ["낳","았","습","니","다"], distractors: ["나","앋","씀","미","타"], hint: "ㅎ이 사라져 「나앋씀니다」로 소리 나요.", rule: "hDeletion" },
        { word: "높이", chunks: ["높","이"], distractors: ["놉","히"], hint: "받침 ㅍ이 뒤로 넘어가 「노피」예요.", rule: "liaison" },
        { word: "날아가", chunks: ["날","아","가"], distractors: ["난","나","까"], hint: "받침 ㄹ이 뒤로 넘어가요.", rule: "liaison" },
        { word: "알이", chunks: ["알","이"], distractors: ["안","리"], hint: "「아리」로 이어 읽어요.", rule: "liaison" },
        { word: "빛이", chunks: ["빛","이"], distractors: ["빋","시"], hint: "받침 ㅊ이 뒤로 넘어가 「비치」예요.", rule: "neutralizedLiaison" },
        { word: "났고", chunks: ["났","고"], distractors: ["낟","꼬"], hint: "뒤 글자가 된소리로 바뀌어요.", rule: "tensification" },
        { word: "알에서", chunks: ["알","에","서"], distractors: ["안","레","써"], hint: "「아레서」로 이어 읽어요.", rule: "liaison" },
        { word: "박씨가", chunks: ["박","씨","가"], distractors: ["박","시","까"], hint: "된소리 ㅆ을 또렷하게 읽어요.", rule: "tensification" },
        { word: "밝게", chunks: ["밝","게"], distractors: ["발","께"], hint: "겹받침 중 ㄱ만 남아 「박께」예요.", rule: "clusterReduction" },
        { word: "빛난다는", chunks: ["빛","난","다","는"], distractors: ["빈","난","따","능"], hint: "받침이 콧소리로 바뀌어 「빈난다는」이에요.", rule: "nasalization" }
      ],
      wordPool: [
        { word: "우물가에", related: true },
        { word: "커다란 알을", related: true },
        { word: "남자아이가", related: true },
        { word: "박씨가", related: true },
        { word: "혁거세", related: true },
        { word: "밝게", related: true },
        { word: "택배 상자", related: false },
        { word: "지우개를", related: false },
        { word: "엘리베이터", related: false },
        { word: "청소기가", related: false },
        { word: "자전거를", related: false },
        { word: "텔레비전", related: false }
      ],
      vocab: [
        { word: "우물가",
          image: "assets/vocab/vocab-s02-01-well.webp", alt: "돌을 둥글게 쌓은 우물과 두레박, 옆에 놓인 물동이",
          bookImage: "assets/book/art/page-05-art.webp", bookAlt: "우물가에 앉은 하얀 말 그림",
          daily: { frame: ["두레박으로 물을 긷는 곳은 ", "예요."], answer: "우물가", other: "모래밭" },
          book: { frame: ["하얀 말은 ", "에 앉아 커다란 알을 낳았습니다."], answer: "우물가", other: "모래밭" },
          meaning: "물을 긷는 우물이 있는 자리예요." },
        { word: "반기다",
          image: "assets/vocab/vocab-s02-02-welcome.webp", alt: "대문 앞에서 두 팔을 벌린 아이에게 강아지가 뛰어오는 모습",
          bookImage: "assets/book/art/page-06-art.webp", bookAlt: "알에서 나온 아기를 둘러싼 빛과 새들 그림",
          daily: { frame: ["두 팔을 벌려 강아지를 ", "."], answer: "반겨요", other: "말려요" },
          book: { frame: ["새와 짐승, 해와 달도 아기를 보고 ", "."], answer: "반겼습니다", other: "말렸습니다" },
          meaning: "반가워하며 기쁘게 맞이하는 거예요." },
        { word: "신기하다",
          image: "assets/vocab/vocab-s02-03-amazed.webp", alt: "눈을 동그랗게 뜨고 하늘의 무지개를 올려다보는 아이",
          bookImage: "assets/book/art/page-07-art.webp", bookAlt: "알에서 나온 아이를 바라보는 사람들 그림",
          daily: { frame: ["무지개를 보고 ", " 눈이 커졌어요."], answer: "신기해서", other: "심심해서" },
          book: { frame: ["사람들은 ", "하면서도 기뻐했습니다."], answer: "신기해", other: "심심해" },
          meaning: "처음 보는 것이 놀랍고 이상해서 자꾸 보고 싶은 마음이에요." },
        { word: "둥글다",
          image: "assets/vocab/vocab-s02-04-round.webp", alt: "공과 수박, 보름달, 동그란 접시가 나란히 놓인 그림",
          bookImage: "assets/book/art/page-07-art.webp", bookAlt: "박처럼 둥근 알에서 나온 아이 그림",
          daily: { frame: ["공과 수박은 모두 ", "."], answer: "둥글어요", other: "뾰족해요" },
          book: { frame: ["아이는 박처럼 ", " 알에서 나왔습니다."], answer: "둥근", other: "뾰족한" },
          meaning: "모난 데 없이 공처럼 동그란 모양이에요." },
        { word: "짐승",
          image: "assets/vocab/vocab-s02-05-beast.webp", alt: "숲속 빈터에 함께 있는 사슴과 토끼와 여우",
          bookImage: "assets/book/art/page-06-art.webp", bookAlt: "아기를 보고 반기는 새와 동물들 그림",
          daily: { frame: ["숲에 사는 사슴과 여우를 ", "이라고 해요."], answer: "짐승", other: "지붕" },
          book: { frame: ["새와 ", ", 해와 달도 아기를 보고 반겼습니다."], answer: "짐승", other: "지붕" },
          meaning: "네 발로 걷는 산이나 들의 동물이에요." }
      ],
      sentences: [
        { page: 5, text: "하얀 말은 우물가에 앉아 커다란 알을 낳았습니다.",
          focus: "앉아", guide: "겹받침 ㄵ에서 ㅈ이 뒤로 넘어가 「안자」로 소리 나요.",
          apply: "의자에 앉아 기다려요.", rule: "clusterLiaison" },
        { page: 5, text: "그리고 다시 하늘 높이 날아가 버렸습니다.",
          focus: "높이", guide: "받침 ㅍ이 뒤로 넘어가 「노피」로 소리 나요.",
          apply: "연이 하늘 높이 올라가요.", rule: "liaison" },
        { page: 6, text: "알이 깨어지며 한 남자아이가 나왔습니다.",
          focus: "알이", guide: "받침 ㄹ이 뒤로 넘어가 「아리」로 소리 나요.",
          apply: "알이 톡 깨어졌어요.", rule: "liaison" },
        { page: 6, text: "아기의 몸에서는 빛이 났고 새와 짐승, 해와 달도 아기를 보고 반겼습니다.",
          focus: "빛이", guide: "받침 ㅊ이 뒤로 넘어가 「비치」로 소리 나요.",
          apply: "창으로 빛이 들어와요.", rule: "neutralizedLiaison" },
        { page: 7, text: "사람들은 신기해하면서도 기뻐했습니다.",
          focus: "사람들은", guide: "「들은」을 「드른」으로 이어 읽어요.",
          apply: "사람들은 모두 웃었어요.", rule: "liaison" },
        { page: 7, text: "아이는 박처럼 둥근 알에서 나왔다고 해서 박씨가 되었습니다.",
          focus: "알에서", guide: "받침 ㄹ이 뒤로 넘어가 「아레서」로 소리 나요.",
          apply: "둥근 알에서 나왔어요.", rule: "liaison" },
        { page: 7, text: "이름은 혁거세입니다. 밝게 빛난다는 뜻입니다.",
          focus: "밝게", guide: "겹받침 중 ㄱ만 남아 「박께」로 소리 나요.",
          apply: "달이 밝게 빛나요.", rule: "clusterReduction" }
      ],
      questions: [
        { prompt: "하얀 말이 우물가에서 한 일은 무엇인가요?", answer: 0 },
        { prompt: "알에서 나온 것은 누구인가요?", answer: 2 },
        { prompt: "아기를 보고 반긴 것들은 무엇인가요?", answer: 3 },
        { prompt: "아이가 박씨가 된 까닭은 무엇인가요?", answer: 5 },
        { prompt: "「혁거세」라는 이름의 뜻이 나온 문장을 찾아보세요.", answer: 6 }
      ]
    },

    // ── 3회차 ─────────────────────────────────────────────────────────────
    // 겨냥: 계룡·시조처럼 처음 보는 낱말에도 규칙을 그대로 적용하기.
    session03: {
      lessonId: "reading.fluency.phg-alyeong.s03",
      sessionLabel: "3회차",
      range: "그림책 8~10쪽",
      coverTitle: "우물에서 온 아이",
      goal: "처음 보는 낱말도 규칙대로 읽어 이야기를 끝까지 이어 읽어요.",
      coverImage: "assets/book/page-01.webp",
      focusRules: [
        "받침 뒤에 모음이 오면 소리를 자연스럽게 이어 읽어요.",
        "처음 보는 낱말도 아는 규칙을 그대로 적용해 읽어요.",
        "긴 문장은 뜻이 이어지는 짧은 덩어리로 나누어 읽어요."
      ],
      game2: [
        { word: "옆에는", phrase: "우물 옆에는", rule: "liaison" },
        { word: "닭의", phrase: "닭의 머리", rule: "clusterLiaison" },
        { word: "계룡이", phrase: "계룡이 나타났습니다", rule: "liaison" },
        { word: "나타났습니다", phrase: "계룡이 나타났습니다", rule: "nasalization" },
        { word: "낳고", phrase: "여자아이를 낳고", rule: "aspiration" },
        { word: "날아갔습니다", phrase: "하늘로 날아갔습니다", rule: "nasalization" },
        { word: "떨어지자", phrase: "닭 부리가 떨어지자", rule: "liaison" },
        { word: "모습이", phrase: "사람의 모습이", rule: "liaison" },
        { word: "이름을", phrase: "우물 이름을", rule: "liaison" },
        { word: "알영이라고", phrase: "알영이라고 불렸습니다", rule: "liaison" },
        { word: "신라의", phrase: "신라의 왕과 왕비", rule: "lateralization" },
        { word: "시조입니다", phrase: "경주 박씨의 시조입니다", rule: "nasalization" }
      ],
      game1: [
        { word: "옆에는", chunks: ["옆","에","는"], distractors: ["엽","페","능"], hint: "받침 ㅍ이 뒤로 넘어가 「여페는」이에요.", rule: "liaison" },
        { word: "닭의", chunks: ["닭","의"], distractors: ["닥","이"], hint: "겹받침 ㄺ에서 ㄱ이 뒤로 넘어가요.", rule: "clusterLiaison" },
        { word: "계룡이", chunks: ["계","룡","이"], distractors: ["게","뇽","리"], hint: "「룡이」를 「룡이」로 이어 읽어요.", rule: "liaison" },
        { word: "나타났습니다", chunks: ["나","타","났","습","니","다"], distractors: ["나","따","낟","씀","미","타"], hint: "「났습니다」는 「낟씀니다」로 소리 나요.", rule: "nasalization" },
        { word: "낳고", chunks: ["낳","고"], distractors: ["나","꼬"], hint: "ㅎ과 ㄱ이 만나 「나코」가 돼요.", rule: "aspiration" },
        { word: "날아갔습니다", chunks: ["날","아","갔","습","니","다"], distractors: ["난","나","갇","씀","미","타"], hint: "받침 ㄹ이 뒤로 넘어가요.", rule: "nasalization" },
        { word: "떨어지자", chunks: ["떨","어","지","자"], distractors: ["떠","러","치","차"], hint: "「떠러지자」로 이어 읽어요.", rule: "liaison" },
        { word: "모습이", chunks: ["모","습","이"], distractors: ["모","슴","시"], hint: "받침 ㅂ이 뒤로 넘어가 「모스비」예요.", rule: "liaison" },
        { word: "이름을", chunks: ["이","름","을"], distractors: ["이","늠","은"], hint: "받침 ㅁ이 뒤로 넘어가요.", rule: "liaison" },
        { word: "알영이라고", chunks: ["알","영","이","라","고"], distractors: ["안","영","리","나","꼬"], hint: "「영이」를 「영이」로 이어 읽어요.", rule: "liaison" },
        { word: "신라의", chunks: ["신","라","의"], distractors: ["신","나","에"], hint: "ㄴ이 ㄹ소리로 바뀌어 「실라」예요.", rule: "lateralization" },
        { word: "시조입니다", chunks: ["시","조","입","니","다"], distractors: ["시","초","임","미","타"], hint: "「입니다」는 「임니다」로 소리 나요.", rule: "nasalization" }
      ],
      wordPool: [
        { word: "알영 우물", related: true },
        { word: "계룡이", related: true },
        { word: "닭 부리", related: true },
        { word: "신라의", related: true },
        { word: "왕과 왕비", related: true },
        { word: "시조입니다", related: true },
        { word: "비행기가", related: false },
        { word: "떡볶이를", related: false },
        { word: "공책에다", related: false },
        { word: "선풍기는", related: false },
        { word: "미끄럼틀", related: false },
        { word: "컴퓨터를", related: false }
      ],
      vocab: [
        { word: "부리",
          image: "assets/vocab/vocab-s03-01-beak.webp", alt: "참새가 옆모습으로 서서 부리로 낟알을 쪼는 모습",
          bookImage: "assets/book/art/page-08-art.webp", bookAlt: "닭 머리를 한 용 계룡 그림",
          daily: { frame: ["참새가 ", "로 낟알을 쪼아요."], answer: "부리", other: "꼬리" },
          book: { frame: ["계룡은 닭 ", "를 가진 여자아이를 낳았습니다."], answer: "부리", other: "꼬리" },
          meaning: "새의 입이에요. 단단하고 뾰족해요." },
        { word: "시조",
          image: "assets/vocab/vocab-s03-02-ancestor.webp", alt: "맨 위 어른에게서 자손이 아래로 이어지는 가족 그림",
          bookImage: "assets/book/art/page-10-art.webp", bookAlt: "왕과 왕비가 된 박혁거세와 알영 그림",
          daily: { frame: ["집안의 맨 처음 어른을 ", "라고 해요."], answer: "시조", other: "사촌" },
          book: { frame: ["두 사람은 경주 박씨의 ", "입니다."], answer: "시조", other: "사촌" },
          meaning: "한 집안이나 나라를 처음 시작한 사람이에요." },
        { word: "왕비",
          image: "assets/vocab/vocab-s03-03-queen.webp", alt: "금관을 쓴 왕과 왕비가 나란히 선 모습",
          bookImage: "assets/book/art/page-10-art.webp", bookAlt: "신라의 왕과 왕비가 된 두 사람 그림",
          daily: { frame: ["임금의 아내를 ", "라고 해요."], answer: "왕비", other: "왕자" },
          book: { frame: ["박혁거세와 알영은 신라의 왕과 ", "가 되었습니다."], answer: "왕비", other: "왕자" },
          meaning: "임금의 아내예요." },
        { word: "나타나다",
          image: "assets/vocab/vocab-s03-04-appear.webp", alt: "구름이 양옆으로 걷히며 그 사이로 무언가가 드러나는 모습",
          bookImage: "assets/book/art/page-08-art.webp", bookAlt: "알영 우물 옆에 나타난 계룡 그림",
          daily: { frame: ["구름이 걷히자 무지개가 ", "."], answer: "나타났어요", other: "사라졌어요" },
          book: { frame: ["알영 우물 옆에는 계룡이 ", "."], answer: "나타났습니다", other: "사라졌습니다" },
          meaning: "보이지 않던 것이 눈앞에 드러나는 거예요." },
        { word: "떨어지다",
          image: "assets/vocab/vocab-s03-05-fall-off.webp", alt: "나뭇가지에서 잎 하나가 막 떨어져 공중에 있는 순간",
          bookImage: "assets/book/art/page-09-art.webp", bookAlt: "닭 부리가 떨어져 사람 모습이 된 여자아이 그림",
          daily: { frame: ["가지에서 잎이 하나 ", "."], answer: "떨어져요", other: "매달려요" },
          book: { frame: ["닭 부리가 ", " 사람의 모습이 되었습니다."], answer: "떨어지자", other: "매달리자" },
          meaning: "붙어 있던 것이 아래로 내려오거나 떨어져 나가는 거예요." }
      ],
      sentences: [
        { page: 8, text: "한편, 알영 우물 옆에는 닭의 머리를 한 용, 계룡이 나타났습니다.",
          focus: "옆에는", guide: "받침 ㅍ이 뒤로 넘어가 「여페는」으로 소리 나요.",
          apply: "우물 옆에는 나무가 있어요.", rule: "liaison" },
        { page: 8, text: "계룡은 닭 부리를 가진 여자아이를 낳고 하늘로 날아갔습니다.",
          focus: "낳고", guide: "ㅎ과 ㄱ이 만나 거센소리 「나코」가 돼요.",
          apply: "알을 낳고 날아갔어요.", rule: "aspiration" },
        { page: 9, text: "닭 부리가 떨어지자 여자아이는 사람의 모습이 되었습니다.",
          focus: "모습이", guide: "받침 ㅂ이 뒤로 넘어가 「모스비」로 소리 나요.",
          apply: "본래 모습이 되었어요.", rule: "liaison" },
        { page: 9, text: "아이는 우물 이름을 따서 알영이라고 불렸습니다.",
          focus: "이름을", guide: "받침 ㅁ이 뒤로 넘어가 「이르믈」로 소리 나요.",
          apply: "이름을 따서 불렀어요.", rule: "liaison" },
        { page: 10, text: "박혁거세와 알영은 신라의 왕과 왕비가 되었습니다.",
          focus: "신라의", guide: "ㄴ이 ㄹ소리로 바뀌어 「실라의」로 소리 나요.",
          apply: "신라의 도읍은 경주예요.", rule: "lateralization" },
        { page: 10, text: "두 사람은 경주 박씨의 시조입니다.",
          focus: "시조입니다", guide: "「입니다」는 「임니다」로 콧소리가 나요.",
          apply: "우리 마을의 시조입니다.", rule: "nasalization" }
      ],
      questions: [
        { prompt: "알영 우물 옆에 나타난 것은 무엇인가요?", answer: 0 },
        { prompt: "계룡이 낳은 아이의 모습은 어땠나요?", answer: 1 },
        { prompt: "여자아이가 사람의 모습이 된 때는 언제인가요?", answer: 2 },
        { prompt: "「알영」이라는 이름은 어디에서 따왔나요?", answer: 3 },
        { prompt: "두 사람이 어떤 자리에 올랐는지 드러난 문장을 찾아보세요.", answer: 4 }
      ]
    }
  }
});
